### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by MaximeLBG**

### CODE REVIEW

**Comment by MaximeLBG** [comment]
@ArduinoBot

**Comment by MaximeLBG** [comment]
@ArduinoBot

**Comment by per1234** [comment]
Hello @MaximeLBG. I see you have fixed the error reported by the bot. However, Library Manager works exclusively from Git tags, so the bot won't be able to see the fix you made until you create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.

If you look at the repository contents at the latest tag, you can see that the version the bot is checking still has the problem:

https://github.com/MaximeLBG/CV7OEMFR/tree/v3.1.2

Once you have done that, simply mention **@ArduinoBot** in a comment here to trigger it to run the automated checks again. After those are passing, your library will automatically be added to Library Manager.

If you have any questions or concerns, please let me know.

Regards, Per

**Comment by per1234** [comment]
Closing as duplicate of https://github.com/arduino/library-registry/pull/1356

**Pull request closed without merging**
