### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by bavathd**

### CODE REVIEW

**Review by per1234 — COMMENTED** [review]
Hello @bavathd. I see you have fixed the error reported by the bot. However, Library Manager works exclusively from Git tags, so the bot won't be able to see the fix you made until you create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.

If you look at the repository contents at the latest tag, you can see that the version the bot is checking still has the problem:

https://github.com/bavathd/pezm/blob/V0.0.1/library.properties

```text
name=pezm
version=0.0.1
author=bavath
maintainer=bavath <dbavath@gmail.com>
sentence=Arduino library for PEZM015/16 energy meters for RS-485
paragraph=Arduino library for PEZM015/16 energy meters for RS-485
category=Device Control
architectures=*
depends=ModbusMaster (>=2.0.1)
includes=pezm.h
```

(note the file didn't have a `url` field at the tagged point in the repository's revision history)

❗ Remember to update the `version` field in the library's [`library.properties` file](https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format) as needed before making a release/tag.

Once you have done that, simply mention **@ArduinoBot** in a comment here to trigger it to run the automated checks again. After those are passing, your library will automatically be added to Library Manager.

If you have any questions or concerns, please let me know.

Regards, Per

**Comment by Tyler-Barnes** [comment]
I really don't understand @ArduinoBot. 

I changed the tag from 1.0, to 1.0.0 to create a new tag for you to look at in the file, and released it. But I find it ridiculous If I have to release this with something other than 1.0 or similar just because you use tags and don't refresh them if I re-release to get a bot to behave

**Comment by Tyler-Barnes** [comment]
THAT ISN"T MY LIBRARY! Can I please get a human to review this?

**Comment by Tyler-Barnes** [comment]
sorry, I didn't realize I was not on my own request. SORRY!!

**Review by per1234 — COMMENTED** [review]
For the sake of a tidy repository, I'm going to close this due to lack of activity.

@bavathd if you ever resolve the issues reported by the bot, please submit another pull request to add the library.

I'll continue to monitor this thread, so feel free to let me know if you have any questions or concerns.

**Pull request closed without merging**
