### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by treeaa**
Upgrade version

### CODE REVIEW

**Comment by per1234** [comment]
@treeaa you need to provide an explanation for this. Just yesterday you requested the library be removed. Now you are adding it back in.

You must start communicating with me. We have an automated system to assist with the submission process, but I'm a real human and I'm the one maintaining this system. When I ask you a question, you are required to answer.

**Comment by treeaa** [comment]
Dear sir,
&nbsp; &nbsp;&nbsp;I requested the library be removed yesterday,but I can still find it from Arduino IDE.I mistakenly thought it could not be deleted, so I added it again.
&nbsp; &nbsp; Now,I already know it can be deleted. Please help delete this library.Sorry for the inconvenience.
&nbsp; &nbsp; &nbsp;Thanks.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "arduino/library-registry"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月31日(星期二) 上午9:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [arduino/library-registry] Update repositories.txt (#438)





 
@treeaa you need to provide an explanation for this. Just yesterday you requested the library be removed. Now you are adding it back in.
 
You must start communicating with me. We have an automated system to assist with the submission process, but I'm a real human and I'm the one maintaining this system. When I ask you a question, you are required to answer.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by per1234** [comment]
Hi @treeaa. Thanks for your response. I explained the situation in my reply to your issue where you requested the library's removal:
https://github.com/arduino/library-registry/issues/428#issuecomment-907958959

>Hello @treeaa. The requested change is now in progress.
>
>Unlike submissions, this type of request is still handled manually. The Library Manager index's maintainer occasionally comes through to clear all the outstanding requests and closes those issues/PRs when that is done. If you are subscribed to the linked issue/PR, you'll get a notification at that time.

Compliant library submissions are accepted and added to Library Manager happen very quickly because the whole submissions and library indexing system is completely automated. However, the other processes like removing libraries are not automated so you must wait for humans to get around to doing them. That means you can expect a delay of weeks before your request is fulfilled. It happens in multiple steps. I already did the first step by merging your https://github.com/arduino/library-registry/pull/427, but there is another step that involves removal of the library's data from the Library Manager database. Until that is done, the library will continue to be listed in Library Manager.

If you subscribe to https://github.com/arduino/library-registry/pull/430 you'll get a notification from GitHub when that pull request is merged by the Library Index maintainer after having made the necessary changes to the database.

We will get to it. Please be patient.

**Comment by treeaa** [comment]
&nbsp; &nbsp; &nbsp;OK, I understand.&nbsp;
Thank you.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "arduino/library-registry"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月31日(星期二) 上午10:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [arduino/library-registry] Update repositories.txt (#438)





 
Hi @treeaa. Thanks for your response. I explained the situation in my reply to your issue where you requested the library's removal:
 #428 (comment)
  
Hello @treeaa. The requested change is now in progress.
 
Unlike submissions, this type of request is still handled manually. The Library Manager index's maintainer occasionally comes through to clear all the outstanding requests and closes those issues/PRs when that is done. If you are subscribed to the linked issue/PR, you'll get a notification at that time.
  
Compliant library submissions are accepted and added to Library Manager happen very quickly because the whole submissions and library indexing system is completely automated. However, the other processes like removing libraries are not automated so you must wait for humans to get around to doing them. That means you can expect a delay of weeks before your request is fulfilled. It happens in multiple steps. I already did the first step by merging your #427, but there is another step that involves removal of the library's data from the Library Manager database. Until that is done, the library will continue to be listed in Library Manager.
 
If you subscribe to #430 you'll get a notification from GitHub when that pull request is merged by the Library Index maintainer after having made the necessary changes to the database.
 
We will get to it. Please be patient.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Pull request closed without merging**
