### PR TITLE
Add PowerMonitor Library

### PR DESCRIPTION
**Pull request by zakarialaoui10**

### CODE REVIEW

**Comment by zakarialaoui10** [comment]
@ArduinoBot

**Comment by zakarialaoui10** [comment]
> ❌ **ERROR:** [Arduino Lint](https://github.com/arduino/arduino-lint) found errors with https://github.com/zakarialaoui10/PowerMonitor:
> 
> ```
> Linting library in PowerMonitor
> INFO: No header file found matching library name (PowerMonitor.h). Best practices are for primary header filename to    
>       match library name.                                                                                               
>       See: https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format            
>       (Rule LS008)                                                                                                      
> ERROR: Missing version field in library.properties                                                           
>        See: https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format
>        (Rule LP019)                                                                                          
> WARNING: No example sketches found. Please provide examples.                                      
>          See: https://arduino.github.io/arduino-cli/latest/library-specification/#library-examples
>          (Rule LD004)                                                                             
> WARNING: Potentially misspelled examples folder name found: PowerMonitor/Examples                 
>          See: https://arduino.github.io/arduino-cli/latest/library-specification/#library-examples
>          (Rule LD005)                                                                             
> WARNING: Incorrect examples folder name case: PowerMonitor/Examples                               
>          See: https://arduino.github.io/arduino-cli/latest/library-specification/#library-examples
>          (Rule LD006)                                                                             
> 
> Linter results for project: 1 ERRORS, 3 WARNINGS
> 
> -------------------
> ```

I have Fixed it

**Comment by per1234** [comment]
Hello @zakarialaoui10. I see you have fixed the error reported by the bot. However, Library Manager works exclusively from Git tags, so the bot won't be able to see the fix you made until you create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.

If you look at the repository contents at the latest tag, you can see that the version the bot is checking still has the problem:

https://github.com/zakarialaoui10/PowerMonitor/blob/v1.0.0/library.properties#L2

```text
versoion=0.9.0
```

❗ Remember to update the `version` field in the library's [`library.properties` file](https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format) as needed before making a release/tag.

Once you have done that, simply mention **@ArduinoBot** in a comment here to trigger it to run the automated checks again. After those are passing, your library will automatically be added to Library Manager.

If you have any questions or concerns, please let me know.

Regards, Per

**Comment by zakarialaoui10** [comment]
Thank you 🙏

**Comment by zakarialaoui10** [comment]
@ArduinoBot

**Comment by zakarialaoui10** [comment]
@per1234 Thank you for your help , now it has been merged successfully

**Pull request merged**
