### PR TITLE
add 3bc language libary

### PR DESCRIPTION
**Pull request by RodrigoDornelles**

### CODE REVIEW

**Comment by RodrigoDornelles** [comment]
@Arduinobot

**Comment by per1234** [comment]
Hello @RodrigoDornelles. The automated system here only operates on open pull requests submissions. Since your submission was already accepted and the pull request merged, the bot won't pay any more attention to this pull request. But this human is happy to provide assistance. Was there something you needed from the bot?

**Comment by RodrigoDornelles** [comment]
hi @per1234, my package is not showing up in the library manager yet, does it take a long time?

**Comment by per1234** [comment]
The logs show that it has been indexed:

http://downloads.arduino.cc/libraries/logs/github.com/rodrigodornelles/3bc-lang/

And it is available for me:

image

It does take some time to be available for everyone everywhere though. The indexing job runs hourly, so it ca be up to an hour from the time the submission is accepted to when it is indexed. After that, there may be some additional delay as the updated index propagates through the CDN cache. Even once it is available at your area via the CDN, the index is cached locally on your machine to avoid excessive load on Arduino's servers. So it is only after that local cache has expired that you will see the library in your Arduino IDE Library Manager

**Pull request merged**
