### PR TITLE
Update name of "MatesController"

### PR DESCRIPTION
**Pull request by per1234**
Resolves https://github.com/arduino/library-registry/issues/500

### CODE REVIEW

**Comment by BreadBoardMates** [comment]
Hi @per1234, 

Do we need to do anything else on our end so that this pull request to be accepted and merged?

I read in one of the older open pull request #347 about how this is processed. I also noticed that this pull request was from a month ago.

Can you give us a bit of an idea regarding how long usually these kind of requests are processed and will take effect?

**Comment by per1234** [comment]
>Do we need to do anything else on our end so that this pull request to be accepted and merged?

No. All that was needed from you was to update the name value in library.properties, make a tag, and submit a request for the name change. You have done all of those things perfectly so now all the rest is our responsibility.

The rename is not so simple as merging this pull request by itself. The database must be updated. Once that has been done, this pull request will be merged immediately.

>I read in one of the older open pull request #347 about how this is processed. 

I replied in your request with a quick overview of the situation:
https://github.com/arduino/library-registry/issues/500#issuecomment-922601271

>Can you give us a bit of an idea regarding how long usually these kind of requests are processed and will take effect?

Sorry, but I don't have any idea how long it will be.

**Comment by BreadBoardMates** [comment]
Thanks @per1234

**Review by rsora — APPROVED** [review]
Worker maintenance is done:
```
2021/09/23 17:42:14 Loaded 4226 libraries from DB
Removing Mates Controller
Success!
```

**Pull request merged**
