### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by adrian2793**

### CODE REVIEW

**Comment by adrian2793** [comment]
@ArduinoBot

**Comment by njh** [comment]
@adrian2793 looks like this repo has been deleted. Do you have any background about why?

https://github.com/arduino279/AISwitch

**Comment by adrian2793** [comment]
> @adrian2793 looks like this repo has been deleted. Do you have any background about why?
> 
> https://github.com/arduino279/AISwitch

Oh sorry, I deleted it. I forgot to mention. Can you delete it from the library Manager?

**Comment by per1234** [comment]
Hi @adrian2793.

> Can you delete it from the library Manager?

If you would like to request the removal of the library, you can follow the procedure documented here:

https://github.com/arduino/library-registry#removing-a-library-from-library-manager

**Pull request merged**
