### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by lukeclements**

### CODE REVIEW

**Comment by per1234** [comment]
Hello @lukeclements. Please provide a detailed description of your request and I will help you out with that.

**Comment by lukeclements** [comment]
> Hello @lukeclements. Please provide a detailed description of your request and I will help you out with that.

Hi, I originally submitted a pull request for Artemis-Arduino, but it didn't pass because it has the word arduino it so i changed it to artemis-teensy. I would like to delete the other library and push artemis-teensy to the the arduino library.

**Comment by lukeclements** [comment]
Is there anything else I need to do for this?

**Comment by per1234** [comment]
>I would like to delete the other library

OK, great. So this pull request is perfect. I just wanted to make sure I understood the intent to avoid accidentally removing your library.

I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests and will merge this pull request when it is done. You will get a notification from GitHub at that time.

>and push artemis-teensy to the the arduino library.

I see the submission was already successful: https://github.com/arduino/library-registry/pull/1145
and that the indexer has already processed the library:
http://downloads.arduino.cc/libraries/logs/github.com/hsfl/artemis-teensy/

It takes some time for the library release to propagate through the CDN and local cache, but you should see it in the Arduino IDE Library Manager soon. We give a conservative estimate of one day, but it is often much less than that.

>Is there anything else I need to do for this?

No. This is sufficient. Now it is only necessary to wait for the maintainer to process the request.

**Review by per1234 — APPROVED** [review]

**Comment by lukeclements** [comment]
Okay, great! Thank you so much for the help.

**Comment by umbynos** [comment]
Done [here](https://github.com/arduino/library-registry/pull/1148#issuecomment-1059220020)

**Pull request merged**
