### PR TITLE
PCA9554

### PR DESCRIPTION
**Pull request by Tinyu-Zhao**

### CODE REVIEW

**Comment by Tinyu-Zhao** [comment]
@ArduinoBot

**Comment by per1234** [comment]
Hi @Tinyu-Zhao. The reason for the somewhat odd messages from the bot is because you moved the `https://github.com/Tinyu-Zhao/TinyGPSPlus` URL to a different location in the list at the same time you added the new `https://github.com/Tinyu-Zhao/PCA9554` URL.

Since this is a modification to existing content of the list, rather than purely an addition, the bot treats it differently. You are welcome to submit pull requests to modify the content of the list, but it will be better to do that in a dedicated pull request, separate from the submission of new libraries. So let's make this pull request be only about the submission of https://github.com/Tinyu-Zhao/PCA9554. If you are in agreement with that, I am happy to update the PR accordingly.

**Comment by Tinyu-Zhao** [comment]
> Hi @Tinyu-Zhao. The reason for the somewhat odd messages from the bot is because you moved the `https://github.com/Tinyu-Zhao/TinyGPSPlus` URL to a different location in the list at the same time you added the new `https://github.com/Tinyu-Zhao/PCA9554` URL.
> 
> Since this is a modification to existing content of the list, rather than purely an addition, the bot treats it differently. You are welcome to submit pull requests to modify the content of the list, but it will be better to do that in a dedicated pull request, separate from the submission of new libraries. So let's make this pull request be only about the submission of https://github.com/Tinyu-Zhao/PCA9554. If you are in agreement with that, I am happy to update the PR accordingly.

Thank you

**Comment by Tinyu-Zhao** [comment]
@ArduinoBot

**Pull request merged**
