### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by pmassio**
Added https://github.com/pmassio/ArduinoLMI

### CODE REVIEW

**Comment by pmassio** [comment]
> Thanks for your interest in contributing to the Arduino Library Manager index @pmassio Please resolve the error(s) mentioned in the previous comment.
> 
> After resolving the issue, trigger this check again by doing one of the following:
> 
> * **Commit the required change to the branch you submitted this pull request from.**
> * **Comment here, mentioning `@ArduinoBot` in the comment.**
> 
> ❗ **NOTE**: It is not necessary to open a new pull request. ❗
> 
> More information: https://github.com/arduino/library-registry/blob/main/README.md#if-the-problem-is-with-the-pull-request

@ArduinoBot the library has the library.properties metadata...

**Comment by pmassio** [comment]
@ArduinoBot

**Review by per1234 — COMMENTED** [review]
Hello @pmassio. I see you have fixed the error reported by the bot. However, Library Manager works exclusively from Git tags, so the bot won't be able to see the fix you made until you create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.

If you look at the repository contents at the latest tag, you can see that the version the bot is checking still has the problem:

https://github.com/pmassio/ArduinoLMI/tree/v1.0.0

Once you have done that, simply mention **@ArduinoBot** in a comment here to trigger it to run the automated checks again. After those are passing, your library will automatically be added to Library Manager.

If you have any questions or concerns, please let me know.

Regards, Per

**Comment by pmassio** [comment]
@per1234 Thanks a lot, I'll try!
sorry I am new to this thing :-)

**Comment by pmassio** [comment]
@ArduinoBot

**Comment by pmassio** [comment]
@ArduinoBot

**Pull request merged**
