### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by beratcomputer**

### CODE REVIEW

**Comment by beratcomputer** [comment]
@ArduinoBot

**Comment by beratcomputer** [comment]
@ArduinoBot

**Comment by per1234** [comment]
Hello @beratcomputer. The automated system here only operates on open pull requests. Since your submission was already accepted and the pull request merged, the bot won't pay any more attention to this pull request.

But this human is happy to provide assistance. Was there something you needed from the bot?

**Comment by beratcomputer** [comment]
I updated repo and relase new version. does It update the new one automatically?

**Comment by beratcomputer** [comment]
@per1234 


I renamed my library. But it has this error. I do not left anywhere old name but i have this error.

2023/11/21 08:31:50 Checking out tag: 1.0.1
2023/11/21 08:31:50 Release Acrome-SMD:1.0.1 has wrong library name, should be Acrome SMD - Arduino Library

what did i do wrong?

**Pull request merged**
