### PR TITLE
Add Arduino AlPlc_Opta library

### PR DESCRIPTION
**Pull request by manchoz**

### CODE REVIEW

**Comment by manchoz** [comment]
@ArduinoBot for 1.1.0

**Comment by per1234** [comment]
Hi @manchoz. This repository's automated system only works on submissions, but I'm happy to provide assistance.

Were you hoping to trigger the system to index the library? If so, it is not necessary to take any action. The indexer system runs hourly and adds any compliant release. I can see from [the logs page](http://downloads.arduino.cc/libraries/logs/github.com/arduino-libraries/AlPlc_Opta/) that it already has done that. The index is cached so it could still be some time before you see the new release in the Arduino IDE Library Manager.

Or maybe you wanted to trigger the bot to run the [**Arduino Lint**](https://github.com/arduino/arduino-lint) checks? I see that a GitHub Actions workflow was set up in the library repository to run **Arduino Lint**:

https://github.com/arduino-libraries/AlPlc_Opta/blob/main/.github/workflows/check-arduino.yml

Unfortunately the maintainers of the library's repository allowed the workflow to become disabled:

https://github.com/arduino-libraries/AlPlc_Opta/actions/workflows/check-arduino.yml

> This scheduled workflow is disabled because there hasn't been activity in this repository for at least 60 days. Enable this workflow to resume scheduled runs.

If you have permissions in that repository (I don't unfortunately), please re-enable the workflow.

**Comment by manchoz** [comment]
Hi @per1234,
I need to unpublish the release 1.1.0 from the index and publish it again with new code. Is it possible? Is there any documentation or recommended workflow for this?

(This is the internal, binary-only library supporting Opta in the PLC IDE.)

Thanks!

**Comment by per1234** [comment]
You could do this by submitting a release removal request:

https://github.com/arduino/library-registry/blob/main/FAQ.md#how-can-i-remove-a-release-of-my-library-from-library-manager

However, I think it is [a bad idea](https://git-scm.com/docs/git-tag#_on_re_tagging) to make two releases with the same version number. This could result in a confusing situation where users have different variants of the library installed, but each identified with the same version number.

I don't have any experience with Arduino PLC IDE, but the Arduino IDE and Arduino CLI Library Managers won't offer updates for the 1.1.0 re-release to users who already installed the first release of that version. So re-releasing is not an effective way of distributing the changes made since the first 1.1.0 release to users.

A better approach would be to simply make a new release of the library. If you want to make sure the bad 1.1.0 release is not available to the users, you can still submit a release removal request.

**Pull request merged**
