### PR TITLE
Removing library

### PR DESCRIPTION
**Pull request by kaiaai**
Removing a library to avoid possible trademark issues

### CODE REVIEW

**Review by per1234 — COMMENTED** [review]
Hi @kaiaai. I'm quite confused about what you are trying to accomplish with the series of pull requests you have been submitting.

First you submitted a request to change the repository name: https://github.com/arduino/library-registry/pull/3372. That was very clear and straightforward and I initiated the process. But then even though the URL change procedure was still underway you deleted the fork you submitted that pull request from, which closed the essential pull request. All without any explanation.

You then proceeded to attempt to submit the already registered library four times in a row, without any explanation of why you were doing that:

- https://github.com/arduino/library-registry/pull/3374
- https://github.com/arduino/library-registry/pull/3375
- https://github.com/arduino/library-registry/pull/3376
- https://github.com/arduino/library-registry/pull/3377

And now you are requesting the library be removed.

We do allow library removals, but all those previous pull requests make me suspect that you have some goal other than a simple removal and you are trying to find some convoluted way to accomplish that via a series of cryptic pull requests instead of just making the effort to communicate what you are actually trying to accomplish.

All of this is causing a lot of work for me and also wasting your time.

You need to understand that, although there is an automated system for processing library submissions, everything else in this repository is managed by a human (me). I'm here to help, but I can only do that if you make the effort to actually communicate with me as a human.

So I will wait for you to add a comment here that provides a clear and detailed explanation of what you are actually hoping to accomplish in the end. Until you do that, we will not accept any requests from you so you would only be wasting your time to submit any other pull request to this repository.

**Comment by kaiaai** [comment]
Hi,
  sorry for the confusion and extra work. I need to
1) change the library repo URL from kaiaai/micro_ros_arduino_kaia to
kaiaai/micro_ros_arduino_kaiaai
2) change the library name (in library.properties) from micro_ros_kaia to
micro_ros_kaiaai
This is because the project name has changed for reasons of trademarking.

I submitted a rename request, but only later noticed that renames are not
allowed, but additions and deletions are. So I deleted the pull request and
tried adding the library under a new name and removing the library under
its old name. While moving the library to the new repo name, I had
unexpected build problems, so I canceled and redid one or more pull
requests until the library built without errors.

I hope this explains it.
Ilia

**Comment by per1234** [comment]
> noticed that renames are not allowed

One thing to note is that library maintainers often mix up two distinct operations:

- Changing the library URL by renaming the **repository** (e.g., `https://github.com/kaiaai/micro_ros_arduino_kaia` -> `https://github.com/kaiaai/micro_ros_arduino_kaiaai`)
- Changing the registered library name, as defined by the `name` field of the [`library.properties` metadata file](https://arduino.github.io/arduino-cli/latest/library-specification/#library-metadata) (e.g., `micro_ros_kaia` -> `micro_ros_kaiaai`)

Although it is common practice to use the same name for the repository and library name, the library maintainers often change both the URL and name at the same time. However, there is nothing in the Library Manager system that requires this, so they are two independent things.

The procedure for requesting a library URL change is documented here:

https://github.com/arduino/library-registry#changing-the-url-of-a-library-already-in-library-manager

The procedure for requesting a library name change is documented here:

https://github.com/arduino/library-registry/blob/main/FAQ.md#how-can-i-change-a-librarys-name

So you are wrong to think that renames are not allowed. It is important to understand that changing the name of a well established library can cause inconvenience or confusion to the users and even other library developers whose library has a dependency on your library. But we do indeed allow library maintainers to change the name of their library, and we accommodate such requests regularly.

So this is all very easy and straightforward to accomplish. You only need to read the documentation and follow the procedures there faithfully. I'm here to help, so if you have any questions, concerns, or problems while following the procedure, just ask and I'll provide assistance.

**Comment by per1234** [comment]
@kaiaai if you want to request a change to the registered library name, please submit a request by following the procedure I linked to in my comment above.

**Comment by per1234** [comment]
@kaiaai if you want to request a change to the registered library name, please submit a request by following the procedure I linked to in my comment above.

**Pull request closed without merging**
