### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by crmoratelli**

### CODE REVIEW

**Comment by crmoratelli** [comment]
@ArduinoBot

**Comment by crmoratelli** [comment]
@ArduinoBot

**Comment by per1234** [comment]
Hello @crmoratelli. The automated system here only operates on library submissions. Since your submission was already accepted and the pull request merged, the bot won't pay any more attention to this pull request.

But this human is happy to help. What was it you wanted from the bot?

**Comment by crmoratelli** [comment]
Hello.

I was trying to understand how a new tag version could be added. But perhaps new tags are automatically fetched from the repository. I think is everything right. 

Thank you.

**Comment by per1234** [comment]
>perhaps new tags are automatically fetched from the repository

You got it! After the initial addition of the library, the indexer job periodically checks each of the libraries in the index and picks up any new release/tag that meets the requirements listed here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#what-are-the-requirements-for-publishing-new-releases-of-libraries-already-in-the-library-manager-list

This means there is no need to take any additional action to add new releases of your library to Library Manager. They will be added automagically! It does take a little time for the indexer job to run, and then some additional time after that for the update to propagate through the CDN and the local cache. But it will get there.

You can monitor the indexing of the library releases by checking the library's dedicated indexer logs web page:
http://downloads.arduino.cc/libraries/logs/github.com/crmoratelli/SupmeaDO7016/
This will tell you when the tag has been indexed and also provide some information in the event there was a problem that caused a release to be rejected. I took a quick look at the logs and it seems all is well with your library. Thanks!

**Pull request merged**
