### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by Nonene2546**

### CODE REVIEW

**Review by Roshanen — APPROVED** [review]

**Review by Roshanen — APPROVED** [review]
heh?

**Comment by Nonene2546** [comment]
@ArduinoBot

**Comment by Nonene2546** [comment]
@ArduinoBot

**Review by Roshanen — APPROVED** [review]
Nonene

**Comment by Nonene2546** [comment]
@ArduinoBot

**Comment by Nonene2546** [comment]
@ArduinoBot

**Comment by per1234** [comment]
Hello @Nonene2546. Thanks for your interest in contributing to the Arduino Library Manager index.

I see that your repository is only a collection of sketches, not a library. Arduino Library Manager is exclusively for libraries, so we can not accept your project. If you would like to share your project with the community, you can consider writing a companion tutorial on the Arduino Project Hub:

https://create.arduino.cc/projecthub

If you are interested in writing an Arduino library, there is a nice tutorial here:

https://docs.arduino.cc/learn/contributions/arduino-creating-library-guide

and a technical reference here:

https://arduino.github.io/arduino-cli/latest/library-specification/

**Pull request closed without merging**
