### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by himanshudiwane**
hello, I am removing this library because i want to submit pull request for this library from official GitHub account. Also i am moving this library to different repository.

### CODE REVIEW

**Comment by per1234** [comment]
Hi @himanshudiwane. While anyone is welcome to submit any library, changes to existing registry entries may only be done with the authorization of a maintainer of the library. Although I have no reason to doubt it, unfortunately, I was unable to verify with certainty that this request was authorized.

I think the best way to provide verification is some sort of clear sign of the intent made in the GitLab repository or parent project from an account that has maintainer/owner role in that project. For example, you could create an issue there tracking the GitHub migration task or add a note to the project documentation about it.

I'm open to any other methods of verification you would like to propose.

Please let me know if you have any questions or concerns.

Per

**Comment by himanshudiwane** [comment]
Hello @per1234. Thank you for the clarification. The project repository of this library has been removed from the GitLab. Also I have submitted as issue for removing the library. 
Please let me know if there is anything else I need to do for removing the library.

**Review by per1234 — COMMENTED** [review]
Hello @himanshudiwane. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will merge this pull request when it is done. You will get a notification from GitHub at that time.

**Comment by zakarialaoui10** [comment]
this pull request should be closed because it is already merged

**Review by MatteoPologruto — APPROVED** [review]

**Pull request merged**
