### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by jmelabs**
Adding BuzzerMelody library to the list.

### CODE REVIEW

**Comment by jmelabs** [comment]
@ArduinoBot

**Comment by jmelabs** [comment]
@ArduinoBot

**Review by per1234 — COMMENTED** [review]
Hello @jmelabs. Thanks for your interest in contributing to the Arduino Library Manager index!

The reason for the check failure from the bot is a typo in the filename of your metadata file. I submitted a pull request to correct it:

https://github.com/jmelabs/BuzzerMelody/pull/1

You will need to do the following things:

1. Merge the PR correcting the filename.
1. Bump the value of the `version` field in the library's `library.properties` metadata file.
1. Create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.
1. Add a comment here in the pull request thread that mentions **@ArduinoBot**.

After that, the automated checks will run again. Once those are passing, your library will automatically be added to Library Manager.

If you have any questions or concerns, please let me know.

Regards, Per

**Comment by jmelabs** [comment]
@ArduinoBot

**Pull request merged**
