### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by byrmeng**
This is an example of reading a qr code with Deneyap Kart.

### CODE REVIEW

**Comment by pxsty0** [comment]
@ArduinoBot

**Review by byrmeng — COMMENTED** [review]
Editing has been done.

**Comment by byrmeng** [comment]
@ArduinoBot

**Comment by byrmeng** [comment]
@ArduinoBot

**Comment by byrmeng** [comment]
@ArduinoBot

**Comment by byrmeng** [comment]
@ArduinoBot warnings fixed.

**Pull request merged**
