### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by bitcode-tech**
V1.0.0 of BC7215 library, a library can decode or generate any format of IR remote control.

### CODE REVIEW

**Comment by bitcode-tech** [comment]
@ArduinoBot

**Comment by bitcode-tech** [comment]
@ArduinoBot

**Comment by per1234** [comment]
Hello @bitcode-tech. The automated system here only operates on open pull requests. Since your submission was already accepted and the pull request merged, the bot won't pay any more attention to this pull request.

But this human is happy to provide assistance. Was there something you needed from the bot?

**Comment by bitcode-tech** [comment]
Thanks a lot.

I did that as an attempt to fix an issue that the last release was not
accepted in the Arduino Library Manager, I've figured out the problem (We
tried to modify the library name alone with the feature upgrades), a new
release has been generated, so I wanted to trigger the bot to check if
everything is ok now.

The release has been created for couple of hours now, but I just checked
https://downloads.arduino.cc/libraries/logs/github.com/bitcode-tech/bc7215/
and haven't seen any update there. Is there anyway to let the bot check the
new release ?

Regards,

bitcode-tech

**Comment by per1234** [comment]
> I've figured out the problem (We
tried to modify the library name alone with the feature upgrades),

Nice work on identifying the cause of the problem!

> The release has been created for couple of hours now, but I just checked
https://downloads.arduino.cc/libraries/logs/github.com/bitcode-tech/bc7215/
and haven't seen any update there.

I can see it:

```text
2024/10/17 22:36:56 Checking out tag: V1.1.1
2024/10/17 22:36:56 Release IR-infrared Remote Control Decoder-Simulator:1.1.1 already loaded, skipping
2024/10/17 22:36:56 [Arduino Lint](https://arduino.github.io/arduino-lint/latest/) has suggestions for possible improvements:
Click to expand Arduino Lint report


Linting library in /home/ubuntu/workspace/gitclones/github.com/bitcode-tech/bc7215
INFO: No header file found matching library name (IR-infrared_Remote_Control_Decoder-Simulator.h). Best practices are   
      for primary header filename to match library name.                                                                
      See: https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format            
      (Rule LS008)                                                                                                      
WARNING: library.properties name value IR-infrared Remote Control Decoder-Simulator is longer than the recommended      
         length of 16 characters.                                                                                       
         See: https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format         
         (Rule LP010)                                                                                                   
WARNING: library.properties name IR-infrared Remote Control Decoder-Simulator contains spaces. Although supported, best 
         practices is to not use spaces.                                                                                
         See: https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format         
         (Rule LP015)                                                                                                   

Linter results for project: 0 ERRORS, 2 WARNINGS

-------------------

Linting sketch in /home/ubuntu/workspace/gitclones/github.com/bitcode-tech/bc7215/examples/comm

Linter results for project: no errors or warnings

-------------------

Linting sketch in /home/ubuntu/workspace/gitclones/github.com/bitcode-tech/bc7215/examples/ir_decoder

Linter results for project: no errors or warnings

-------------------

Linting sketch in /home/ubuntu/workspace/gitclones/github.com/bitcode-tech/bc7215/examples/ir_switch

Linter results for project: no errors or warnings

-------------------

Linting sketch in /home/ubuntu/workspace/gitclones/github.com/bitcode-tech/bc7215/examples/prog_remote

Linter results for project: no errors or warnings

-------------------

Linter results for projects: 0 ERRORS, 2 WARNINGS
```

> Is there anyway to let the bot check the
new release ?

We do not provide such a service in this repository. We only provide checks here for submissions.

The check results for each tag are provided in the logs page though.

However, the time to catch problems is before you make a release, not after. These checks are done by using an open source tool named "Arduino Lint" that we created:

https://arduino.github.io/arduino-lint/latest/

You can directly run Arduino Lint on your library on your computer if you like.

Better yet, you might consider setting up an automated check in your library repository for compliance with the Library Manager requirements. This could run on every commit and pull request to ensure such violations are caught immediately.

Arduino provides a [GitHub Actions](https://docs.github.com/en/actions) action that makes this very easy to do by adding a simple YAML file to the repository:

https://github.com/arduino/arduino-lint-action#readme

This action also uses Arduino Lint.

It is in use in all the official Arduino library repositories ([example](https://github.com/arduino-libraries/Servo/blob/master/.github/workflows/check-arduino.yml)).

**Comment by bitcode-tech** [comment]
Thanks a lot and it's very helpful. I'll apply these checks to the project.

**Pull request merged**
