### PR TITLE
Added Deneyap Telegram Library

### PR DESCRIPTION
**Pull request by pxsty0**

### CODE REVIEW

**Comment by pxsty0** [comment]
@ArduinoBot

**Comment by pxsty0** [comment]
@ArduinoBot

**Comment by per1234** [comment]
| @pxsty0 |
| :-: |
| :exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation: |
| :exclamation::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::exclamation: |
| :exclamation::warning:  **PLEASE READ THIS IMPORTANT INFORMATION**  :warning::exclamation: |
| :exclamation::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::exclamation: |
| :exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation: |
| @pxsty0  |

Hello @pxsty0. The automated system here only operates on open pull requests. Since your submission was already accepted and the pull request merged, the bot won't pay any more attention to this pull request.

But this human is happy to provide assistance. Was there something you needed from the bot?

You are making a lot of noise in the repository without accomplishing anything. This is a waste of time for both of us. Please, just take a minute to clearly communicate what you are trying to accomplish. I'm here to help, but I can only do that if you make the effort to communicate with me.

It is true that we have an automated system for handling submissions here, but that is the only thing that is automated. Everything else here is managed by a human, so you must communicate as you would with a human in order to accomplish anything.

**Comment by pxsty0** [comment]
I updated my library in my repo and created a new release. How will it be processed into Arduino?

**Comment by per1234** [comment]
After the initial addition of the library, the indexer job periodically checks each of the libraries in the index and picks up any new release/tag that meets the requirements listed here:

https://github.com/arduino/library-registry/blob/main/FAQ.md#what-are-the-requirements-for-publishing-new-releases-of-libraries-already-in-the-library-manager-list

This means there is no need to take any additional action to add new releases of your library to Library Manager. They will be added automagically!

The automated system here only operates on open pull requests. Since your submission was already accepted and the pull request merged, the bot completely ignores this pull request thread.

It does take a little time for the indexer job to run, and then some additional time after that for the update to propagate through the CDN and the local cache. But it will get there. We give a conservative estimate of availability within one day's time.

As already explained by the bot, you can monitor the indexing of the library releases by checking the library's dedicated indexer logs web page:

http://downloads.arduino.cc/libraries/logs/github.com/pxsty0/deneyap.telegram/

**Comment by pxsty0** [comment]
Thank you, I will not forget this information 🙃

**Comment by pxsty0** [comment]
Thank you, I will not forget this information 🙃

**Pull request merged**
