### PR TITLE
upd

### PR DESCRIPTION
**Pull request by addowneer01**

### CODE REVIEW

**Comment by addowneer01** [comment]
@ArduinoBot

**Comment by addowneer01** [comment]
@ArduinoBot

**Comment by addowneer01** [comment]
@ArduinoBot

**Comment by addowneer01** [comment]
@ArduinoBot

**Comment by addowneer01** [comment]
@ArduinoBot

**Review by per1234 — COMMENTED** [review]
Hello @addowneer01. I see you have fixed the error reported by the bot. However, Library Manager works exclusively from Git tags, so the bot won't be able to see the fix you made until you create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.

If you look at the repository contents at the latest tag, you can see that the version the bot is checking still has the problem:

https://github.com/addowneer01/CraftConnect-library-for-Arduino-ESP8266/tree/v0.1.2

(note the file is named `Library.properties` instead of the correct name `library.properties`)

❗ Remember to update the `version` field in the library's [`library.properties` file](https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format) as needed before making a release/tag.

Once you have done that, simply mention **@ArduinoBot** in a comment here to trigger it to run the automated checks again. After those are passing, your library will automatically be added to Library Manager.

If you have any questions or concerns, please let me know.

Regards, Per

**Comment by addowneer01** [comment]
@ArduinoBot

**Comment by addowneer01** [comment]
@ArduinoBot

**Pull request closed without merging**
