### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by teruyamato0731**

### CODE REVIEW

**Comment by teruyamato0731** [comment]
@ArduinoBot

**Comment by per1234** [comment]
Hello @teruyamato0731.  Thanks for your interest in contributing to the Arduino Library Manager index.

I see the bot reported a problem with your submission that will block its acceptance:

```text
ERROR: Path does not contain a valid Arduino library.                         
       See: https://arduino.github.io/arduino-cli/latest/library-specification
       (Rule LS001)  
```

In order to be considered valid, the library must contain a header file in the source folder, as documented here:

https://arduino.github.io/arduino-cli/latest/library-specification/#layout-of-folders-and-files

The header files of your library are currently located under [the `include/Chassis` subfolder](https://github.com/teruyamato0731/Chassis/tree/master/include/Chassis), which is not supported.

You must have at least one header file either in the `src` subfolder of the repository ([recursive layout](https://arduino.github.io/arduino-cli/latest/library-specification/#library-layout)) or in the root of the repository ([flat layout](https://arduino.github.io/arduino-cli/latest/library-specification/#library-layout)). If you prefer, you can place supplemental header files in subfolders.

After fixing the repository structure, create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.

Remember to update the `version` field in the library's [`library.properties` file](https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format) as needed before making a release/tag.

Once you have done that, simply mention **@ArduinoBot** in a comment here to trigger it to run the automated checks again. After those are passing, your library will automatically be added to Library Manager.

If you have any questions or problems while following the instructions to resolve the problem, please let me know and I'll help out.

If you decide you no longer wish to submit the library, you can close this pull request.

Regards, Per

**Comment by teruyamato0731** [comment]
@ArduinoBot

**Comment by teruyamato0731** [comment]
@ArduinoBot

**Pull request closed without merging**
