### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by reefwing**
Added Nexgen Codecamp Motor Shield Library

### CODE REVIEW

**Comment by reefwing** [comment]
@ArduinoBot - Git tag added

**Comment by per1234** [comment]
Hi @reefwing. I'm not super familiar with BitBucket's interface, but it looks like there are still no tags in the repository:
https://bitbucket.org/David_Such/nexgen_motorshield/downloads/?tab=tags
If you created the tag in your local clone, make sure you pushed it to the remote.

**Comment by reefwing** [comment]
@ArduinoBot - Correct Git tag added!

**Comment by reefwing** [comment]
@per1234 - thanks for having a look at this. I will try pushing to the remote. Sorry I'm a GitHub noob. One question. When setting the tag should I just use the number in the properties file (e.g. 1.1.0) or should I use v1.1.0 (e.g. `git tag -a v1.1.0 -m "Original Release - v1.1.0"` )?

**Comment by per1234** [comment]
>Sorry I'm a GitHub noob

No worries. Git is complex stuff!

>When setting the tag should I just use the number in the properties file (e.g. 1.1.0) or should I use v1.1.0 (e.g. git tag -a v1.1.0 -m "Original Release - v1.1.0" )?

You can use any style of tags you like. Even though tags are the unit of library releases used by Library Manager, they are only used as a marker to a specific point in the commit history. The name of the tag is completely disregarded. It could be "foobar" as far as the Library Manager indexer is concerned (though that is not a practice I would recommend 😄). All versioning of the library is done according to the `version` value in the library's `library.properties` metadata file.

**Comment by reefwing** [comment]
Thanks again @per1234 - I think I've managed to push the tag to the remote repository this time!

**Comment by reefwing** [comment]
@ArduinoBot - Git tag added and pushed to remote repository!

**Pull request merged**
