### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by E-Lagori**
@ArduinoBot ELagori repositories updated

### CODE REVIEW

**Comment by per1234** [comment]
Hello @E-Lagori. After the initial addition of the library, the indexer job periodically checks each of the libraries in the index and picks up any new release/tag that meets the requirements listed here:

https://github.com/arduino/library-registry/blob/main/FAQ.md#what-are-the-requirements-for-publishing-new-releases-of-libraries-already-in-the-library-manager-list

This means there is no need to take any additional action to add new releases of your library to Library Manager. They will be added automagically!

It does take a little time for the indexer job to run, and then some additional time after that for the update to propagate through the CDN and the local cache. But it will get there. We give a conservative estimate of availability within one day's time.

You can monitor the indexing of the library releases by checking the library's dedicated indexer logs web page:
https://github.com/arduino/library-registry/blob/main/FAQ.md#user-content-can-i-check-on-library-releases-being-added-to-library-manager

**Comment by E-Lagori** [comment]
Hi per1234,For some reason last 3 of my revisions have not been updated in the library manager of Arduino. I was trying to figure out why and any procedure to be followed for the same. Please let me know any reason why updates are not taki place. contact ---- On Tue, 30 Aug 2022 10:27:23 +0530  ***@***.***  wrote ----
Hello @E-Lagori. After the initial addition of the library, the indexer job periodically checks each of the libraries in the index and picks up any new release/tag that meets the requirements listed here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#what-are-the-requirements-for-publishing-new-releases-of-libraries-already-in-the-library-manager-list
This means there is no need to take any additional action to add new releases of your library to Library Manager. They will be added automagically!
It does take a little time for the indexer job to run, and then some additional time after that for the update to propagate through the CDN and the local cache. But it will get there. We give a conservative estimate of availability within one day's time.
You can monitor the indexing of the library releases by checking the library's dedicated indexer logs web page:
https://github.com/arduino/library-registry/blob/main/FAQ.md#user-content-can-i-check-on-library-releases-being-added-to-library-manager

**Comment by per1234** [comment]
I'll assume you mean the "**ELi_McM_4_00**" library. You can see the logs for the library here:

http://downloads.arduino.cc/libraries/logs/github.com/E-Lagori/ELi_McM_4_00/

from the logs, we can see that the following releases were accepted:

- 1.0.0
- 1.0.1
- 1.0.11

The 1.1.00 release was rejected because it is not compliant with the requirements for inclusion in the Arduino Library Manager index:

```text
2022/08/30 04:23:42 Checking out tag: v1.1.00
2022/08/30 04:23:46 [Arduino Lint](https://arduino.github.io/arduino-lint/latest/) found errors:
Click to expand Arduino Lint report


Linting library in /home/ubuntu/workspace/gitclones/github.com/E-Lagori/ELi_McM_4_00
ERROR: library.properties version value 1.1.00 is invalid.                                                   
       See: https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format
       (Rule LP020)                                                                                          
WARNING: library.properties version value 1.1.00 is not compliant with the semver specification.
         See: https://semver.org/                                                               
         (Rule LP021)                                                                           
WARNING: No example sketches found. Please provide examples.                                      
         See: https://arduino.github.io/arduino-cli/latest/library-specification/#library-examples
         (Rule LD004)                                                                             

Linter results for project: 1 ERRORS, 2 WARNINGS

-------------------




2022/08/30 04:23:46 Error syncing library: exit status 1
```

In order to ensure your releases are compliant, please make sure that you always use version numbers in the `version` field of the `library.properties` metadata file that are compliant with the "semver" specification:

https://semver.org/

Your continuous integration system caught the error:

https://github.com/E-Lagori/ELi_McM_4_00/runs/8041739361?check_suite_focus=true

You should carefully check the result of the workflow runs.

---

I see you made a 1.1.1 release only 45 minutes ago. The indexer job runs periodically, and even after indexing the releases take some time to propagate through the CDN and local cache before they become available from Library Manager in the Arduino IDE. We give a conservative estimate of one day's time before the release becomes available for everyone.

So as I can see the first three in Library Manager, and you have already fixed the problem with the version in your 1.1.1 release, I think all is well now:

image

**Comment by E-Lagori** [comment]
Thank you very much per1234 for your help. Will follow the semver requirements in the future. Thank youcontact ---- On Tue, 30 Aug 2022 10:46:26 +0530  ***@***.***  wrote ----
I'll assume you mean the "ELi_McM_4_00" library. You can see the logs for the library here:
http://downloads.arduino.cc/libraries/logs/github.com/E-Lagori/ELi_McM_4_00/
from the logs, we can see that the following releases were accepted:

1.0.0
1.0.1
1.0.11

The 1.1.00 release was rejected because it is not compliant with the requirements for inclusion in the Arduino Library Manager index:
2022/08/30 04:23:42 Checking out tag: v1.1.00
2022/08/30 04:23:46 [Arduino Lint](https://arduino.github.io/arduino-lint/latest/) found errors:
Click to expand Arduino Lint report


Linting library in /home/ubuntu/workspace/gitclones/github.com/E-Lagori/ELi_McM_4_00
ERROR: library.properties version value 1.1.00 is invalid.                                                   
       See: https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format
       (Rule LP020)                                                                                          
WARNING: library.properties version value 1.1.00 is not compliant with the semver specification.
         See: https://semver.org/                                                               
         (Rule LP021)                                                                           
WARNING: No example sketches found. Please provide examples.                                      
         See: https://arduino.github.io/arduino-cli/latest/library-specification/#library-examples
         (Rule LD004)                                                                             

Linter results for project: 1 ERRORS, 2 WARNINGS

-------------------




2022/08/30 04:23:46 Error syncing library: exit status 1

In order to ensure your releases are compliant, please make sure that you always use version numbers in the version field of the library.properties metadata file that are compliant with the "semver" specification:
https://semver.org/
Your continuous integration system caught the error:
https://github.com/E-Lagori/ELi_McM_4_00/runs/8041739361?check_suite_focus=true
You should carefully check the result of the workflow runs.

I see you made a 1.1.1 release only 45 minutes ago. The indexer job runs periodically, and even after indexing the releases take some time to propagate through the CDN and local cache before they become available from Library Manager in the Arduino IDE. We give a conservative estimate of one day's time before the release becomes available for everyone.
So as I can see the first three in Library Manager, and you have already fixed the problem with the version in your 1.1.1 release, I think all is well now:

**Pull request closed without merging**
