### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by iotkaran**

### CODE REVIEW

**Comment by iotkaran** [comment]
@ArduinoBot

**Comment by per1234** [comment]
Hello @iotkaran. Please tell me what you intend to do with this pull request so I can review it.

**Comment by iotkaran** [comment]
@ArduinoBot

**Comment by per1234** [comment]
@iotkaran. No matter how many times you tell the bot to run the checks, the result will be the same.

I'm a human. I'm here to help you, but I can only do it if you make the effort to communicate with me. So far, the only information I have about this pull request is that it "updates repositories.txt". That does not explain why you are trying to move a URL from one place in the file to another.

**Comment by iotkaran** [comment]
@ArduinoBot

**Comment by per1234** [comment]
OK. I'm going to close this pull request since it's pointless to continue in this way if you refuse to communicate with me. If you will answer my question then we can proceed

**Comment by iotkaran** [comment]
sorry iam try to update library to vertion 0.2

**Comment by per1234** [comment]
The Library Manager indexer checks all the libraries on the list for new tags/releases hourly and adds any new release that is compliant with the requirements listed here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#what-are-the-requirements-for-publishing-new-releases-of-libraries-already-in-the-library-manager-list

After that, it may take some time for the updated index to propagate through the CDN cache to make your new release available everywhere, but it will get there in good time. In fact, the 0.2 release is already available for me via Library Manager:
image

So you don't need to create an issue report every time you release a new version; once you push a tag/release that is compliant with all the Library Manager requirements everything happens automagically from there.

We now provide a dedicated web page for each library that shows its indexer logs. You can see the logs for your library here:
http://downloads.arduino.cc/libraries/logs/github.com/iotkaran/Arduino/
Note that it shows the 0.2.0 release was already indexed successfully.

**Pull request closed without merging**
