### PR TITLE
MX8650 library for Arduino and ESP

### PR DESCRIPTION
**Pull request by styropyr0**
This library facilitates communication with the MX8650 mouse controller, allowing for reading and writing data to its internal registers. It is essential to refer to the MX8650 datasheet before transferring data to the sensor registers.

Author: Saurav Sajeev

### CODE REVIEW

**Comment by styropyr0** [comment]
@ArduinoBot

**Comment by styropyr0** [comment]
@ArduinoBot

**Comment by styropyr0** [comment]
@ArduinoBot

**Comment by styropyr0** [comment]
@ArduinoBot

**Comment by per1234** [comment]
Hello @styropyr0. The automated system here only operates on open pull requests. Since your submission was already accepted and the pull request merged, the bot won't pay any more attention to this pull request.

But this human is happy to provide assistance. Was there something you needed from the bot?

**Comment by styropyr0** [comment]
Hello @per1234 ,
Thank you for the response. This was my first time publishing libraries to Arduino. I think I have made mistakes somewhere. It is showing me an error that for both the libraries I have published, the header files are not found. Think I didn't provide the header file's name as the commit message or something? You could help me by removing those two libraries which I have added and give me some suggestions if I have missed anything. I will just read and understand all the steps clearly, and publish it again.

**Comment by per1234** [comment]
>  It is showing me an error that for both the libraries I have published, the header files are not found.

Are you referring to this part of [the bot's comment](https://github.com/arduino/library-registry/pull/5233#issuecomment-2408424981)?:

```text
INFO: No header file found matching library name (MX8650_Mouse_sensor_library.h). Best practices are for primary header 
      filename to match library name.                                                                                   
      See: https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format            
      (Rule LS008) 
```

If so, this is not an error. It is only telling you that your library does not follow the best practices of the primary header filename matching the sanitized library name.

The library name is defined by the `name` property in the library's `library.properties` metadata file:

https://github.com/styropyr0/MX8650/blob/main/library.properties#L1

```text
name=MX8650 Mouse sensor library
```

Best practices would be for the library to have a primary header file matching the library name, with spaces replaced by underscores: `MX8650_Mouse_sensor_library.h`.

The reason this is considered a best practice is because in the case where multiple libraries contain a header file matching an `#include` directive in the sketch program, the Arduino sketch build system uses the match between the header filename and the library name as a factor in determining which of the libraries is the best choice:

https://arduino.github.io/arduino-cli/latest/sketch-build-process/#library-name-priority

So if you like, you can add a header file to the library named `MX8650_Mouse_sensor_library.h`. You can do this in a non-breaking manner by leaving the existing header file in the library and simply adding an `#include directive for the other header in the otherwise empty header file:

```cpp
#include "mx8650.h"
```

But please note that this is not an error. It is only a suggestion the bot is making in order to encourage library authors to follow best practices. If you decide that you don't want to follow the suggestion, there are no consequences. Your library has already been accepted for inclusion in the Arduino Library Manager and it will remain in Library Manager regardless.

> You could help me by removing those two libraries which I have added

It is not necessary. If you want to make improvements to the library, that is completely fine. Just make a new release of the library when you are ready and it will be automatically picked up by the Library Manager system:

https://github.com/arduino/library-registry/blob/main/FAQ.md#how-can-i-publish-a-new-release-once-my-library-is-in-the-list

**Pull request merged**
