### PR TITLE
1.0.2

### PR DESCRIPTION
**Pull request by RASPIAUDIO**
@ArduinoBot

### CODE REVIEW

**Comment by RASPIAUDIO** [comment]
@ArduinoBot

**Comment by RASPIAUDIO** [comment]
@ArduinoBot

**Review by per1234 — COMMENTED** [review]
| @RASPIAUDIO |
| :-: |
| :exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation: |
| :exclamation::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::exclamation: |
| :exclamation::warning:  **PLEASE READ THIS IMPORTANT INFORMATION**  :warning::exclamation: |
| :exclamation::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::exclamation: |
| :exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation: |
| @RASPIAUDIO |

DID YOU READ MY PREVIOUS MESSAGE?????

https://github.com/arduino/library-registry/pull/5496#pullrequestreview-2470858020

If not, then you need to get your act together and start paying attention!!!!!!!!!!!!!!!!!!

If you did, then why on earth did you submit yet another worthless pull request???????

If you continue to behave disrespectfully you will be permanently banned from the Arduino Library Manager and your library will be removed.

Start acting like a professional instead of an incompetent!!!!!!!!

**Comment by RASPIAUDIO** [comment]
> @RASPIAUDIO
> ❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗
> ❗⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️❗
> ❗⚠️ **PLEASE READ THIS IMPORTANT INFORMATION** ⚠️❗
> ❗⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️❗
> ❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗

@per1234

Thank you for your feedback. I’d like to clarify the sequence of events regarding our pull requests:

1. The first PR on November 29, 2024, was submitted to add our URL.
2. The second PR was accidental, as it unintentionally modified one character in the README.md file, which triggered a manual review. My apologies for this oversight.
3. The third PR was an attempt to correct the README.md to prevent rejection. If there’s a better approach I should have taken, I’d be grateful for your guidance.

I sincerely apologize for any inconvenience or frustration caused. As we are all learning and striving to contribute constructively, I assure you our intentions are genuine and in good faith.

That said, I believe maintaining professionalism in our communication is essential. Referring to someone as "unprofessional" or "incompetent" may not foster the constructive environment we all value in the open-source community.

Thank you for your time and consideration. I’ll make sure to be more thorough in the future.

**Comment by RASPIAUDIO** [comment]
@ArduinoBot

**Comment by per1234** [comment]
Hello @RASPIAUDIO. The automated system here only operates on open pull requests. Since the pull request is closed, the bot won't pay any more attention to it.

But this human is happy to provide assistance. Was there something you needed from the bot?

**Comment by RASPIAUDIO** [comment]
> Hello @RASPIAUDIO. The automated system here only operates on open pull requests. Since the pull request is closed, the bot won't pay any more attention to it.
> 
> But this human is happy to provide assistance. Was there something you needed from the bot?

Thanks for your help @per1234 , version 1.0.2 of our library was published in the Arduino library manager but I need to make a version 1.0.3, I have pushed my modification to my referenced repository but the library mananger doesn't seem to pubish the changes after 3 days.

Am I missing something?

thanks

https://github.com/RASPIAUDIO/Muse_library

**Comment by RASPIAUDIO** [comment]
> Hello @RASPIAUDIO. The automated system here only operates on open pull requests. Since the pull request is closed, the bot won't pay any more attention to it.
> 
> But this human is happy to provide assistance. Was there something you needed from the bot?

Thank you for your help, @per1234.

Our library was indeed accepted in [PR #5492](https://github.com/arduino/library-registry/pull/5492), but it seems that the latest version (1.0.3), committed to our [library repository](https://github.com/RASPIAUDIO/Muse_library), is not being updated automatically.

I was under the impression that the crawler would automatically fetch new versions. Could you kindly clarify what might be causing this issue?

**Comment by per1234** [comment]
Hi @RASPIAUDIO. You can check on the indexing of a library by the automated system by looking at [the dedicated logs web page for the library](https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager). The logs page for this library is here:

https://downloads.arduino.cc/libraries/logs/github.com/RASPIAUDIO/Muse_library/

```text
2024/12/08 14:40:13 Checking out tag: v1.0.2
2024/12/08 14:40:13 Release :1.0.2 has wrong library name, should be Muse_library
2024/12/08 14:40:13 Checking out tag: v1.0.3
2024/12/08 14:40:14 Release :1.0.3 has wrong library name, should be Muse_library
```

The indexer rejects any release that does not meet [the requirements](https://github.com/arduino/library-registry/blob/main/FAQ.md#what-are-the-requirements-for-publishing-new-releases-of-libraries-already-in-the-library-manager-list). The 1.0.2 and 1.0.3 releases of the library do not meet the requirements, so they were rejected by the indexer.

At the time you registered the library, the metadata was valid:

https://github.com/RASPIAUDIO/Muse_library/blob/v1.0.0/library.properties#L1

```text
name=Muse_library
```

However, a corruption was later introduced:

https://github.com/RASPIAUDIO/Muse_library/commit/e8c84d2f0ca0a9585101a17dc483570494da13fd

```diff
--- a/library.properties
+++ b/library.properties
@@ -1,4 +1,4 @@
-name=Muse_library
+sp32-sh1106-oledname=Muse_library
 version=1.0.1
 author=Raspiaudio
 maintainer=Raspiaudio <support@raspiaudio.com>
```

You changed the property name from `name` to `sp32-sh1106-oledname`. This effectively removed the definition of the library name from the metadata.

To solve this, you should do the following:

1. Change the name of the `sp32-sh1106-oledname` property in `library.properties` back to `name`.
1. Update the value of the `version` property to the number you want to use for the new release (e.g., 1.0.4)
1. Make a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.

After that, you only need to wait for the indexer job to run, and then for the updated index to propagate to you and the library users. After a successful indexing, it does take a bit of time before you will see a new release in your Library Manager due to caching, but it will get there eventually. We give a conservative estimate of availability within one day's time.

**Pull request closed without merging**
