### PR TITLE
mrm-fet-can library link added

### PR DESCRIPTION
**Pull request by PribaNosati**

### CODE REVIEW

**Comment by PribaNosati** [comment]
@ArduinoBot

**Comment by PribaNosati** [comment]
Error is "Error found with Your submission". Is there a less generic error message?

**Comment by per1234** [comment]
Hi @PribaNosati. The error is [this](https://github.com/arduino/library-registry/pull/75#issuecomment-859061111):

>Submission URL is already in the Library Manager index.

You already added this library to the Library Manager index last December: https://github.com/arduino/Arduino/issues/11050
So it's already on the list:
https://github.com/arduino/library-registry/blob/d0ba1688761e83ccedb8d2e68893b2e72be2667c/repositories.txt#L2691
Adding it again would cause a duplicate entry, which is not allowed.

You're welcome to add any other libraries which are not already in the Library Manager index.

**Comment by PribaNosati** [comment]
Sorry, I was stupid.

**Comment by per1234** [comment]
No worries. It's not stupid at all. This is a new system and we definitely need to make its communications more clear about the reasons for rejecting a submission when it doesn't meet the complex requirements.

I am monitoring the submissions closely and taking notes for any areas for improvement they reveal. I think we will be able to use this feedback to enhance the experience for the library maintainers.

**Comment by PribaNosati** [comment]
Thanks. Maybe the question was not stupid but I was. I should have checked.

**Comment by per1234** [comment]
I'm going to go ahead and close this as resolved. @PribaNosati feel free to open additional pull requests when you have other libraries to add. Thanks!

**Pull request closed without merging**
