### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by AndreiOp235**
Change library name/URL to remove warning

### CODE REVIEW

**Review by per1234 — COMMENTED** [review]
@AndreiOp235 we're happy to take care of this for you. But we can only do that if you leave the pull request open!!!!

So what do you want to do???

**Comment by AndreiOp235** [comment]
i just wanted to change the URL name(due to a warning in the lint action) but then the bot reported an error

Can you remove my URL from the repositories.txt (https://github.com/AndreiOp235/24s02ya__M24SR02-Y_Library) to make sure that everything is compliant ?

I will contribute back when the library is ok

**Review by per1234 — COMMENTED** [review]
Hi @AndreiOp235. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by AndreiOp235** [comment]
Thanks @per1234 for the patience of trying to understand me !

I managed to fix most of the lint warnings on my part. I`ll wait for the closing notification from Github

**Review by MatteoPologruto — APPROVED** [review]
Done:
```
2024/09/12 16:08:35 Loaded 7292 libraries from DB
Removing 24s02ya__M24SR02-Y_Library
Success!
```

**Pull request merged**
