### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by not-phoenix-w**

### CODE REVIEW

**Comment by per1234** [comment]
@ArduinoBot please check it again

**Review by per1234 — COMMENTED** [review]
Hello @not-phoenix-w. Thanks for your interest in contributing to the Arduino Library Manager index.

I see the bot reported a problem with your submission that will block its acceptance:

> ❌ ERROR: The repository has no tags. You need to create a [release](https://docs.github.com/en/github/administering-a-repository/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) that matches the version value in the library's library.properties file.

Please fix the problem so we can proceed with your submission.

You will need to do the following things:

1. Create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.
1. Add a comment here in the pull request thread that mentions **@ArduinoBot**.

After that, the automated checks will run again. Once those are passing, your library will automatically be added to Library Manager.

If you have any questions or concerns, please let me know.

Regards, Per

**Comment by not-phoenix-w** [comment]
@per1234 Good evening! I have already fixed all the problems mentioned earlier. Please check it again

**Comment by per1234** [comment]
@ArduinoBot please check it again.

**Review by per1234 — COMMENTED** [review]
Hello again @not-phoenix-w.

There is good progress, but I see the bot still reported a problem with your submission that will block its acceptance:

```text
Linting sketch in MovingPlatform/examples/PID example

[...]

ERROR: Prohibited character(s) in file name(s): PID examples.ino                                       
       See: https://arduino.github.io/arduino-cli/latest/sketch-specification/#sketch-folders-and-files
       (Rule SS002)   
```

Please fix the problem so we can proceed with your submission.

You will need to do the following things:

1. Remove the space from the name of the folder at `MovingPlatform/examples/PID example`.
1. Rename the `.ino` file in the renamed folder to _**EXACTLY**_ match the folder name. Note that there is a mismatch between the current filename `PID examples.ino` and the folder name `PID example` ("example**s**" vs. "example")
1. Bump the value of the `version` field in the library's `library.properties` metadata file.
1. Create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.
1. Add a comment here in the pull request thread that mentions **@ArduinoBot**.

After that, the automated checks will run again. Once those are passing, your library will automatically be added to Library Manager.

If you have any questions or concerns, please let me know.

Regards, Per

**Comment by per1234** [comment]
@ArduinoBot please check it again.

**Review by per1234 — COMMENTED** [review]
Hello @not-phoenix-w. I see you have fixed the error reported by the bot. However, Library Manager works exclusively from Git tags, so the bot won't be able to see the fix you made until you create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.

If you look at the repository contents at the latest tag, you can see that the version the bot is checking still has the problem:

https://github.com/siroshy/MovingPlatform/tree/0.1/examples/PID%20example

❗ Remember to update the `version` field in the library's [`library.properties` file](https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format) as needed before making a release/tag.

Once you have done that, simply mention **@ArduinoBot** in a comment here to trigger it to run the automated checks again. After those are passing, your library will automatically be added to Library Manager.

If you have any questions or concerns, please let me know.

Regards, Per

**Review by per1234 — COMMENTED** [review]
For the sake of a tidy repository, I'm going to close this due to lack of activity.

@not-phoenix-w if you ever resolve the issues reported by the bot, please submit another pull request to add the library.

I'll continue to monitor this thread, so feel free to let me know if you have any questions or concerns.

**Pull request closed without merging**
