### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by wxzed**

### CODE REVIEW

**Comment by per1234** [comment]
Hi @wxzed. I see this pull request removes https://github.com/DFRobot/DFRobot_GDL from the list. As explained by the bot, the automated system only handles submissions. But I'm here to help out with all other request types. Please tell me exactly what you are requesting to be done and I will get that process started right away.

**Comment by wxzed** [comment]
Please remove the DFRobot GDL library

**Comment by per1234** [comment]
Although anyone is welcome to submit any library for inclusion in the Arduino Library Manager index, removals may only be done with the authorization of a maintainer of the library. Unfortunately, I was unable to verify that this request to remove https://github.com/DFRobot/DFRobot_GDL was authorized. 

Please provide proof that this request is authorized. Thanks!

**Comment by wxzed** [comment]
What kind of authorization certificate needs to be provided. This library was submitted by me. Is this ok?https://github.com/arduino/library-registry/pull/481

**Comment by per1234** [comment]
> This library was submitted by me. Is this ok?

No. Even though anyone is permitted to submit a library, that does not give them authorization to later remove it.

However, I can see from the commit history of https://github.com/DFRobot/DFRobot_GDL that you have write permissions in the repository, which is sufficient.

**Review by per1234 — APPROVED** [review]

**Comment by per1234** [comment]
The requested change is now in progress.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests and closes those issues/PRs when that is done. If you are subscribed to the linked PR, you'll get a notification at that time: https://github.com/arduino/library-registry/pull/491

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Pull request merged**
