### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by Tyler-Barnes**
My desire is to have my library fork added to the Arduino Library Manager browser. 

https://github.com/Tyler-Barnes/promplus

### CODE REVIEW

**Comment by Tyler-Barnes** [comment]
I have edited my repository based on the reported errors @ArduinoBot

**Comment by Tyler-Barnes** [comment]
I don't understand @ArduinoBot. The error reported has been corrected and a URL is indeed in my library.properties file.

**Comment by Tyler-Barnes** [comment]
Maybe it's the git tags not matching. @ArduinoBot ?

**Review by per1234 — COMMENTED** [review]
Hello @Tyler-Barnes. I see you have fixed the error reported by the bot. However, Library Manager works exclusively from Git tags, so the bot won't be able to see the fix you made until you create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.

If you look at the repository contents at the latest tag, you can see that the version the bot is checking still has the problem:

https://github.com/Tyler-Barnes/promplus/blob/1.0/library.properties#L8

```text
url=
```

❗ Remember to update the `version` field in the library's [`library.properties` file](https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format) as needed before making a release/tag.

Once you have done that, simply mention **@ArduinoBot** in a comment here to trigger it to run the automated checks again. After those are passing, your library will automatically be added to Library Manager.

If you have any questions or concerns, please let me know.

Regards, Per

**Comment by Tyler-Barnes** [comment]
Thanks for the more detailed information. 

I will try with 1.0.0, but I will find it frustrating if I cannot release this with some variant of 'version 1.0' because of a bot's inability to look at an updated re-release. 

@ArduinoBot

**Comment by per1234** [comment]
> I will find it frustrating if I cannot release this with some variant of 'version 1.0' because of a bot's inability to look at an updated re-release.

@Tyler-Barnes "re-releasing" is a huge no-no in software development. A release tag is expected to be an immutable marker at a specific point in the revision history of a project.

https://git-scm.com/docs/git-tag#_on_re_tagging

Imagine how frustrated you would be if you were the user of some software and reported a problem you were having with version 1.0 of the software, only to have the response "Which version 1.0 are you using? We made two different releases with that version number, one of which had a bug."

**Comment by Tyler-Barnes** [comment]
I understand that, but this is not a new version. This is v1.0 and remains v1.0 trying to release it within the constraints of fixing an error in uploading to the platform in which the 'releasing' happens.

**Comment by Tyler-Barnes** [comment]
Your information helped greatly in fixing said frustrations. So I thank you for that. Continue with the prompts, accurate, and valuable work.

**Pull request merged**
