### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by Jayedt5**

### CODE REVIEW

**Comment by Jayedt5** [comment]
@ArduinoBot

**Comment by Jayedt5** [comment]
@ArduinoBot

**Comment by Jayedt5** [comment]
@ArduinoBot

**Comment by Jayedt5** [comment]
@ArduinoBot

**Comment by Jayedt5** [comment]
@ArduinoBot

**Comment by Jayedt5** [comment]
@ArduinoBot

**Review by per1234 — COMMENTED** [review]
I see the repository contains a sketch, not a library. @Jayedt5 the Arduino Library Manager is only for distribution of Arduino libraries so we cannot accept this submission.

You can learn about writing Arduino libraries from this tutorial:

https://docs.arduino.cc/learn/contributions/arduino-creating-library-guide

**Comment by per1234** [comment]
Hello @Jayedt5. In order to be accepted to the

**Comment by Jayedt5** [comment]
@per1234 not sure if you can still see this

**Pull request closed without merging**
