### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by SooDragon**

### CODE REVIEW

**Comment by SooDragon** [comment]
@ArduinoBot

**Comment by per1234** [comment]
Hello @SooDragon. The automated system here only operates on open pull requests. Since your submission was already accepted and the pull request merged, the bot won't pay any more attention to this pull request.

But this human is happy to provide assistance. Was there something you needed from the bot?

**Comment by SooDragon** [comment]
@per1234 Hi! Thank you for reply!
I updated my library, and wanted to apply version update
according to Guideline  -> https://github.com/arduino/library-registry
------
Create a [release](https://docs.github.com/repositories/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag). The Library Manager index always uses tagged versions of the libraries, so even if the development version of the library is compliant, it can't be accepted until the latest release or tag is compliant. Alternatively, you can redo the existing release/tag if you prefer.
Comment on your pull request here in the arduino/library-registry repository, mentioning @ArduinoBot in the comment. Doing this will cause the automated check to run again.
------

so I tried mentioning....

I don't know How it happened but it worked

Did it worked because I mentioned arduinobot? or is it caused by other reasons?
Thank you!

**Comment by per1234** [comment]
> Did it worked because I mentioned arduinobot?

No. Your comment didn't accomplish anything at all. The automated system completely ignores merged pull requests. It would be idiotic for us to design a system that forces the library maintainers to comment on a pull request every time they make a new release. The system we designed uses the correct approach of simply checking every library repository periodically, then indexing any new releases that have been made.

Please don't mention arduinobot here when you make new releases of the library. It doesn't accomplish anything and it is harmful because I have to monitor every comment in this repository and so if every one of the thousands of library maintainers did that then I would not be able to accomplish any of the important productive work the upon which the Arduino community depends. Just be patient and wait for the system to pick up your new release automagically.

It does take a little time for the indexer job to run, and then some additional time after that for the update to propagate through the CDN and the local cache. But it will get there. We give a conservative estimate of availability within one day's time.

You can monitor the indexing of the library releases by checking the library's dedicated indexer logs web page:
https://github.com/arduino/library-registry/blob/main/FAQ.md#user-content-can-i-check-on-library-releases-being-added-to-library-manager

**Pull request merged**
