### PR TITLE
Added vovagorodok arduino libraries

### PR DESCRIPTION
**Pull request by vovagorodok**
Added:
- `ArduinoBleChess` - play chess over bluetooth with couple apps (WhitePawn/chess.com/lichess) by universal chess protocol
- `ArduinoBleOTA` - upload/update your project over bluetooth (currently support esp32, atmel sam and more)
- `ArduinoPin` - analog/digital pin classes. Require c++14
- `ArduinoStreamLogger` - add stream based logging system to your project. Require c++17
- `ArrayUtils` - fast array based map and more. Require c++14
- `PicChess` - basic chess engine
- `Servo` - servo library that support position changing speed in order to decrees pic current

### CODE REVIEW

**Comment by vovagorodok** [comment]
> ArrayUtils

@per1234  why ArduinoIDE does't support adding of libraries with same name but other authors like:
```
ArrayUtils
   by vovagorodok
ArrayUtils
   by Sandeep Prasad
```
?

It will be supported in ArduinoIDE 2?

**Comment by per1234** [comment]
Hello @vovagorodok. Every library must have a unique name. Please do this:

1. Change the value of the `name` field in the library's `library.properties` file.
1. Bump the value of the `version` field in the library's `library.properties` metadata file.
1. Create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.
1. Add a comment here in the pull request thread that mentions **@ArduinoBot**.

After that, the automated checks will run again. Once those are passing, your libraries will automatically be added to Library Manager.

If you have any questions or concerns, please let me know.

Regards, Per

**Comment by vovagorodok** [comment]
As I correctly understand, PlatformIO use `library.json` and I can leave same naming (ArduinoBleChess, ArrayUtils..), but ArduinoIDE use `library.properties` and here I should rename somehow (VovagorodokArduinoBleChess, VovagorodokArrayUtils..?) ?\
Have You any suggestion  what naming convention I should use in order to achieve some consistency?\
It's ok that some of my libraries require c++ greater than c++11 (https://github.com/vovagorodok/ArrayUtils?tab=readme-ov-file#configuration)?

**Comment by per1234** [comment]
> As I correctly understand, PlatformIO use `library.json` and I can leave same naming (ArduinoBleChess, ArrayUtils..), but ArduinoIDE use `library.properties`

That is correct. The Arduino Library Manager and official Arduino development tools do not use `library.json` in any way so the contents of `library.json` are irrelevant for the purposes of this discussion.

> Have You any suggestion what naming convention I should use in order to achieve some consistency?

I think the use of the `Vovagorodok` prefix is a good one. This creates a "namespace" of sorts for your libraries.

> It's ok that some of my libraries require c++ greater than c++11

This doesn't impact the eligibility for inclusion in Arduino Library Manager. The requirement for the user to modifying the platform in order to use the library does make it less accessible (some Arduino users will find it very difficult to accomplish this) and inconvenient to use the library, but we don't base Library Manager acceptance on such subjective usability considerations.

**Comment by vovagorodok** [comment]
@ArduinoBot

**Pull request merged**
