### PR TITLE
Remove library

### PR DESCRIPTION
**Pull request by oguzkaganyaglioglu**
I deleted and recreated the Github repository so I can't access the library right now so I want to remove and re-add it

### CODE REVIEW

**Comment by per1234** [comment]
Hi @oguzkaganyaglioglu. It's not clear to me what you are trying to accomplish. Please provide a detailed description.

You are, of course, always permitted to request the removal of your library from Library Manager, but that should only be done if your intention is to permanently remove the library. If you are planning on just adding it back right away, this indicates that your goal is not really to remove it after all.

>I can't access the library right now

Why not? I can access it, no problem, so surely you can as well:
https://github.com/oguzkaganyaglioglu/PLCustomDevicesLibrary

**Comment by oguzkaganyaglioglu** [comment]
I realized that I added secret information to the github repo so I deleted the repository then recreated this repo with the same name and uploaded the new library but now
http://downloads.arduino.cc/libraries/logs/github.com/oguzkaganyaglioglu/PLCustomDevicesLibrary/
when i go to the link

> 2021/06/12 13:58:52 Scraping https://github.com/oguzkaganyaglioglu/PLCustomDevicesLibrary.git
> 2021/06/12 13:58:52 Error fetching repository: authentication required
> 2021/06/12 13:58:52 Removing clone and trying again
> 2021/06/12 13:58:52 Error fetching repository: authentication required
> 2021/06/12 13:58:52 Leaving...

I found these errors. So I am thinking if I delete and re-add library it will fix that error

**Comment by per1234** [comment]
OK, I understand now. Once the Library Manager indexer adds a release to the index, it is stored there unless its removal is requested. You might request the removal of a release that has a problem, such as the one you described.

So what we need to do is remove the release from the Library Manager index, while leaving the library. As long as you have also removed the tag with the problematic content from the repository, as is sounds like you have done, it will be permanently removed from the Library Manager index. Any existing tags will be picked up by the indexer automatically, as usual.

There is no automated system for removing libraries or releases and I don't have access to the data that needs to be removed in order to remove releases (or libraries for that matter). So we'll need to wait until someone with the necessary access is available to help out. Since you don't actually want to remove your library, I will not merge this pull request, but we can keep it open as a way to track your request to remove the current `0.1.0` release from the index.

Please let me know if you have any questions or concerns.

>I found these errors.

I think that was a temporary thing caused by the indexer job running during or near to the time you had deleted the repository. I see that in the latest run of the indexer it was able to access your library without any problems:
http://downloads.arduino.cc/libraries/logs/github.com/oguzkaganyaglioglu/PLCustomDevicesLibrary/
```
2021/06/12 14:58:44 Scraping https://github.com/oguzkaganyaglioglu/PLCustomDevicesLibrary.git
2021/06/12 14:58:44 Checking out tag: v0.1.0
2021/06/12 14:58:44 Release PLCustomDevices:0.1.0 already loaded, skipping
```

**Comment by oguzkaganyaglioglu** [comment]
It's been 9 days and still, version `0.1.0` is not removed from the index. When will it be removed?

**Comment by per1234** [comment]
Hi @oguzkaganyaglioglu Although the submission and indexing processes are automated, the removals and modifications are still manual processes. So it will be done on the next sweep by the index maintainer to clear all the outstanding requests.

**Comment by cmaglie** [comment]
The release `0.1.0` has been regenerated.

**Pull request closed without merging**
