### PR TITLE
Add Sensair S8 UART library

### PR DESCRIPTION
**Pull request by Belphemur**
To easily interface with a Sensair S8 sensor

Author: @jcomas 
Repo: https://github.com/jcomas/S8_UART

### CODE REVIEW

**Comment by per1234** [comment]
Thanks @Belphemur.
I'll add a note to myself here that there is an effort to resolve the issue blocking the merge of the PR: https://github.com/jcomas/S8_UART/issues/2
So we can leave this open until it is resolved.

**Comment by Belphemur** [comment]
@per1234 Thanks !
The developer has been unresponsive for close to a week now. I'll see if I can contact him by email.

**Comment by jcomas** [comment]
Next days I'll test the new changes before I release the final version 1.0.0.

**Comment by Belphemur** [comment]
@jcomas Great to hear !
Thank you again for your work, I've been using it in my fork of AirGradient (https://github.com/Belphemur/AirGradient) , and it's working flawlessly for now.

**Comment by jcomas** [comment]
Added v1.0.0 tag, first release.
Is it ok "v1.0.0" tag for "version=1.0.0" in library.properties?

**Comment by per1234** [comment]
Hello @jcomas

>Is it ok "v1.0.0" tag for "version=1.0.0" in library.properties?

Yes. The Library Manager system doesn't care at all what the name of the tag is, so you are welcome to use any tag name format you like.

Although Git tags are the unit of release for Arduino Library Manager, all versioning is done according to the value of the `version` field in the `library.properties` metadata file at that tag. So the important thing is that the `version` field value be unique and compliant with the requirements specified [here](https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format).

**Pull request merged**
