### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by wzwyz**

### CODE REVIEW

**Comment by wzwyz** [comment]
@ArduinoBot

**Comment by wzwyz** [comment]
@ArduinoBot

**Review by per1234 — COMMENTED** [review]
Hello @wzwyz. I see you have fixed the error reported by the bot. However, Library Manager works exclusively from Git tags, so the bot won't be able to see the fix you made until you create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.

If you look at the repository contents at the latest tag, you can see that the version the bot is checking still has the problem:

https://github.com/wzwyz/Calculate/tree/v0.0.1

---

❗ Remember to update the `version` field in the library's [`library.properties` file](https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format) as needed before making a release/tag.

---

Once you have done that, simply mention **@ArduinoBot** in a comment here to trigger it to run the automated checks again. After those are passing, your library will automatically be added to Library Manager.

If you have any questions or concerns, please let me know.

Regards, Per

**Review by per1234 — COMMENTED** [review]
For the sake of a tidy repository, I'm going to close this due to lack of activity.

@wzwyz if you ever resolve the issues reported by the bot, please submit another pull request to add the library.

I'll continue to monitor this thread, so feel free to let me know if you have any questions or concerns.

**Pull request closed without merging**
