### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by akkoyun**

### CODE REVIEW

**Comment by akkoyun** [comment]
@ArduinoBot I want to remove the library from list.

**Comment by per1234** [comment]
Hello @akkoyun. I see your pull request moves the `https://github.com/akkoyun/I2C_Functions` URL from line 4661 to 4678:

https://github.com/arduino/library-registry/pull/1084/files

Was there a reason you wanted to move it?

**Comment by per1234** [comment]
Ah, I see now you commented while I was replying:

>I want to remove the library from list.

That is fine. Please update the PR to remove the URL from the list rather than moving it from one line to another.

Once that is done, I will proceed with the removal as requested.

**Comment by akkoyun** [comment]
> Hello @akkoyun. I see your pull request moves the `https://github.com/akkoyun/I2C_Functions` URL from line 4661 to 4678:
> 
> https://github.com/arduino/library-registry/pull/1084/files
> 
> Was there a reason you wanted to move it?

My library is shown wrong on Arduino so I want to delete the old submission and add it again.

**Comment by per1234** [comment]
>My library is shown wrong on Arduino

What do you mean by "wrong" @akkoyun?

Of course, you are always welcome to remove libraries from the list if you want, but I may be able to suggest a more efficient way of fixing that issue than going through a removal and resubmission process.

**Comment by akkoyun** [comment]
> 

name and version showed wrong on library manager.

**Comment by akkoyun** [comment]
> > My library is shown wrong on Arduino
> 
> What do you mean by "wrong" @akkoyun?
> 
> Of course, you are always welcome to remove libraries from the list if you want, but I may be able to suggest a more efficient way of fixing that issue than going through a removal and resubmission process.

what is your advice, my friend?

**Comment by per1234** [comment]
Libraries in the Library Manager list are locked to the name they had at the time they were added to the list. At the time the library [was added](https://github.com/arduino/library-registry/pull/1038), the `name` value in the `library.properties` metadata file was set to "Generic I2C Functions":

https://github.com/akkoyun/I2C_Functions/blob/01.00.00/library.properties#L1

```text
name=Generic I2C Functions
```
So it was [registered](https://github.com/arduino/library-registry/commit/428950a8b6d9ff91fb1e27f8723a1638295c5e65) under that name:

```text
https://github.com/akkoyun/I2C_Functions.git|Contributed|Generic I2C Functions
```

I see you have since [changed the name value](https://github.com/akkoyun/I2C_Functions/commit/9e70637df33f7d3413fffe3297079e5ff26dcab5) to "I2C_Functions".

The Library Manager indexer rejects any release that uses a `name` value which does not match the registration data. The dedicated Library Manager indexer logs webpage for your library shows that the tags since the name change have been rejected:

http://downloads.arduino.cc/libraries/logs/github.com/akkoyun/I2C_Functions/

```text
2022/02/20 14:21:55 Checking out tag: 01.01.01
2022/02/20 14:21:55 Release I2C_Functions:1.1.1 has wrong library name, should be Generic I2C Functions
2022/02/20 14:21:55 Checking out tag: 01.02.00
2022/02/20 14:21:55 Release I2C_Functions:1.2.0 has wrong library name, should be Generic I2C Functions
```

So this is the reason you are not seeing the 1.1.1 and 1.2.0 releases listed in Arduino Library Manager, and why the library is still listed under "Generic I2C Functions".

---

So I think the easiest thing is for us to just [update the registration name](https://github.com/arduino/library-registry/blob/main/FAQ.md#how-can-i-change-a-librarys-name) data for you. That is more straightforward than doing a removal and then resubmission.

I have initiated the name change on your behalf: https://github.com/arduino/library-registry/pull/1087

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests and merges the PRs when that is done. If you are subscribed to the linked PR, you'll get a notification at that time.

After that, you can monitor the indexing of the library via [its dedicated logs web page](http://downloads.arduino.cc/libraries/logs/github.com/akkoyun/I2C_Functions/).
The 1.1.1 and 1.2.0 releases will be automatically added to the index once the name change has been made.

Please let me know if you have any questions or concerns.
Regards, Per

**Pull request closed without merging**
