### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by and900**

### CODE REVIEW

**Review by per1234 — COMMENTED** [review]
Hello @and900. Thanks for your interest in contributing to the Arduino Library Manager index.

I see the bot reported a problem with your submission that will block its acceptance:

```text
ERROR: library.properties version value 1.0.0 All My Things On Line (AMYTOL) September 8th 2023 is invalid.  
       See: https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format
       (Rule LP020)     
```

Please fix the problem so we can proceed with your submission.

You will need to do the following things:

1. Change the value of the `version` field in the library's `library.properties` metadata file to be a valid [semver-compliant](https://semver.org/) version number:
   https://github.com/and900/AMYTOL_Robot/blob/main/library.properties#L2
1. Create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.
1. Add a comment here in the pull request thread that mentions **@ArduinoBot**.

After that, the automated checks will run again. Once those are passing, your library will automatically be added to Library Manager.

If you have any questions or concerns, please let me know.

Regards, Per

**Comment by and900** [comment]
@ArduinoBot

Have updated

**Comment by MAGGI0007** [comment]
Have reviewed and tested the code 
All working

**Review by MAGGI0007 — APPROVED** [review]
Have tested the code and it works on the Rover V3

**Review by per1234 — COMMENTED** [review]
Hello @and900. I see you have fixed the error reported by the bot. However, Library Manager works exclusively from Git tags, so the bot won't be able to see the fix you made until you create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.

If you look at the repository contents at the latest tag, you can see that the version the bot is checking still has the problem:

https://github.com/and900/AMYTOL_Robot/blob/Update/library.properties#L2

```text
version=1.0.0 All My Things On Line (AMYTOL) September 8th 2023
```

❗ Remember to update the `version` field in the library's [`library.properties` file](https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format) as needed before making a release/tag.

Once you have done that, simply mention **@ArduinoBot** in a comment here to trigger it to run the automated checks again. After those are passing, your library will automatically be added to Library Manager.

If you have any questions or concerns, please let me know.

Regards, Per

**Comment by and900** [comment]
Hi Per,

Do not understand how to do what you are requesting.

Going round in circles

Cheers
Andrew
All My Things On Line
[http://www.allmythingsonline.com/Images/Amtol/logo.gif]
All My Things On Line<http://www.allmythingsonline.com/>

________________________________

**Comment by and900** [comment]
@ArduinoBot
Committed

**Comment by and900** [comment]
@ArduinoBot

**Comment by and900** [comment]
@ArduinoBot

**Comment by per1234** [comment]
Hello @and900. The automated system here only operates on open pull requests. Since your submission was already accepted and the pull request merged, the bot won't pay any more attention to this pull request.

But this human is happy to provide assistance. Was there something you needed from the bot?

**Comment by and900** [comment]
Hi Per,

Want to update the Library.

How do I  do that?

Regards

Andrew
________________________________

**Comment by per1234** [comment]
@and900 you can learn how to do that here:

https://github.com/arduino/library-registry/blob/main/FAQ.md#how-can-i-publish-a-new-release-once-my-library-is-in-the-list

Please let me know if you have any questions or problems.

**Pull request merged**
