### PR TITLE
Revert "Update repositories.txt"

### PR DESCRIPTION
**Pull request by ProjectoOfficial**
Reverts arduino/library-registry#670

### CODE REVIEW

**Comment by ProjectoOfficial** [comment]
@ArduinoToolingBot

**Comment by ProjectoOfficial** [comment]
@ArduinoBot

**Comment by ProjectoOfficial** [comment]
@ArduinoBot

**Comment by per1234** [comment]
Hello @ProjectoOfficial. As mentioned by the bot, this type of pull request can't be handled by the automated system as is done for submissions. But I'm happy to help out.

I need a little more information in order to do that. Please tell me what is the result you want to achieve via this pull request.

**Comment by per1234** [comment]
Hello @ProjectoOfficial. I'm checking back in with you to see if I can move this forward. If you no longer wish to make this change, I can close the PR in order to keep the issue tracker tidy.

**Comment by per1234** [comment]
Closing due to lack of response.

@ProjectoOfficial if you will provide the requested information by commenting here, I'll be happy to re-open this PR and move forward with the work on it.

**Pull request closed without merging**
