### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by BreadBoardMates**

### CODE REVIEW

**Comment by per1234** [comment]
Hello @BreadBoardMates. I'm commenting hear to make sure you are aware that we are currently having an outage of the system that adds new libraries and library releases to the Arduino Library Manager, as announced here:
<https://github.com/arduino/library-registry/issues/483>
You can follow that issue if you want to get updates on the situation.

The only impact of this is that there will be an unknown delay before this library becomes available for installation via the Arduino Library Manager. Once the system comes back on line, everything will happen as usual, so no special action is needed on your part.

**Comment by BreadBoardMates** [comment]
@ArduinoBot

**Comment by per1234** [comment]
Hi @BreadBoardMates. The automated system here only operates on library submissions. Since your submission was already accepted and the pull request merged, the bot won't pay any more attention to this pull request. But this human is happy to provide assistance. Was there something you needed from the bot?

**Comment by BreadBoardMates** [comment]
Hi @per1234, we are trying to do another library release, moving up the revision number to v1.0.1. Can you point us to how we can properly perform updates?

Thank you very much for your help.

**Comment by per1234** [comment]
The reason your 1.0.1 release was not accepted into the Library Manager index is this change:
https://github.com/BreadBoardMates/Arduino-Mates-Controller/commit/fffc74d32ea9baefde6bb63e66b995a129750d81#diff-f267f9ae2f5d5d56a1dbb305e95d40d4408d9ee7f71357f1f67fb18c29b7f082L1-R2
```diff
- name=Mates Controller
+ name=MatesController
```
The library is locked to the `name` value it had at the time it was admitted to Arduino Library Manager and any release that uses a different `name` value is rejected.

It is possible to change the name if necessary:
https://github.com/arduino/library-registry/blob/main/FAQ.md#how-can-i-change-my-librarys-name
>For the sake of continuity, libraries in the Library Manager list are locked to the name they had at the time they were added to the list. Changing the library name can be disruptive to its users because this is the unique identifier for the library used by the Arduino development software command line interfaces, sketch metadata, library dependencies, and installation location.

**Comment by BreadBoardMates** [comment]
Thanks @per1234 

I've created a change name request #500

**Pull request merged**
