### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by ollprogram**

### CODE REVIEW

**Comment by ollprogram** [comment]
@ArduinoBot

**Comment by ollprogram** [comment]
@ArduinoBot

**Comment by per1234** [comment]
Hello @ollprogram. The automated system here only operates on open pull requests. Since your submission was already accepted and the pull request merged, the bot won't pay any more attention to this pull request.

But this human is happy to provide assistance. Was there something you needed from the bot?

**Comment by ollprogram** [comment]
@per1234 Hello, I'm sorry for this. I just have changed my latest release in order to remove the warnings of the arduino bot to have a better library. And I thought it was possible to retry the analyze of my repository by mentionning the bot. I wanted to see if I removed the warnings. But it's not very important. Thanks for your answer.

**Comment by per1234** [comment]
>I thought it was possible to retry the analyze of my repository by mentionning the bot.

It is not possible. The bot here only checks the library at the time of the submission.

>I wanted to see if I removed the warnings.

The checks are ran every time the Library Manager system indexes a new release of your library. The results are shown on the dedicated logs page for your library:

https://downloads.arduino.cc/libraries/logs/github.com/ollprogram/SimpleShiftRegisterController/

However, it is better to catch problems before you make a release. You can run the same checks locally on your computer using the **Arduino Lint** tool:

https://arduino.github.io/arduino-lint/latest/

Better yet, you might consider setting up an automated check in your library repository for compliance with the Library Manager requirements. This could run on every commit and pull request to ensure such violations are caught immediately.

Arduino provides a [GitHub Actions](https://docs.github.com/en/actions) action that makes this very easy to do by adding a simple YAML file to the repository:

https://github.com/arduino/arduino-lint-action#readme

This action uses the same [Arduino Lint](https://github.com/arduino/arduino-lint) tool as the Library Manager system.

It is in use in all the official Arduino library repositories ([example](https://github.com/arduino-libraries/Servo/blob/master/.github/workflows/check-arduino.yml)).

**Pull request merged**
