### PR TITLE
New library called PTSolns_microWatt

### PR DESCRIPTION
**Pull request by PTSolns**

### CODE REVIEW

**Comment by PTSolns** [comment]
We added the required tag in v1.0.0 release @ArduinoBot

**Comment by PTSolns** [comment]
@ArduinoBot 
1) Something is mixed up, we submitted a new pull request for a new library. Somehow it is thinking this pull request is for the previous one. The previous library we submitted "PTSolns_I2CBackpack", Library that we are submitting now "PTSolns_microWatt".
2) There is an example in the examples folder called GettingStarted.ino...?

**Review by per1234 — COMMENTED** [review]
Hello @PTSolns. Take a look at the "Files changed" tab of the pull request:

https://github.com/arduino/library-registry/pull/3515/files

Do you see that the diff is the addition of two library repository URLs?:

```diff
  https://github.com/Tenveis/SimpleMotorControl
  https://github.com/Finndersen/LEDuino
  https://github.com/ichirowo/FLINT_E220_900T22S_JP_Library
+ https://github.com/PTSolns/PTSolns_I2CBackpack
+ https://github.com/PTSolns/PTSolns_microWatt
```

The reason for this is that you didn't sync your fork with Arduino's repository. If you look at the home page of your fork, you will see this:

image

> This branch is [2 commits ahead](https://github.com/PTSolns/library-registry/compare/arduino:library-registry:main...main), [20 commits behind](https://github.com/PTSolns/library-registry/compare/main...arduino:library-registry:main) arduino:main.

So you are working with a significantly outdated version of the file. This is why you must always sync your fork before you begin work on a pull request you plan to submit to a repository that is under active development.

You can learn how to sync your fork from this tutorial:

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

Doing that will automatically trigger another round of checks from the bot. If it finds all is now well with your pull request, it will be merged immediately and your library added to the Arduino Library Manager.

Please let me know if you have any questions or concerns.

Regards,
Per

**Comment by PTSolns** [comment]
Thank you for your detailed reply! We synced our fork. Hopefully, that did the trick! Cheers - MP

**Review by per1234 — COMMENTED** [review]
> We synced our fork. Hopefully, that did the trick!

@PTSolns it did not do the trick. Your commit that added the new library URL to the file was lost when you did the sync.

If you look at the "Files changed" tab of the pull request, you can see there is no diff at all:

https://github.com/arduino/library-registry/pull/3515/files

**Pull request closed without merging**
