### PR TITLE
remove old library

### PR DESCRIPTION
**Pull request by cotestatnt**
Removal of library YA_FSM which has been replaced by the more efficient and flexible AgileStateMachine

### CODE REVIEW

**Review by per1234 — COMMENTED** [review]
Hello @cotestatnt. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will merge this pull request when it is done. You will get a notification from GitHub at that time.

**Review by per1234 — COMMENTED** [review]
Hello @cotestatnt. I see you closed this pull request. Did you decide you no longer wish to remove the library from Library Manager?

If you want the library to be removed from Library Manager, it is essential for this pull request to be left open. The Library Manager index maintainer will merge the pull request once they have completed the database operations that are necessary for the removal.

**Comment by cotestatnt** [comment]
I apologize, I closed by mistake convinced to act elsewhere.

Yes, please remove the library.

**Review by MatteoPologruto — APPROVED** [review]
Done:
```
2024/03/07 16:47:43 Loaded 6727 libraries from DB
Removing YA_FSM
Success!
```

**Pull request merged**
