### PR TITLE
New library

### PR DESCRIPTION
**Pull request by Adish0016**
Created a new addition for dht 11 with ESP8266 directly

### CODE REVIEW

**Comment by Adish0016** [comment]
@ArduinoBot

**Comment by Adish0016** [comment]
@ArduinoBot

**Comment by Adish0016** [comment]
@ArduinoBot

**Comment by per1234** [comment]
I see that for some reason a repository with a different name was created with duplicate copy of the library, and that library was submitted. So I will close this as a duplicate of https://github.com/arduino/library-registry/pull/2101

**Pull request closed without merging**
