### PR TITLE
Update URL of "KONNEKTING Device Library"

### PR DESCRIPTION
**Pull request by per1234**
Companion to https://github.com/arduino/library-registry/pull/1178

### CODE REVIEW

**Comment by umbynos** [comment]
Done:
```
2022/03/15 08:37:04 Loaded 4702 libraries from DB
Changing URL of library KONNEKTING Device Library from https://github.com/KONNEKTING/KonnektingDeviceLibrary.git to https://gitlab.com/konnekting/KonnektingDeviceLibrary.git
Success!

```

**Comment by tuxedo0801** [comment]
@umbynos  @per1234 
Something's not working properly...

Log (https://downloads.arduino.cc/libraries/logs/gitlab.com/konnekting/KonnektingDeviceLibrary/) says:

2022/03/16 19:02:45 Scraping https://gitlab.com/konnekting/KonnektingDeviceLibrary.git
2022/03/16 19:02:45 Checking out tag: 1.0.0-BETA1
2022/03/16 19:02:45 Error syncing library: Error generating library from repo: can't read library.properties: open /home/ubuntu/workspace/gitclones/gitlab.com/konnekting/KonnektingDeviceLibrary/library.properties: no such file or directory
2022/03/16 19:02:45 Checking out tag: 1.0.0-BETA2
2022/03/16 19:02:45 Error syncing library: Error generating library from repo: can't read library.properties: open /home/ubuntu/workspace/gitclones/gitlab.com/konnekting/KonnektingDeviceLibrary/library.properties: no such file or directory
2022/03/16 19:02:45 Checking out tag: 1.0.0-BETA3
2022/03/16 19:02:45 Release KONNEKTING Device Library:1.0.0-BETA3 already loaded, skipping
2022/03/16 19:02:45 Checking out tag: 1.0.0-BETA4
2022/03/16 19:02:45 Release KONNEKTING Device Library:1.0.0-BETA4 already loaded, skipping
2022/03/16 19:02:45 Checking out tag: 1.0.0-BETA4a
2022/03/16 19:02:45 Release KONNEKTING Device Library:1.0.0-BETA4a already loaded, skipping
2022/03/16 19:02:45 Checking out tag: 1.0.0-BETA4b
2022/03/16 19:02:46 Release KONNEKTING Device Library:1.0.0-BETA4b already loaded, skipping

But there is another git tag "1.0.0-RC1" on gitlab (https://gitlab.com/konnekting/KonnektingDeviceLibrary/-/tags) which the sync does not see:

image

No idea what's wrong. Would be great if you can shed some light on it. Worked with previous tags like a charm...

**Comment by per1234** [comment]
Hi @tuxedo0801. Thanks for your report. I will investigate this.

**Comment by per1234** [comment]
I have good news for you @tuxedo0801. Thanks to your report, I found a bug I made in the tool that is used for managing these library URL change requests in the Arduino Library Manager back end.

I have submitted a fix to avoid this problem for future requests:

https://github.com/arduino/libraries-repository-engine/pull/107

and @umbynos was kind enough to update the outdated data that was produced by the previous uses of the tool.

The correct Git remote URL is now used for your library and the expected release was indexed in the latest run of the job:

https://downloads.arduino.cc/libraries/logs/gitlab.com/konnekting/KonnektingDeviceLibrary/

```text
2022/03/17 10:02:47 Checking out tag: 1.0.0-RC1
```

**Comment by tuxedo0801** [comment]
Thanks a lot.

**Pull request merged**
