### PR TITLE
Remove ArdUAV, navduino, and other libs

### PR DESCRIPTION
**Pull request by PowerBroker2**
Please remove the following libraries:

- ArdUAV
- Autopilot
- navduino
- NEO-6M_GPS
- UM7

### CODE REVIEW

**Comment by PowerBroker2** [comment]
@per1234

**Review by per1234 — COMMENTED** [review]
Hello @PowerBroker2. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will merge this pull request when it is done. You will get a notification from GitHub at that time.

**Comment by per1234** [comment]
@PowerBroker2 I see you deleted your fork of this repository. That caused the pull request to be closed.

Did you decide you no longer wish to have these libraries removed?

If you still want to have them removed, it is important that this pull request be merged instead of being closed.

**Comment by PowerBroker2** [comment]
I had some new libraries I wanted to add to the list, but didn't know how to update my fork properly. I took a risk to just delete my fork, refork, and start from scratch, but I didn't realize it would delete all the PRs for library removal.

I still want the libs removed, though. I just had a screw up trying to add other libs.

**Comment by per1234** [comment]
In the future, create a dedicated branch in your fork for each pull request. Push any changes you want to submit via the PR to that branch. This way you can manage multiple PRs for independent changes without interference with each other.

You should never submit a pull request from the `main` branch of a fork. This way you can simply click the convenient "Sync fork" button on your fork's GitHub web interface to bring the fork's `main` branch up to date with the parent repository's `main` before creating each new PR branch off the `main` branch.

If you created a fork solely for the purposes of submitting PRs and all the PRs have been merged, you can then delete the fork, but you should not delete it while PRs submitted from the fork are still open.

> I still want the libs removed, though.

OK, I recreated the PR on your behalf: https://github.com/arduino/library-registry/pull/4878

**Pull request closed without merging**
