### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by piscodev**
Request for adding wrapper for Arduino UNO R4 WiFi HttpClient

### CODE REVIEW

**Comment by piscodev** [comment]
@ArduinoBot

**Comment by per1234** [comment]
Hello @piscodev. The automated system here only operates on open pull requests. Since your submission was already accepted and the pull request merged, the bot won't pay any more attention to this pull request.

But this human is happy to provide assistance. Was there something you needed from the bot?

**Comment by piscodev** [comment]
I thought calling the bot re-scrapes the index. Made some mistake on my properties, it was v1.0.1 but my release were still v1, then I updated  the properties back to v1 back after being scraped.

**Comment by piscodev** [comment]
@ArduinoBot

I have updated to 1.0.2 but it hasnt scraped the new version, what could have happened?

**Comment by per1234** [comment]
> @ArduinoBot
>

@piscodev I already explained to you that mentioning the bot doesn't have any effect after your pull request has been merged. _**So why are you still doing it???????????????**_

>I have updated to 1.0.2 but it hasnt scraped the new version

I see it in my Library Manager. Please check again. It takes time for the new release to be indexed and then the updated index to work through the cache. We give a conservative estimate of availability within one day's time. So please don't expect instant results.

**Comment by per1234** [comment]
> do you have a suggestion on how to produce a lossless properties file?

Hi @tobozo. I compared @piscodev's `library.properties` file to this one, which is correctly rendered:

https://gitlab.com/xoan/escornabot-extlib/-/raw/master/library.properties

I found that the file encoding of the working one is UTF-8, while the encoding of @piscodev's file is ISO-8859:

```text
$ mkdir -p /tmp/library_properties_encoding/R4HttpClient

$ wget --output-document=/tmp/library_properties_encoding/R4HttpClient/library.properties https://github.com/piscodev/r4httpclient/raw/refs/heads/main/library.properties

[...]

$ mkdir -p /tmp/library_properties_encoding/EscornabotEXT

$ wget --output-document=/tmp/library_properties_encoding/EscornabotEXT/library.properties https://gitlab.com/xoan/escornabot-extlib/-/raw/master/library.properties

[...]

$ file /tmp/library_properties_encoding/R4HttpClient/library.properties /tmp/library_properties_encoding/EscornabotEXT/library.properties

/tmp/library_properties_encoding/R4HttpClient/library.properties:  ISO-8859 text
/tmp/library_properties_encoding/EscornabotEXT/library.properties: Unicode text, UTF-8 text, with very long lines (353)
```

So it should be possible to fix the rendering problem by changing the file encoding to UTF-8

**Pull request merged**
