### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by CDTParaguana**

### CODE REVIEW

**Review by per1234 — COMMENTED** [review]
Hello @CDTParaguana.  Thanks for your interest in contributing to the Arduino Library Manager index.

I see the bot reported a problem with your submission that will block its acceptance:

> :x: **ERROR:** Unable to load submission URL. Is the repository public?

Please fix the problem so we can proceed with your submission. If you have any questions or problems while following the instructions to resolve the problem, please let me know and I'll help out.

If you decide you no longer wish to submit the library, you can close this pull request.

**Comment by CDTParaguana** [comment]
@ArduinoBot Done

**Comment by CDTParaguana** [comment]
@ArduinoBot Done

**Comment by CDTParaguana** [comment]
@ArduinoBot Done

**Comment by CDTParaguana** [comment]
@ArduinoBot  Done

**Comment by CDTParaguana** [comment]
@ArduinoBot Done

**Review by per1234 — COMMENTED** [review]
@CDTParaguana I see you attempted to fix the problem reported by the bot:

> ❌ ERROR: Library is missing a `library.properties` metadata file.

But the file you added is named `[biblioteca.properties](https://github.com/CDTParaguana/Controlador_Vergatario/blob/main/biblioteca.properties)` instead of `library.properties`. You **MUST** name the file exactly `library.properties`. Just as you wouldn't translate a C++ keyword in your code, you also should not translate special filenames.

**Comment by CDTParaguana** [comment]
@ArduinoBot  Done

**Comment by CDTParaguana** [comment]
@ArduinoBot  Done

**Pull request closed without merging**
