### PR TITLE
chore: add new unified repo to library manager

### PR DESCRIPTION
**Pull request by koen1711**

### CODE REVIEW

**Comment by koen1711** [comment]
@ArduinoToolingBot

**Comment by koen1711** [comment]
@ArduinoBot

**Comment by per1234** [comment]
Hello @koen1711. The automated system here only operates on open pull requests. Since your submission was already accepted and the pull request merged, the bot won't pay any more attention to this pull request.

But this human is happy to provide assistance. Was there something you needed from the bot?

**Comment by koen1711** [comment]
> Hello @koen1711. The automated system here only operates on open pull requests. Since your submission was already accepted and the pull request merged, the bot won't pay any more attention to this pull request.
> 
> But this human is happy to provide assistance. Was there something you needed from the bot?

Hi thank you for your response, I kinda got a little impatient and reading this I thought to get the new version out faster I had the ping the bot. But thank you so much man!!!
https://github.com/arduino/library-registry?tab=readme-ov-file#if-the-problem-is-with-the-library

**Pull request merged**
