### PR TITLE
Update URL of "micro_ros_kaia"

### PR DESCRIPTION
**Pull request by per1234**
Companion to ~~https://github.com/arduino/library-registry/pull/3372~~ https://github.com/arduino/library-registry/pull/3396

### CODE REVIEW

**Comment by per1234** [comment]
On hold due to a series of unexplained actions by @kaiaai since the time of the original URL change request. I am waiting for an explanation at https://github.com/arduino/library-registry/pull/3378

**Comment by per1234** [comment]
Moving forward again with the URL update.

**Review by MatteoPologruto — APPROVED** [review]
Done:
```
2023/10/04 16:01:38 Loaded 6237 libraries from DB
Changing URL of library micro_ros_kaia from https://github.com/kaiaai/micro_ros_arduino_kaia.git to https://github.com/kaiaai/micro_ros_arduino_kaiaai.git
Success!
```

**Comment by kaiaai** [comment]
Thank you, much appreciated!

**Pull request merged**
