### PR TITLE
Remove "FloatToString"

### PR DESCRIPTION
**Pull request by per1234**
Companion to https://github.com/arduino/library-registry/pull/4084

### CODE REVIEW

**Review by MatteoPologruto — APPROVED** [review]
Done:
```
2024/02/21 16:09:09 Loaded 6678 libraries from DB
Removing FloatToString
warning: Library Git clone folder /home/ubuntu/workspace/gitclones/github.com/koendv/FloatToString not present
Success!
```

**Comment by tedtoal** [comment]
Created new release of FloatToString but it is not being picked up by the library manager and I don't know why.  @ArduinoBot

**Comment by per1234** [comment]
Hi @tedtoal. I can see it in my Library Manager:

image

It takes some time for the updated index to work through the CDN and local cache so you might have just checked too soon. Please look again now.

We give a conservative estimate that a new release will become available to everyone within one day's time.

**Comment by tedtoal** [comment]
I was looking here expecting to see it, and still don’t:

https://downloads.arduino.cc/libraries/logs/github.com/tedtoal/floatToString/



On Aug 24, 2024, at 5:00 PM, per1234 ***@***.***> wrote:



Hi @tedtoal<https://github.com/tedtoal>. I can see it in my Library Manager:

image.png (view on web)<https://github.com/user-attachments/assets/9d7a20b7-0cbe-42e8-8a0e-f88f8b8d923f>

It takes some time for the updated index to work through the CDN and local cache so you might have just checked too soon. Please look again now.

We give a conservative estimate that a new release will become available to everyone within one day's time.

**Comment by per1234** [comment]
Unfortunately the Arduino web team have instated a draconian caching policy on the log web pages so they are often days out of date.

So check your Library Manager.

**Pull request merged**
