### PR TITLE
TinyGPS

### PR DESCRIPTION
**Pull request by TinyuZhao**

### CODE REVIEW

**Comment by Tinyu-Zhao** [comment]
@ArduinoBot

**Comment by Tinyu-Zhao** [comment]
@ArduinoBot

**Comment by per1234** [comment]
Hello @Tinyu-Zhao. The automated system here only operates on library submissions. Since your submission was already accepted and the pull request merged, the bot won't pay any more attention to this pull request. But this human is happy to provide assistance. Was there something you wanted from the bot?

**Comment by per1234** [comment]
Ah, I see you were now successful with submitting it via https://github.com/arduino/library-registry/pull/369
Thanks!

**Pull request closed without merging**
