### PR TITLE
add library cafeiot

### PR DESCRIPTION
**Pull request by cafeiot**

### CODE REVIEW

**Comment by cafeiot** [comment]
retry

**Comment by cafeiot** [comment]
@ArduinoBot

**Comment by cafeiot** [comment]
@ArduinoBot

**Comment by cafeiot** [comment]
@ArduinoBot

**Comment by cafeiot** [comment]
@ArduinoBot

**Comment by cafeiot** [comment]
@ArduinoBot

**Comment by per1234** [comment]
Hello @cafeiot. I see you have fixed the error reported by the bot:

```
Linting library in CafeIOT_Esp8266

[...]

ERROR: Library name Iotkaran is in use by a library in the Library Manager index. Each library must have a unique name  
       value. If your library is already in the index, use the "--library-manager update" flag. (Rule LP017)            
```

However, Library Manager works exclusively from Git tags, so the bot won't be able to see the fix you made until you create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.

You can see that at the latest tag, the problem was still present;

https://github.com/cafeiot/CafeIOT_Esp8266/blob/v0.1/library.properties#L1

```
name=Iotkaran
```

Remember to update the `version` field in the library's [`library.properties` file](https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format) as needed before making a release/tag.

Once you have done that, simply mention **@ArduinoBot** in a comment here to trigger it to run the automated checks again. After those are passing, your library will automatically be added to Library Manager.

**Pull request closed without merging**
