### PR TITLE
merge the branch

### PR DESCRIPTION
**Pull request by roshanraj2**

### CODE REVIEW

**Comment by roshanraj2** [comment]
arduino/library-registry @ArduinoBot

**Review by per1234 — COMMENTED** [review]
@roshanraj2 this is the third pull request you have submitted to remove or add newlines at the end of the file. This is not productive.

I am guessing you are attempting to accomplish something, but I'm not psychic so it is impossible for me to guess what you are trying to accomplish. I would be happy to provide assistance but I can only do that if you clearly communicate what your goal is with these pull requests.

**Comment by roshanraj2** [comment]
Hi @per1234, I have a update in my library repo under same tag version. how should I have to update it to the Arduino library registry . Do I need to delete the repo then should i have to add it again or the changes in the same tag will get updated in arduino library also.

**Comment by per1234** [comment]
Hi @roshanraj2. You must make a new tag when you want to distribute updates to the library:

1. Bump the value of the `version` field in the library's `library.properties` metadata file.
1. Create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.

After the initial addition of the library, the indexer job periodically checks each of the libraries in the index and picks up any new release/tag that meets the requirements listed here:

https://github.com/arduino/library-registry/blob/main/FAQ.md#what-are-the-requirements-for-publishing-new-releases-of-libraries-already-in-the-library-manager-list

This means there is no need to take any additional action to add new releases of your library to Library Manager. They will be added automagically!

It does take a little time for the indexer job to run, and then some additional time after that for the update to propagate through the CDN and the local cache. But it will get there. We give a conservative estimate of availability within one day's time.

You can monitor the indexing of the library releases by checking the library's dedicated indexer logs web page:
https://github.com/arduino/library-registry/blob/main/FAQ.md#user-content-can-i-check-on-library-releases-being-added-to-library-manager

**Comment by roshanraj2** [comment]
HI @per1234, My changes are need to be done in library.properties file to change the sentence and paragraph. does these updates will be automatically updated by indexer.

**Comment by per1234** [comment]
The indexer works exclusively from Git tags (or GitHub releases, which generate Git tags). If you change the `sentence` and `paragraph` fields of the `library.properties` file, bump the version number in the `version` field of the file, and then make a new tag or release, then the new release of the library will have the updated sentence and paragraph data in Library Manager.

**Pull request closed without merging**
