### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by fangamy**
tuya ble mcu sdk

### CODE REVIEW

**Comment by fangamy** [comment]
@ArduinoBot

**Comment by fangamy** [comment]
update library.properties,，@ArduinoBot

**Comment by per1234** [comment]
@fangamy 
@fangamy
@fangamy
@fangamy
@fangamy

Hi. Let's talk about this. If you keep doing the same thing, you are going to keep getting the same result. I'm here to help you, but I can only do that if you communicate with me. Please just leave this PR open so we can have a conversation and get this resolved.

I see you have fixed the error reported by the bot. However, Library Manager works exclusively from Git tags. You can see that at the last tag the problem was still present:
https://github.com/tuya/tuya-ble-mcu-sdk-arduino-library/blob/0.0.1/library.properties#L8

So the bot won't be able to see the fix you made until you create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.

Remember to update the `version` field in the library's [`library.properties` file](https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format) as needed before making a release/tag.

Once you have done that, simply mention **@ArduinoBot** in a comment here to trigger it to run the automated checks again. After those are passing, your library will automatically be added to Library Manager.

**Comment by fangamy** [comment]
I‘m sorry，@ArduinoBot

**Pull request merged**
