### PR TITLE
Add Blues Notecard Environment Variable Manager

### PR DESCRIPTION
**Pull request by zfields**

### CODE REVIEW

**Review by per1234 — COMMENTED** [review]
Hello @zfields.  Thanks for your interest in contributing to the Arduino Library Manager index.

I see the bot reported a problem with your submission that will block its acceptance:

```text
ERROR: Symlink(s) found. Symlinks cause difficulties for Windows users. These block addition to the Arduino Library     
       Manager index:                                                                                                   
         notecard-env-var-manager/examples/zephyr/NotecardEnvVarManager.c                                               
         notecard-env-var-manager/examples/zephyr/NotecardEnvVarManager.h                                               
```

If you have any questions or problems while following the instructions to resolve the problem, please let me know and I'll help out.

If you decide you no longer wish to submit the library, you can close this pull request.

**Comment by zfields** [comment]
Hi @per1234, thanks for your help in ciphering the message!

The folder in question is for an unrelated `zephyr` implementation.

Is it possible to indicate in the `library.properties` file that we would like to ignore a specific subfolder, or is there a common workaround for this?

**Comment by per1234** [comment]
> Is it possible to indicate in the library.properties file that we would like to ignore a specific subfolder

At this time, the entire contents of the repository are included in the archive generated by the Library Manager system for installation on the user's machine.

There is a request for a feature that would allow something like this here: https://github.com/arduino/libraries-repository-engine/issues/59

>is there a common workaround for this?

You will need to ensure the tagged releases do not contain any symlinks. One option would be to move the Zephyr example to a dedicated repository and then incorporate the library files into the example project by adding the library repository to the Zephyr example repository as a Git submodule (as I see is already being done for some other libraries).

**Comment by zfields** [comment]
So if we were to create a `samples/` folder and move `zephyr/` to that new folder in our repository.

What would be required to resubmit the CI jobs (checks)?

**Comment by zfields** [comment]
Hello @ArduinoBot!

We are ready to try again!

**Review by per1234 — COMMENTED** [review]
Hello . I see you have fixed the error reported by the bot. However, Library Manager works exclusively from Git tags, so the bot won't be able to see the fix you made until you create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.

If you look at the repository contents at the latest tag, you can see that the version the bot is checking still has the problem:

https://github.com/blues/notecard-env-var-manager/tree/v1.0.0/examples/zephyr

❗ Remember to update the `version` field in the library's [`library.properties` file](https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format) as needed before making a release/tag.

Once you have done that, simply mention **@ArduinoBot** in a comment here to trigger it to run the automated checks again. After those are passing, your library will automatically be added to Library Manager.

If you have any questions or concerns, please let me know.

Regards, Per

**Comment by zfields** [comment]
Okay @ArduinoBot, I have a new _VERSION_ for you to test! :+1:

**Pull request merged**
