### PR TITLE
add https://github.com/machinefi/w3bstream-client-arduino-ce

### PR DESCRIPTION
**Pull request by as-iotex**

### CODE REVIEW

**Comment by as-iotex** [comment]
@per1234  I have fixed the errors already. Could you take a look at what's wrong?

**Review by per1234 — COMMENTED** [review]
Hello @as-iotex.  Thanks for your interest in contributing to the Arduino Library Manager index.

I see the bot reported a problem with your submission that will block its acceptance:

```text
ERROR: library.properties url value is less than minimum length.
```

The cause of the error was somewhat subtle, so I went ahead and submitted a pull request to fix the problem:

https://github.com/machinefi/w3bstream-client-arduino-ce/pull/3

So to move forward with this submission, the following steps will need to be taken:

1. Merge https://github.com/machinefi/w3bstream-client-arduino-ce/pull/3
1. Bump the value of the `version` property  in `library.properties`
1. Make a new tag or release in the library repository
1. Comment here in the pull request thread, mentioning ****@ArduinoBot** in the comment.

The last step will automatically trigger another round of checks on the submission. If everything is found to be compliant, the submission will be accepted and the library will be added to Library Manager.

If you have any questions or problems while following the instructions to resolve the problem, please let me know and I'll help out.

**Comment by as-iotex** [comment]
Thanks very much for taking a look at this. I have merged your PR and made a new release

**Comment by as-iotex** [comment]
@ArduinoBot

**Pull request merged**
