### PR TITLE
iarduino.ru libraries

### PR DESCRIPTION
**Pull request by drondistortion**
repositories for iarduino.ru made libraries

### CODE REVIEW

**Review by per1234 — COMMENTED** [review]
Hello @drondistortion. I errors reported by the bot have already been fixed. However, Library Manager works exclusively from Git tags, so the bot won't be able to see the fix you made until you create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.

If you look at the repository contents at the latest tag, you can see that the version the bot is checking still has the problem. For example:

https://github.com/tremaru/iarduino_Bluetooth_HC05/tree/1.1.1/examples/HardwareSerial/AT-command

(note the invalid `AT-command (2).ino` file is still present

https://github.com/tremaru/iarduino_I2C_Software/tree/1.0.1/examples/SoftwareWire/findDevices

(note the invalid `findDevices (2).ino` file is still present

https://github.com/tremaru/iarduino_4LED/blob/1.0.2/library.properties#L1

```text
name =			iarduino 4LED (4 разрядный LED индикатор)
```

❗ Remember to update the `version` field in the library's [`library.properties` file](https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format) as needed before making a release/tag.

Once you have done that, simply mention **@ArduinoBot** in a comment here to trigger it to run the automated checks again. After those are passing, your library will automatically be added to Library Manager.

If you have any questions or concerns, please let me know.

Regards, Per

**Comment by drondistortion** [comment]
@ArduinoBot now superly-duperly fixed

**Review by per1234 — COMMENTED** [review]
Hello @drondistortion. Thanks for your interest in contributing to the Arduino Library Manager index.

I see the bot reported a problem with your submission that will block its acceptance:

>❌ ERROR: Your submission meets all requirements. However, the pull request could not be merged.
>
>Please follow this guide to resolve a merge conflict:
https://docs.github.com/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-on-github

Please fix the merge conflict so we can proceed with your submission.

---

If you find it too challenging to fix the merge conflict, I would be happy to take care of it for you, but first I will need you to enable the pull request's "**Allow edits from maintainers**" setting. You can do that by following these instructions:
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

Once that is done, please comment here to let me know.
Please let me know if you have any questions or concerns.

Regards, Per

**Comment by drondistortion** [comment]
@per1234 resolved

**Pull request merged**
