### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by Frederik-Eberhard**

### CODE REVIEW

**Comment by Frederik-Eberhard** [comment]
@ArduinoBot

**Comment by per1234** [comment]
Hi @Frederik-Eberhard. I see you already added a library of this name from a different repository:

https://github.com/Frederik-Eberhard/Excelsior

Please tell me exactly what you are hoping to accomplish and I'll provide assistance.

**Comment by Frederik-Eberhard** [comment]
Hi @per1234,

I'm trying to replace my former Library directory with the new one. It is still the same library. Can I simply edit my entry in the index with a new pull-request to update the directory since I'm the owner of both libraries?

**Comment by per1234** [comment]
Yes. Editing the existing entry to the new URL is the correct way to accomplish the URL change.

**Comment by per1234** [comment]
For the sake of a tidy repository, I'm going to close this due to lack of activity.

@Frederik-Eberhard feel free to submit another pull request to update the library URL.

I'll continue to monitor this thread, so feel free to let me know if you have any questions or concerns.

**Pull request closed without merging**
