### PR TITLE
Change library name

### PR DESCRIPTION
**Pull request by tfeldmann**
Changed from "Schmitt trigger" to "SchmittTrigger".
This change is also done in the library's properties.

### CODE REVIEW

**Review by per1234 — APPROVED** [review]

**Comment by per1234** [comment]
Hi @tfeldmann. Thanks for making the extra effort to submit a PR the name change.

Unlike submissions, this type of request is still handled manually. The Library Manager index's maintainer occasionally comes through to clear all the outstanding requests and closes/merges those issues/PRs when that is done. You'll get a notification at that time.

After that, you can monitor the indexing of the library via its logs web page:

https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by tfeldmann** [comment]
I'm sorry for the trouble. The linter gave a hints about naming conventions that I wanted to follow. Thanks for the heads up!

**Comment by rsora** [comment]
@per1234 backend maintenance operations are done

**Comment by rsora** [comment]
Closes #183

**Pull request merged**
