### PR TITLE
Add Deneyap Arduino Example Library

### PR DESCRIPTION
**Pull request by DogushC**
Add Deneyap Arduino Example Library.

### CODE REVIEW

**Comment by DogushC** [comment]
> A problem was found with your submission https://github.com/deneyapkart/deneyap_arduino_examples
> 
> ❌ **ERROR:** Unable to load submission URL. Is the repository public?

Public now.

**Comment by DogushC** [comment]
> 

Add a dummy library. @ArduinoBot

**Comment by DogushC** [comment]
> ❌ **ERROR:** [Arduino Lint](https://github.com/arduino/arduino-lint) found errors with https://github.com/deneyapkart/deneyap_arduino_examples:
> 
> ```
> Linting library in deneyap_arduino_examples
> ERROR: Path does not contain a valid Arduino library.                         
>        See: https://arduino.github.io/arduino-cli/latest/library-specification
>        (Rule LS001)                                                           
> INFO: No header file found matching library name (Deneyap_Arduino_Examples.h). Best practices are for primary header    
>       filename to match library name.                                                                                   
>       See: https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format            
>       (Rule LS008)                                                                                                      
> WARNING: library.properties name value Deneyap Arduino Examples is longer than the recommended length of 16 characters.
>          See: https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format        
>          (Rule LP010)                                                                                                  
> WARNING: Library name Deneyap Arduino Examples contains "Arduino". This is superfluous.                        
>          See: https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format
>          (Rule LP014)                                                                                          
> WARNING: library.properties name Deneyap Arduino Examples contains spaces. Although supported, best practices is to not 
>          use spaces.                                                                                                    
>          See: https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format         
>          (Rule LP015)                                                                                                   
> WARNING: The library.properties paragraph field repeats the sentence field. These are displayed together so redundancy  
>          is not needed.                                                                                                 
>          See: https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format         
>          (Rule LP036)                                                                                                   
> WARNING: No example sketches found. Please provide examples.                                      
>          See: https://arduino.github.io/arduino-cli/latest/library-specification/#library-examples
>          (Rule LD004)                                                                             
> 
> Linter results for project: 1 ERRORS, 5 WARNINGS
> 
> -------------------
> ```

Fix the error. @ArduinoBot

**Comment by DogushC** [comment]
> 

We have a header file as "dummy.h"... @ArduinoBot

**Comment by DogushC** [comment]
> ❌ **ERROR:** [Arduino Lint](https://github.com/arduino/arduino-lint) found errors with https://github.com/deneyapkart/deneyap_arduino_examples:
> 
> ```
> Linting library in deneyap_arduino_examples
> ERROR: Path does not contain a valid Arduino library.                         
>        See: https://arduino.github.io/arduino-cli/latest/library-specification
>        (Rule LS001)                                                           
> INFO: No header file found matching library name (Deneyap_Arduino_Examples.h). Best practices are for primary header    
>       filename to match library name.                                                                                   
>       See: https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format            
>       (Rule LS008)                                                                                                      
> WARNING: library.properties name value Deneyap Arduino Examples is longer than the recommended length of 16 characters.
>          See: https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format        
>          (Rule LP010)                                                                                                  
> WARNING: Library name Deneyap Arduino Examples contains "Arduino". This is superfluous.                        
>          See: https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format
>          (Rule LP014)                                                                                          
> WARNING: library.properties name Deneyap Arduino Examples contains spaces. Although supported, best practices is to not 
>          use spaces.                                                                                                    
>          See: https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format         
>          (Rule LP015)                                                                                                   
> WARNING: The library.properties paragraph field repeats the sentence field. These are displayed together so redundancy  
>          is not needed.                                                                                                 
>          See: https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format         
>          (Rule LP036)                                                                                                   
> WARNING: No example sketches found. Please provide examples.                                      
>          See: https://arduino.github.io/arduino-cli/latest/library-specification/#library-examples
>          (Rule LD004)                                                                             
> 
> Linter results for project: 1 ERRORS, 5 WARNINGS
> 
> -------------------
> ```

@ArduinoBot

**Comment by DogushC** [comment]
> ❌ **ERROR:** [Arduino Lint](https://github.com/arduino/arduino-lint) found errors with https://github.com/deneyapkart/deneyap_arduino_examples:
> 
> ```
> Linting library in deneyap_arduino_examples
> ERROR: Path does not contain a valid Arduino library.                         
>        See: https://arduino.github.io/arduino-cli/latest/library-specification
>        (Rule LS001)                                                           
> INFO: No header file found matching library name (Deneyap_Arduino_Examples.h). Best practices are for primary header    
>       filename to match library name.                                                                                   
>       See: https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format            
>       (Rule LS008)                                                                                                      
> WARNING: library.properties name value Deneyap Arduino Examples is longer than the recommended length of 16 characters.
>          See: https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format        
>          (Rule LP010)                                                                                                  
> WARNING: Library name Deneyap Arduino Examples contains "Arduino". This is superfluous.                        
>          See: https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format
>          (Rule LP014)                                                                                          
> WARNING: library.properties name Deneyap Arduino Examples contains spaces. Although supported, best practices is to not 
>          use spaces.                                                                                                    
>          See: https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format         
>          (Rule LP015)                                                                                                   
> WARNING: The library.properties paragraph field repeats the sentence field. These are displayed together so redundancy  
>          is not needed.                                                                                                 
>          See: https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format         
>          (Rule LP036)                                                                                                   
> WARNING: No example sketches found. Please provide examples.                                      
>          See: https://arduino.github.io/arduino-cli/latest/library-specification/#library-examples
>          (Rule LD004)                                                                             
> 
> Linter results for project: 1 ERRORS, 5 WARNINGS
> 
> -------------------
> ```

@ArduinoBot

**Comment by DogushC** [comment]
> Hello @DogushC. I see you have fixed the error reported by the bot. However, Library Manager works exclusively from Git tags, so the bot won't be able to see the fix you made until you create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.
> 
> If you look at the repository contents at the latest tag, you can see that the version the bot is checking still has the problem:
> 
> https://github.com/deneyapkart/deneyap_arduino_examples/tree/1.0.0
> 
> ❗ Remember to update the `version` field in the library's [`library.properties` file](https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format) as needed before making a release/tag.
> 
> Once you have done that, simply mention **@ArduinoBot** in a comment here to trigger it to run the automated checks again. After those are passing, your library will automatically be added to Library Manager.
> 
> If you have any questions or concerns, please let me know.
> 
> Regards, Per

Thanks. Done.

**Review by per1234 — COMMENTED** [review]
Hi @DogushC. A merge conflict must be resolved before this pull request can be merged.

I would like to assist with that, but first I will need you to enable the pull request's "**Allow edits from maintainers**" setting. You can do that by following these instructions:
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

Once that is done, please comment here to let me know.

---

If you prefer to resolve the merge conflict yourself, you can follow the instructions here:

https://docs.github.com/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-on-github

---

Please let me know if you have any questions or concerns.

**Comment by DogushC** [comment]
> Hi @DogushC. A merge conflict must be resolved before this pull request can be merged.
> 
> I would like to assist with that, but first I will need you to enable the pull request's "**Allow edits from maintainers**" setting. You can do that by following these instructions: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork
> 
> Once that is done, please comment here to let me know.
> 
> If you prefer to resolve the merge conflict yourself, you can follow the instructions here:
> 
> https://docs.github.com/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-on-github
> 
> Please let me know if you have any questions or concerns.

Done. @per1234

**Pull request merged**
