### PR TITLE
Add Log repository

### PR DESCRIPTION
**Pull request by loginov-rocks**

### CODE REVIEW

**Comment by loginov-rocks** [comment]
`Log` is in use via https://github.com/arduino/library-registry/blob/main/repositories.txt#L4614C38-L4614C40 `https://github.com/ploys/arduino-logger` - last release in October, 2017 https://github.com/nik-sharky/arduino-logger/releases/tag/v1.0.1

**Review by per1234 — COMMENTED** [review]
Hello . Thanks for your interest in contributing to the Arduino Library Manager index.

As you noticed, the bot reported problems with your submission that will block its acceptance:

```text
ERROR: Path does not contain a valid Arduino library.                         
       See: https://arduino.github.io/arduino-cli/latest/library-specification
       (Rule LS001)                                                           
```

The Arduino Library Specification requires that all code files be located under the `src` subfolder of the repository:

https://arduino.github.io/arduino-cli/latest/library-specification/#source-code

We do not support the PlatformIO `include`/`src` structure. Please move the code files under the `src` subfolder. PlatformIO also supports this structure so this won't cause any problems with PlatformIO compatibility.

A header file must be present in the root of this folder, but you are welcome to organize the rest of the files in any structure of subfolders you like. If for some reason you are set on having all the header files segregated from the source files, you can make that root header file something simple like this:

```text
// This file is present to make the library compliant with the Arduino Library Specification.
#include "include/LogInternal.h"
```

---

```text
ERROR: Library name Log is in use by a library in the Library Manager index. Each library must have a unique name value.
       If your library is already in the index, use the "--library-manager update" flag.                                
       See: https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format           
       (Rule LP017)                                                                                                     
```

Every Arduino library must have a unique name (which is the machine identifier of the library). As you noticed, "Log" is taken so you must pick another one. You can search Library Manager to see if your choice is taken.

The library name is defined in the `name` field of the `library.properties` metadata file. You must change the value of that field.

---

❗ There are no restrictions on the repository name. You are welcome to leave the repository at the name it has now. Or you can change it if you like. If you do change it, please also update the URL in this PR.

---

I also spotted another critical problem with your library. You have a file named `main.cpp` in your `src` folder:

https://github.com/loginov-rocks/Log/blob/main/src/main.cpp

This is a complete program, not a library file. The Arduino sketch build system compiles all the source files under the `src` subfolder. Obviously it is essential that this file is not compiled with the library.

Since it is an example of the library usage, you should move this to a dedicated folder under the `examples` subfolder of the library:

https://arduino.github.io/arduino-cli/latest/library-specification/#library-examples

You must convert it to a sketch, which is accomplished by changing the file extension from `.cpp` to `.ino`. If you don't like that, alternatively, you can add an empty `.ino` file to the folder (the sketch build system compiles all the source files in the sketch folder. Make sure to carefully review the Arduino Sketch Specification to ensure you create a valid sketch:

https://arduino.github.io/arduino-cli/latest/sketch-specification/

---

These problems indicate that you have not made any effort to validate that your library will work with the official Arduino development software. It is pointless and irresponsible to submit a non-functional library. Please take the time to thoroughly test your library using one of the official Arduino development tools:

- [**Arduino IDE**](https://docs.arduino.cc/software/ide-v2)
- [**Arduino CLI**](https://arduino.github.io/arduino-cli/latest/)
- [**Arduino Cloud Editor**](https://docs.arduino.cc/arduino-cloud/guides/cloud-editor)

---

Please fix the problems so we can proceed with your submission.

You will need to do the following things:

1. Fix all the problems I reported above, as well as any others you find through your own testing.
1. Bump the value of the `version` field in the library's `library.properties` metadata file.
1. Create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.
1. Add a comment here in the pull request thread that mentions **@ArduinoBot**.

After that, the automated checks will run again. Once those are passing, your library will automatically be added to Library Manager.

If you have any questions or concerns, please let me know.

Regards, Per

**Review by per1234 — COMMENTED** [review]
For the sake of a tidy repository, I'm going to close this due to lack of activity.

@loginov-rocks if you ever resolve the issues, please submit another pull request to add the library.

I'll continue to monitor this thread, so feel free to let me know if you have any questions or concerns.

**Comment by loginov-rocks** [comment]
Hi @per1234,

Thank you so much for taking the time to provide such a thorough and detailed review of my library submission! I really appreciate the feedback and will work on making the necessary changes to ensure compliance with the Arduino Library Specification.

Just out of curiosity, could you clarify your role in this process? I’d love to know more about how you’re involved in the Arduino ecosystem for future contributions.

Thanks again for your guidance, and I look forward to getting the library up to standard!

**Comment by per1234** [comment]
>could you clarify your role in this process?

I'm the primary maintainer of this repository, and responsible for the development of its infrastructure.

**Pull request closed without merging**
