### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by sswartley**
This is a pull request to change the URL of a library that already exists in the Library Manager. The current URL points to an individual's Git account ("dvernier"). The new URL will point to the official Git account for Vernier Science Education. In addition, the new URL contains an updated version of the VernierLib library (1.0.6)

### CODE REVIEW

**Review by per1234 — COMMENTED** [review]
Hello @sswartley. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will merge this pull request when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Review by MatteoPologruto — APPROVED** [review]
Done:
```
2023/10/18 15:03:54 Loaded 6279 libraries from DB
Changing URL of library VernierLib from https://github.com/dvernier/VernierLib.git to https://github.com/VernierST/VernierLib.git
Success!
```

**Comment by per1234** [comment]
Hi @sswartley. It is mandatory to add the trailing slash to the URL:

https://downloads.arduino.cc/libraries/logs/github.com/VernierST/VernierLib/

**Comment by sswartley** [comment]
Thanks @per1234 - all looks good!

**Pull request merged**
