### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by finani**
Thank you for your kind instruction! x2
from #638

### CODE REVIEW

**Comment by per1234** [comment]
Hello @finani. Regarding the problem reported by the bot:
```
ERROR: Library name Arduino_ICM20689 starts with "Arduino". These names are reserved for official libraries. (Rule      
       LP012)                                                                                                           
```
 I see you have already resolved it (https://github.com/finani/ICM20689/commit/dc649396fd43d91220f14ce70acce6698ec2e370). However, Library Manager works exclusively from Git tags, and the problem was still present at the time of the latest release:
https://github.com/finani/ICM20689/blob/v1.0.0/library.properties#L1

So the bot won't be able to see the fix you made until you create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.

**Comment by finani** [comment]
> Hello @finani. Regarding the problem reported by the bot:
> 
> ```
> ERROR: Library name Arduino_ICM20689 starts with "Arduino". These names are reserved for official libraries. (Rule      
>        LP012)                                                                                                           
> ```
> 
> I see you have already resolved it ([finani/ICM20689@dc64939](https://github.com/finani/ICM20689/commit/dc649396fd43d91220f14ce70acce6698ec2e370)). However, Library Manager works exclusively from Git tags, and the problem was still present at the time of the latest release: https://github.com/finani/ICM20689/blob/v1.0.0/library.properties#L1
> 
> So the bot won't be able to see the fix you made until you create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.

Thank you so much.

I can't see what is the problem. bbb

**Comment by finani** [comment]
@ArduinoBot

**Comment by finani** [comment]
@ArduinoBot

**Pull request merged**
