### PR TITLE
New library: FlashStringTable

### PR DESCRIPTION
**Pull request by tig**

### CODE REVIEW

**Comment by tig** [comment]
@ArduinoBot - fixed issues (I think)

**Comment by tig** [comment]
@ArduinoBot added license

**Comment by per1234** [comment]
Hello @tig. Thanks for your attention to the suggestions from the bot. Documenting the library's license in the standardized form of the licence file is very useful.

It's not mandatory to resolve the items in the Arduino Lint report marked "WARNING", only those marked "ERROR". Since Arduino Lint didn't find any errors in the library, the bot accepted the submission and it is already available for installation via Arduino Library Manager. The bot only handles the submission process, so once the library has been accepted it no longer responds to the PR thread.

Arduino Lint is also run by the automated indexer system that picks up new releases of your library whenever you push a tag to GitHub. When there are any errors or warnings, the Arduino Lint report is published on the dedicated logs web page for your library here:
http://downloads.arduino.cc/libraries/logs/github.com/tig/FlashStringTable/
You can see that the v0.6.0 tag got a clean bill of health!

You also have the option of downloading and running Arduino Lint on your library locally:
https://arduino.github.io/arduino-lint/latest/installation/
or adding a GitHub Actions workflow to your repository to automatically run it every time you push a commit or get a pull request in the library:
https://github.com/arduino/arduino-lint-action#usage

**Comment by tig** [comment]
@arduinobot - new version posted.

**Comment by per1234** [comment]
Hello again @tig. There is an automated indexer job which does the following:

1. Checks every repository in the Library Manager list for new tags
1. Checks whether those new tags meet the requirements for addition to the index, publishing logs (e.g., http://downloads.arduino.cc/libraries/logs/github.com/tig/FlashStringTable/)
1. Adds compliant tags to the Library Manager index.

So once the library has been accepted, everything happens automagically so long as you make sure that your releases are compliant with the requirements listed [here](https://github.com/arduino/library-registry/blob/main/FAQ.md#what-are-the-requirements-for-publishing-new-releases-of-libraries-already-in-the-library-manager-list). So there is no need for you to take any special action to notify the bot that you made a new release.

**Pull request merged**
