### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by Jeroen88**

### CODE REVIEW

**Comment by Jeroen88** [comment]
@ArduinoBot

**Comment by Jeroen88** [comment]
@ArduinoBot

**Comment by per1234** [comment]
Hello @Jeroen88. The automated system here only operates on open pull requests. Since your submission was already accepted and the pull request merged, the bot won't pay any more attention to this pull request.

But this human is happy to provide assistance. Was there something you needed from the bot?

**Comment by Jeroen88** [comment]
Hi @per1234, so nice that not only bots are watching! Thank you for you reaction! I released a new version of my updated EasyOpenTherm Arduino library and thought that I should send the above comment. But from your reaction I do understand this is not needed? If I update the version in the library.properties file and push a new version to my Github main this is automatically seen by the bot? The active version should now be 1.1.0, could you confirm that? :)

**Comment by per1234** [comment]
>from your reaction I do understand this is not needed? If I update the version in the library.properties file and push a new version to my Github main this is automatically seen by the bot?

That is correct. There is some information on publishing new releases here:

https://github.com/arduino/library-registry/blob/main/FAQ.md#how-can-i-publish-a-new-release-once-my-library-is-in-the-list

The repositories are checked hourly, but since the Library Manager index is cached we give a conservative estimate of the release being available to all users everywhere within a day's time. When that doesn't happen, it is nearly always because the release was found to be non-compliant with [the requirements](https://github.com/arduino/library-registry/blob/main/FAQ.md#what-are-the-requirements-for-publishing-new-releases-of-libraries-already-in-the-library-manager-list). You can monitor the indexing at the dedicated logs web page for your library:

http://downloads.arduino.cc/libraries/logs/github.com/Jeroen88/EasyOpenTherm/

>The active version should now be 1.1.0, could you confirm that? 

I confirm:

Screenshot from 2022-12-27 11-51-02

**Comment by Jeroen88** [comment]
@per1234 thank you so much, also for the links with information about releases. I was not aware of the automatic update of a new release. I will keep that in mind for the next release. Have a nice day!

**Pull request merged**
