### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by Lzw655**
I previously uploaded two libraries, [ESP32_Display_Panel ](https://github.com/Lzw655/ESP32_Display_Panel)and [ESP32_IO_Expander](https://github.com/Lzw655/ESP32_IO_Expander), under my personal account. Now, I would like to upload them through the official Espressif account ([ESP Arduino Libs](https://github.com/esp-arduino-libs)) and also remove the library [esp-io-expander](https://github.com/esp-arduino-libs/esp-io-expander) that was just uploaded.

### CODE REVIEW

**Review by per1234 — CHANGES_REQUESTED** [review]
> I previously uploaded two libraries, [ESP32_Display_Panel ](https://github.com/Lzw655/ESP32_Display_Panel)and [ESP32_IO_Expander](https://github.com/Lzw655/ESP32_IO_Expander), under my personal account. Now, I would like to upload them through the official Espressif account

Hello @Lzw655. The appropriate way to do this is via the URL change procedure, which is documented here:

https://github.com/arduino/library-registry/tree/main#changing-the-url-of-a-library-already-in-library-manager

That will be more efficient than removing the registrations and then submitting them all over again.

Please let me know if you have any questions or concerns regarding that procedure.

**Review by per1234 — COMMENTED** [review]
> remove the library [esp-io-expander](https://github.com/esp-arduino-libs/esp-io-expander)

I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will merge this pull request when it is done. You will get a notification from GitHub at that time.

**Comment by Lzw655** [comment]
@per1234 Thanks for your reminder! It sounds like a better way via the URL change procedure. But I'm concerned about version issues. For example, if the latest release version of the library before modification is 1.1.1, and the version of the modified library is 0.0.1, what will be the final release version in Arduino? I don't want to retain the version before the modification.

**Review by per1234 — COMMENTED** [review]
> the latest release version of the library before modification is 1.1.1, and the version of the modified library is 0.0.1

Ewwwwwwwwwwwwwwwwwwwwwww. I makes me physically ill to contemplate managing a released project in that way. But since we haven't established rules requiring responsible practices from the library maintainers I guess I must hold my nose and accommodate your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will merge this pull request when it is done. You will get a notification from GitHub at that time.

**Comment by Lzw655** [comment]
I'm sorry for causing you any inconvenience. I'll be more careful in the future when creating and uploading libraries.

**Review by MatteoPologruto — APPROVED** [review]
Done:
```
2023/09/27 15:23:14 Loaded 6207 libraries from DB
Removing esp-io-expander
Success!
```
Done:
```
2023/09/27 15:20:47 Loaded 6209 libraries from DB
Removing ESP32_IO_Expander
Success!
```
Done:
```
2023/09/27 15:21:58 Loaded 6208 libraries from DB
Removing ESP32_Display_Panel
Success!
```

**Pull request merged**
