### PR TITLE
Add TinyGPSPlus

### PR DESCRIPTION
**Pull request by santaimpersonator**
Link in the TinyGPSPlus library: https://github.com/mikalhart/TinyGPSPlus

### CODE REVIEW

**Comment by per1234** [comment]
I'll add a note to myself here:

This is in progress but will require two things to happen in the library repository:

1. Merge of https://github.com/mikalhart/TinyGPSPlus/pull/92
2. Release of the library containing the name change provided by https://github.com/mikalhart/TinyGPSPlus/pull/92

Once those are done, the bot can be triggered again and the submission should be accepted.

**Comment by santaimpersonator** [comment]
Desired library name is taken: https://github.com/mikalhart/TinyGPSPlus/pull/92#issuecomment-1005408105

Closing this pull request until an new library name is decided on or owner of the forked library can be reached.

**Comment by santaimpersonator** [comment]
Reopening pull request in regards to checklist: https://github.com/mikalhart/TinyGPSPlus/issues/85#issuecomment-1008245696

**Comment by santaimpersonator** [comment]
Oops, jumped the gun on reopening the pull request. Need to wait for https://github.com/arduino/library-registry/pull/878 and https://github.com/mikalhart/TinyGPSPlus/pull/92 to be merged.

**Comment by santaimpersonator** [comment]
@ArduinoBot - Retry check

**Pull request merged**
