### PR TITLE
Update name of "I2CHelper"

### PR DESCRIPTION
**Pull request by per1234**
Resolves https://github.com/arduino/library-registry/issues/346

### CODE REVIEW

**Comment by Basirk** [comment]
May I ask when this change is likely to be merged please?

**Comment by per1234** [comment]
Hi @Basirk. I don't have an answer for "when", but I can provide some information about "why": The reason this pull request hasn't been merged yet is because the equivalent changes must first be made to the Library Manager index database. It wouldn't do any good to make the change I proposed here by itself. As soon as the maintainer of the index database has time to handle the request, they will merge this pull request and you'll get a notification from GitHub at that time.

**Comment by Basirk** [comment]
Thanks for the quick response and explanation  :)

**Comment by Basirk** [comment]
Really not wanting to be one of those unreasonable, pushy people who expects instant results from volunteers, but it's been over a month since this request was made. If you let me know the DB schema then I'll help with the UPDATE query  ;p

**Comment by per1234** [comment]
Hi @Basirk. "Database" is maybe putting it a bit strongly. It's actually a JSON file. If you are curious, you can see the engine source code here:
https://github.com/arduino/libraries-repository-engine

As for the update command, it will look like this:
```
libraries-repository-engine remove "I2C Helper"
```
Because the name is the unique for the library, changing a library's name is actually done by removing the library completely from the database and then allowing the engine to reindex the library under the newly registered name on the next hourly run. The first step must be done by a maintainer who is able to do the removal, after which this pull request handles the second step of changing the registration data so that the engine will use the new name for the library.

**Review by rsora — APPROVED** [review]
Worker maintenance is done:
```
2021/09/23 17:44:40 Loaded 4225 libraries from DB
Removing I2C Helper
Success!
```

**Pull request merged**
