### PR TITLE
Update repositories.txt remove EdgieD forever

### PR DESCRIPTION
**Pull request by crunchysteve**
The library submission process makes no sense to me at all. I quit. This is one of the reasons I moved to PlatformIO, adding libraries is on a project-by-project basis, where you simply add a link to a git repo in the project's platformio.ini file. Even version 2 of Arduino IDE is outdated rubbish.

### CODE REVIEW

**Review by per1234 — COMMENTED** [review]
@crunchysteve thousands of other library authors have no problem using this system. The system is quite straightforward and well documented. Did you take the time to read the documentation? I offered to provide assistance. All you have to do is ask if there is anything that is unclear.

Versioning via Git tags is a standard practice in any high quality software development work. So this is not something specific to the Arduino Library Manager system. It is well worth learning how to correctly use Git tags.

**Comment by crunchysteve** [comment]
I am in the process of learning this stuff, at a stage where what seemed easy is now mind bendingly obtuse to me. I'll get there, but I don't do this for a living, I did the library for the community, as well as for a couple of my projects. It frustrates me that there's so much backend to learn, and I've started really late because I never had opportunities to do this as a hobby or professionally when I was younger. I'm frustrated with the process, because, while I've picked up C and C++ quickly, thanks to Arduino, the environments around it are deeply and deceptively complex. I have maybe 3 months of using git daily as a tool, not just as a filestore. That's where my frustration comes from.

And yes, I've read the instructions every which way and, that they make no sense to me, is down to me and the learning I still have to do. I'm autistic and not an instructable learner. I have to figure stuff out for myself. Hence my exasperation.

**Comment by per1234** [comment]
I'll provide detailed instructions you can follow to successfully achieve a release to Library Manager:

1. Change the `name` field of your `library.properties` file from [the current value](https://github.com/crunchysteve/EdgieD/blob/2ef7c58052ed302b05d2e66490f8f13e4c7ec688/library.properties#L1):
   ```text
   name=EdgieD 1.0.0
   ```
   back to the name the library had when it was registered:
   ```text
   name=EdgieD
   ```
1. Commit that change to the GitHub repository.
1. Change the `version` field of your `library.properties` file from [the current value](https://github.com/crunchysteve/EdgieD/blob/2ef7c58052ed302b05d2e66490f8f13e4c7ec688/library.properties#L2):
   ```text
   version=1.0.0
   ```
   to the next version number in the sequence:
   ```text
   version=1.0.1
   ```
1. Commit that change to the GitHub repository.
1. Click the following link to open the GitHub release creation page for your repository:
   https://github.com/crunchysteve/EdgieD/releases/new
1. Click the "**Choose a tag ▼**" menu on the release creation page:
   image
   The "**Choose a tag**" menu will open.
1. Type `1.0.1` into the "**Find or create a new tag**" field of that menu:
   image
1. You will now see a "**+ Create new tag: 1.0.1 on publish**" item in the menu, click on that menu item:
   image
   The menu will close.
1. Type `1.0.1` into the "**Release title**" field on that page:
   image
1. Click the "**Publish release**" button at the bottom of the page:
   image

If everything was done correctly, you should now be taken to the GitHub page for the 1.0.1 release of your repository.

Contratulations! You have now successfully made a new release of your library. After the initial addition of the library, the indexer job periodically checks each of the libraries in the index and picks up any new release/tag that meets the requirements listed here:

https://github.com/arduino/library-registry/blob/main/FAQ.md#what-are-the-requirements-for-publishing-new-releases-of-libraries-already-in-the-library-manager-list

This means there is no need to take any additional action to add the new release of your library to Library Manager. It will be added automagically!

It does take a little time for the indexer job to run, and then some additional time after that for the update to propagate through the CDN and the local cache. But it will get there. We give a conservative estimate of availability within one day's time.

You can monitor the indexing of the library releases by checking the library's dedicated indexer logs web page:
http://downloads.arduino.cc/libraries/logs/github.com/crunchysteve/EdgieD/

---

Please let me know if you have any questions or problems while following those instructions.

**Comment by crunchysteve** [comment]
Thanks Per! The new version is live! I literally could not have done it
without your help!

Cheers,
Crunchy

**Comment by per1234** [comment]
You are welcome. I'm glad it is working now.

Regards,
Per

**Pull request closed without merging**
