### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by stoneroweast**

### CODE REVIEW

**Comment by per1234** [comment]
| @stoneroweast |
| :-: |
| :exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation: |
| :exclamation::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::exclamation: |
| :exclamation::warning:  **PLEASE READ THIS IMPORTANT INFORMATION**  :warning::exclamation: |
| :exclamation::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::exclamation: |
| :exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation: |
| @stoneroweast |

@stoneroweast please stop spamming our repository with pointless pull requests. If you continue doing this I will be forced to report you to GitHub.

If you will provide a detailed description of what you are trying to accomplish, I will be happy to help you out with that. You just need to make the effort to communicate with me.

**Comment by stoneroweast** [comment]
I'm really sorry... I'm really newbie, I'm trying to solve the problem, how to do reviews with access write...

**Comment by stoneroweast** [comment]
@per1234

**Comment by per1234** [comment]
Hi @stoneroweast.

> I'm trying to solve the problem

I'll be happy to help you with that. But I need to understand what the problem is. Please provide a detailed description of the problem.

- What did you do?
- What were the results you expected from doing that?
- What were the results you observed that did not match your expectations?
  - Make sure to include the full and exact text of any error or warning message you might have encountered.

>how to do reviews with access write

I'm not sure I understood correctly what you mean by "reviews with access write". Please provide a more detailed description to help me to understand it.

**Comment by stoneroweast** [comment]
Hi @per1234 

Thank you for responding and offering  help, I really appreciate it..

**"What did you do?"** 
My goal is to learn how to put my library in the Arduino Library Manager. I started by learning Git. After feeling enough with the basic knowledge, I started forking the Arduino library-registry, added my library repository to repositories.txt then made a pull request.


**"What were the results you expected from doing that?"**
**"What were the results you observed that did not match your expectations?"**

image



I learned how to solve these needs by taking various actions. every time I do one action and that error message appears I immediately close the pull request. perform another action and return to performing a pull request. i did this several times trying various actions that came across. try and error. I didn't expect that my action would be spam. I apologize for the inconvenience caused.
So can you tell me how to solve the problem. Thank you

**Comment by per1234** [comment]
> image

That "Review required" notice only means that we have configured this repository so that a maintainer must review and approve each pull request before merging it. This is normal and expected. The red "**X**" symbol might give the impression the notice is an indication something is wrong, but it is not. The notice is only indicating that additional action is needed before the pull request is ready to be merged. Unfortunately this notice comes from GitHub and so there is no way we can adjust its appearance or wording to more effectively communicate to the contributor.

> I learned how to solve these needs by taking various actions. every time I do one action and that error message appears I immediately close the pull request. perform another action and return to performing a pull request. i did this several times trying various actions that came across. try and error.

I understand. Trial and error is a fairly reasonable approach when working with an automated system. This repository is specifically set up to allow the library maintainer to work with the bot to iterate through problems and finally achieve a successful submission. However, this repository is only semi-automated. Library submissions are automated, but other requests must be handled manually. So a human (me) monitors every pull request. This means that a human is ready to provide assistance when people are having problems, but I can only do that if the contributor communicates what they are attempting to accomplish and what problems or questions they have.

So in the future when you are submitting pull requests or issues, just keep in mind that even though you are working with a computer system, there is a real human somewhere on the other end of that wire. It is very much worth the effort to take a little extra time to clearly communicate your intent in a way a human can understand. Instead of using the automatic "Update \_\_\_" title, write a concise yet descriptive commit and pull request title. Add a more detailed description of what you are proposing and why you are proposing it in the commit and pull request description. If there is a problem or uncertainty with the pull request, you can add a comment describing the problem or question and one of the project maintainers will probably respond.

> So can you tell me how to solve the problem. 

There is nothing you can do. This notification means action is needed from one of the maintainers of the repository. In the case of a library submission, the bot does the review and approves and merges the pull request automatically if it is found to meet all the requirements. If the bot detects a problem, it comments to explain what needs to be done. You can see here where that happened in one of your previous pull requests:

https://github.com/arduino/library-registry/pull/2393#issuecomment-1396381615

> A problem was found with your submission https://github.com/stoneroweast/HoldButton
>
> :x: **ERROR:** The repository has no tags. You need to create a [release](https://docs.github.com/en/github/administering-a-repository/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in the library's library.properties file.

> Thanks for your interest in contributing to the Arduino Library Manager index @stoneroweast
Please resolve the error(s) mentioned in the previous comment.
>
>After resolving the issue, trigger this check again by doing one of the following:
>
>- **Commit the required change to the branch you submitted this pull request from.**
>- **Comment here, mentioning `@ArduinoBot` in the comment.**
>
>:exclamation: **NOTE**: It is not necessary to open a new pull request. :exclamation:
>
>More information:
>https://github.com/arduino/library-registry/blob/main/README.md#if-the-problem-is-with-the-pull-request

But in the end you did fix that problem and your **HoldButton** library has been added to the Arduino Library Manager:

https://github.com/arduino/library-registry/pull/2399#issuecomment-1398001948

> Your submission has now been accepted! Thanks for your contribution to the Arduino Library Manager index.
>
>The library(s) will be available for installation via Library Manager within a day's time.
>
>You can check the logs from the Library Manager indexer for your library(s) here:
http://downloads.arduino.cc/libraries/logs/github.com/stoneroweast/HoldButton/

image

So you have accomplished your goal and no further action is needed. Congratulations and thanks for your contribution to the Arduino project!

**Comment by stoneroweast** [comment]
Hi @per1234 
Really great experience for me... thank you for sharing knowledge and help!

**Comment by per1234** [comment]
You are welcome. I'm glad if I was able to be of assistance.

Regards,
Per

**Pull request closed without merging**
