### PR TITLE
Create UART for ESP8266

### PR DESCRIPTION
**Pull request by MYBOTIC**
@ArduinoBot

### CODE REVIEW

**Comment by per1234** [comment]
Hello @MYBOTIC. Thanks for your interest in contributing to the Arduino Library Manager index.

I see you already submitted this library in July https://github.com/arduino/library-registry/pull/1659

So I will close this as a duplicate.

If you were trying to accomplish something other than a submission, please comment here with a detailed description and I will help you out.

Regards, Per

**Comment by MYBOTIC** [comment]
> Hello @MYBOTIC. Thanks for your interest in contributing to the Arduino Library Manager index.
> 
> I see you already submitted this library in July #1659
> 
> So I will close this as a duplicate.
> 
> If you were trying to accomplish something other than a submission, please comment here with a detailed description and I will help you out.
> 
> Regards, Per

Hi, Per,

There have some changing in the library and i wish to make it available to install the new version in arduino library manager.
Please advice.

Thanks and have a nice day,

Best Regards,
MYBOTIC

**Comment by per1234** [comment]
Thanks for the clarification @MYBOTIC. After the initial addition of the library, the indexer job periodically checks each of the libraries in the index and picks up any new release/tag that meets the requirements listed here:

https://github.com/arduino/library-registry/blob/main/FAQ.md#what-are-the-requirements-for-publishing-new-releases-of-libraries-already-in-the-library-manager-list

This means there is no need to take any additional action to add new releases of your library to Library Manager. They will be added automagically!

It does take a little time for the indexer job to run, and then some additional time after that for the update to propagate through the CDN and the local cache. But it will get there. We give a conservative estimate of availability within one day's time.

You can monitor the indexing of the library releases by checking the library's dedicated indexer logs web page:

http://downloads.arduino.cc/libraries/logs/github.com/MYBOTIC/DurianBlynkESP8266/

I can see from looking at those logs that the latest release was rejected as non-compliant due to the change of the `name` property value in the library's `library.properties` file:

https://github.com/MYBOTIC/DurianBlynkESP8266/commit/d4bd8a4a20ef1f929cf31be093d04acd8af2a0c5

**Comment by MYBOTIC** [comment]
> Thanks for the clarification @MYBOTIC. After the initial addition of the library, the indexer job periodically checks each of the libraries in the index and picks up any new release/tag that meets the requirements listed here:
> 
> https://github.com/arduino/library-registry/blob/main/FAQ.md#what-are-the-requirements-for-publishing-new-releases-of-libraries-already-in-the-library-manager-list
> 
> This means there is no need to take any additional action to add new releases of your library to Library Manager. They will be added automagically!
> 
> It does take a little time for the indexer job to run, and then some additional time after that for the update to propagate through the CDN and the local cache. But it will get there. We give a conservative estimate of availability within one day's time.
> 
> You can monitor the indexing of the library releases by checking the library's dedicated indexer logs web page:
> 
> http://downloads.arduino.cc/libraries/logs/github.com/MYBOTIC/DurianBlynkESP8266/
> 
> I can see from looking at those logs that the latest release was rejected as non-compliant due to the change of the `name` property value in the library's `library.properties` file:
> 
> [MYBOTIC/DurianBlynkESP8266@d4bd8a4](https://github.com/MYBOTIC/DurianBlynkESP8266/commit/d4bd8a4a20ef1f929cf31be093d04acd8af2a0c5)

Hi, Per,

Thanks for information, so i just changing the name in the library.properties` file. after that, it will auto update inside the library manager in arduino side? Am I right?

**Comment by per1234** [comment]
You need to do three things, in this order:

1. Change the name back to `Mybotic Durian Blynk ESP8266`
1. Update the `version` value in the `library.properties` file: https://github.com/MYBOTIC/DurianBlynkESP8266/blob/main/library.properties#L2
1. Create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.

I see you have already done (1) in https://github.com/MYBOTIC/DurianBlynkESP8266/commit/1089f614fae577a583a5da55582be01ef2627a57

**Comment by MYBOTIC** [comment]
> You need to do three things, in this order:
> 
> 1. Change the name back to `Mybotic Durian Blynk ESP8266`
> 2. Update the `version` value in the `library.properties` file: https://github.com/MYBOTIC/DurianBlynkESP8266/blob/main/library.properties#L2
> 3. Create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.
> 
> I see you have already done (1) in [MYBOTIC/DurianBlynkESP8266@1089f61](https://github.com/MYBOTIC/DurianBlynkESP8266/commit/1089f614fae577a583a5da55582be01ef2627a57)

Thanks for help, I done all, let see the changing tomorrow. Thank a lot

**Comment by MYBOTIC** [comment]
Hi, per1234

I have make some changing in the library, i wish to make it available to install the new version in Arduino Library Manager.
How should I do?

Best Regards,
MYBOTIC

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by per1234** [comment]
Hello @MYBOTIC. Please see the information provided here:

https://github.com/arduino/library-registry/blob/main/FAQ.md#how-can-i-publish-a-new-release-once-my-library-is-in-the-list

If you have any questions or problems, let me know and I'll help you out.

**Pull request closed without merging**
