### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by kolabse**

### CODE REVIEW

**Comment by per1234** [comment]
Hello @kolabse. I see you have fixed the error reported by the bot. However, Library Manager works exclusively from Git tags, so the bot won't be able to see the fix you made until you create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.

You can see here that at the tagged version of the library the submission system looks at, the `library.properties` file was still missing:

https://github.com/autowp/arduino-mcp2515/tree/v1.0.1

Remember to update the `version` field in the library's [`library.properties` file](https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format) as needed before making a release/tag.

Once you have done that, simply mention **@ArduinoBot** in a comment here to trigger it to run the automated checks again. After those are passing, your library will automatically be added to Library Manager.

**Comment by kolabse** [comment]
@ArduinoBot

**Comment by per1234** [comment]
For my own future reference, I'll add a note about the status of this submission.

Work is in progress to resolve the non-compliance reported by the bot. The following will need to be done:

1. Update library name by merging https://github.com/autowp/arduino-mcp2515/pull/72
2. Create a new release/tag of the library that contains the name change

**Comment by kolabse** [comment]
@ArduinoBot

**Pull request merged**
