### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by CDTParaguana**

### CODE REVIEW

**Comment by CDTParaguana** [comment]
@ArduinoBot  Done

**Comment by CDTParaguana** [comment]
@ArduinoBot

**Comment by CDTParaguana** [comment]
@ArduinoBot

**Comment by CDTParaguana** [comment]
@ArduinoBot Done

**Review by per1234 — COMMENTED** [review]
I'm going to close this because the library is not in a state where it can be submitted to Arduino Library Manager.

I recommend you to spend the time to carefully read and understand the Arduino Library Specification:

https://arduino.github.io/arduino-cli/latest/library-specification/

If there is anything you don't understand or you have any questions, you can ask for assistance on Arduino Forum:

https://forum.arduino.cc/c/international/espanol/software/126

We'll be happy to help you out over there.

Once the library is fully specification compliant, you can open another pull request here to submit it to Library Manager.

**Pull request closed without merging**
