### PR TITLE
Added helper library for the Bee S3 board

### PR DESCRIPTION
**Pull request by strid3r21**

### CODE REVIEW

**Comment by strid3r21** [comment]
@ArduinoBot

**Comment by strid3r21** [comment]
@ArduinoBot trying this again lol

**Comment by strid3r21** [comment]
@ArduinoBot one more time please. i think i got it fixed. fingers crossed.

**Comment by strid3r21** [comment]
@ArduinoBot

**Comment by per1234** [comment]
Hi @strid3r21. Thanks for your interest in contributing to the Arduino Library Manager index!

The reason for the error reported by the bot is that the source folder of your library is named `scr`, while the required folder name is `src` (note the transposition of the last two letters):

https://github.com/strid3r21/BeeS3-Arduino-Helper/tree/1.0.3/scr

If you rename the folder, then just make sure to create a new tag or release in your repository with the library in the valid state, then trigger the bot to check it again.

Please let me know if you have any questions or problems.

Regards, Per

**Comment by strid3r21** [comment]
> Hi @strid3r21. Thanks for your interest in contributing to the Arduino Library Manager index!
> 
> The reason for the error reported by the bot is that the source folder of your library is named `scr`, while the required folder name is `src` (note the transposition of the last two letters):
> 
> https://github.com/strid3r21/BeeS3-Arduino-Helper/tree/1.0.3/scr
> 
> If you rename the folder, then just make sure to create a new tag or release in your repository with the library in the valid state, then trigger the bot to check it again.
> 
> Please let me know if you have any questions or problems.
> 
> Regards, Per

omg, im an idiot lol. thanks for pointing that out. i fixed it. @ArduinoBot

**Comment by strid3r21** [comment]
@ArduinoBot

**Pull request merged**
