### PR TITLE
Initial Official wolfSSL Arduino Library

### PR DESCRIPTION
**Pull request by gojimmypi**
# Add Official wolfSSL Arduino Library

As noted in:

- https://github.com/wolfSSL/Arduino-wolfSSL/pull/1 
- https://github.com/onelife/Arduino_wolfssl/issues/3
- https://github.com/platformio/platformio-registry/issues/85
- Arduino support ticket #282646

This PR [replaces](https://github.com/arduino/library-registry?tab=readme-ov-file#changing-the-url-of-a-library-already-in-library-manager) the current `onelife/Arduino_wolfssl` with the Official [wolfSSL](https://www.wolfssl.com/) repository at:

https://github.com/wolfSSL/Arduino-wolfSSL

The existing URL is intentionally being changed.

# About

The wolfSSL library is a small, fast, portable implementation of TLS/SSL for embedded devices to the cloud. wolfSSL supports up to TLS 1.3!

# License

Dual Commercial or GPLv2

https://github.com/wolfSSL/wolfssl?tab=GPL-2.0-1-ov-file#readme

# Support

See https://www.wolfssl.com/products/support-and-maintenance/

### How to Create a Support Ticket or Forum Post

wolfSSL maintains two support channels: a public support forum and a support ticket system. The wolfSSL ticket system should be used when looking for the fastest response time. Sending an email to support@wolfssl.com will automatically generate a new support ticket. The public wolfSSL forums are also available, and are a great place to search for existing issues.

- wolfSSL Support Forums:  https://www.wolfssl.com/forums
- wolfSSL Support Ticket System:  https://wolfssl.zendesk.com/hc/en-us/requests/new

### Support and Maintenance Packages

Support packages and maintenance for wolfSSL products including the wolfSSL embedded SSL/TLS library, wolfCrypt embedded crypto engine, wolfSSH SSHv2 Server library, and more are available directly from wolfSSL on a yearly basis. The comparison matrix below outlines differences in package features and prices.

For more information, or to visit with a wolfSSL representative, please [Contact Us](https://www.wolfssl.com/contact/)

#### General product questions, FIPS, porting, etc.

Email: facts@wolfssl.com

Phone: +1 (425) 245-8247

#### Licensing Questions

Open source or Commercial license questions or inquiries.

Email: licensing@wolfssl.com

#### Technical Support

Technical support for wolfSSL products.

Email: support@wolfssl.com

### CODE REVIEW

**Comment by gojimmypi** [comment]
I've applied update to rename the library to (all lower case) `wolfssl` as noted in https://github.com/wolfSSL/Arduino-wolfSSL/pull/3

@ArduinoBot

**Comment by gojimmypi** [comment]
I've refreshed the `5.6.6-Arduino.1` release https://github.com/wolfSSL/Arduino-wolfSSL/releases/tag/5.6.6-Arduino.1 

@ArduinoBot

**Review by per1234 — COMMENTED** [review]
Hello @gojimmypi. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will merge this pull request when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Review by MatteoPologruto — APPROVED** [review]
Done:
```
2024/02/21 16:04:51 Loaded 6679 libraries from DB
Changing URL of library wolfssl from https://github.com/onelife/Arduino_wolfssl.git to https://github.com/wolfSSL/Arduino-wolfSSL.git
Success!
```

**Pull request merged**
