### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by InfiniteCoder01**

### CODE REVIEW

**Comment by per1234** [comment]
Hello @InfiniteCoder01. Thanks for your interest in contributing to the Arduino Library Manager index!

I see the bot reported a problem with your submission that will block its acceptance:

> :x: **ERROR:** The repository has no tags. You need to create a [release](https://docs.github.com/en/github/administering-a-repository/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in the library's library.properties file.

If you have any questions or problems while following the instructions to resolve the problem, please let me know and I'll help out.

If you decide you no longer wish to submit the library, you can close this pull request.

**Comment by InfiniteCoder01** [comment]
Fixed

**Comment by per1234** [comment]
Hello @InfiniteCoder01. I see the repository still does not have any tags or releases:

https://github.com/InfiniteCoder01/BufferedOreonSSD1351/tags

Did you maybe forget to push the tag from your local clone of the repository to GitHub?

**Comment by InfiniteCoder01** [comment]
Fixed now

**Comment by per1234** [comment]
@ArduinoBot please check it again.

**Pull request merged**
