### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by shubhamtrivedi95**

### CODE REVIEW

**Comment by shubhamtrivedi95** [comment]
@per1234 Can you help me resolve this issue.

**Comment by per1234** [comment]
Hi @shubhamtrivedi95. The reason for the error is because we only started the process of removing the library, but had not completed it. I have put the removal process on hold, but there is still one more thing you must do, which I explained here:
https://github.com/shubhamtrivedi95/UltraDistSensor/issues/1#issuecomment-886797986

Please let me know if you have any questions or concerns.
Regards, Per

**Comment by shubhamtrivedi95** [comment]
@per1234 I just deleted 1.0 tag.

**Comment by per1234** [comment]
I can still see it:
https://github.com/shubhamtrivedi95/UltraDistSensor/releases/tag/1.0
did you delete it via the GitHub Web interface according to my instructions at https://github.com/shubhamtrivedi95/UltraDistSensor/issues/1#issuecomment-886797986, or did you use Git directly?

**Review by per1234 — APPROVED** [review]

**Comment by per1234** [comment]
OK, now it's gone. The 1.0 version of the library will be removed from Library Manager, but the library will still be available in Library Manager from the 1.1 version onward.

Thanks @shubhamtrivedi95!

**Comment by shubhamtrivedi95** [comment]
Thanks @per1234

**Pull request merged**
