### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by alexitoo00**

### CODE REVIEW

**Comment by alexitoo00** [comment]
@ArduinoBot

**Comment by per1234** [comment]
Hello @alexitoo00. The automated system here only operates on open pull requests. Since your submission was already accepted and the pull request merged, the bot won't pay any more attention to this pull request.

But this human is happy to provide assistance. Was there something you needed from the bot?

**Comment by alexitoo00** [comment]
The log page throws error 404 https://downloads.arduino.cc/libraries/logs/github.com/alexitoo00/NewEncoder/

**Comment by per1234** [comment]
Please check it again. The job that generates the page only runs once an hour so it can be up to an hour between the time when your submission is accepted and when the logs page is available.

**Comment by alexitoo00** [comment]
Oh ok, thank you very much. This was my first contribution to the arduino community and I was a little nervous. Thanks again. Have a good night

**Pull request merged**
