### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by Dhanabhon**

### CODE REVIEW

**Comment by Dhanabhon** [comment]
@ArduinoBot

**Comment by Dhanabhon** [comment]
> Thanks for your interest in contributing to the Arduino Library Manager index @Dhanabhon Please resolve the error(s) mentioned in the previous comment.
> 
> After resolving the issue, trigger this check again by doing one of the following:
> 
> * **Commit the required change to the branch you submitted this pull request from.**
> * **Comment here, mentioning `@ArduinoBot` in the comment.**
> 
> ❗ **NOTE**: It is not necessary to open a new pull request. ❗
> 
> More information: https://github.com/arduino/library-registry/blob/main/README.md#if-the-problem-is-with-the-pull-request

@ArduinoBot

**Review by per1234 — COMMENTED** [review]
Hello @Dhanabhon. I see you have fixed the error reported by the bot. However, Library Manager works exclusively from Git tags, so the bot won't be able to see the fix you made until you create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.

If you look at the repository contents at the latest tag, you can see that the version the bot is checking still has the problem:

https://github.com/Dhanabhon/TomIBT2/tree/v1.0.0

❗ Remember to update the `version` field in the library's [`library.properties` file](https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format) as needed before making a release/tag.

Once you have done that, simply mention **@ArduinoBot** in a comment here to trigger it to run the automated checks again. After those are passing, your library will automatically be added to Library Manager.

If you have any questions or concerns, please let me know.

Regards, Per

**Comment by Dhanabhon** [comment]
> Library is missing a library.properties metadata file.

@ArduinoBot

**Comment by Dhanabhon** [comment]
> A problem was found with your submission https://github.com/Dhanabhon/TomIBT2
> 
> ❌ **ERROR:** Library is missing a library.properties metadata file.
> 
> See: https://arduino.github.io/arduino-cli/latest/library-specification/#library-metadata

@ArduinoBot

**Comment by Dhanabhon** [comment]
> 

@ArduinoBot

**Comment by Dhanabhon** [comment]
> Thanks for your interest in contributing to the Arduino Library Manager index @Dhanabhon Please resolve the error(s) mentioned in the previous comment.
> 
> After resolving the issue, trigger this check again by doing one of the following:
> 
> * **Commit the required change to the branch you submitted this pull request from.**
> * **Comment here, mentioning `@ArduinoBot` in the comment.**
> 
> ❗ **NOTE**: It is not necessary to open a new pull request. ❗
> 
> More information: https://github.com/arduino/library-registry/blob/main/README.md#if-the-problem-is-with-the-pull-request

@ArduinoBot

**Comment by Dhanabhon** [comment]
@per1234 Hi, What happens to my request that "ERROR: Library is missing a library.properties metadata file." In the TomIBT repository already exist the library.properties file.

**Comment by per1234** [comment]
Hello @Dhanabhon. I see you have fixed the error reported by the bot. However, Library Manager works exclusively from Git tags, so the bot won't be able to see the fix you made until you create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.

If you look at the repository contents at the latest tag, you can see that the version the bot is checking still has the problem:

https://github.com/Dhanabhon/TomIBT2/tree/v1.0.0

❗ Remember to update the `version` field in the library's [`library.properties` file](https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format) as needed before making a release/tag.

Once you have done that, simply mention **@ArduinoBot** in a comment here to trigger it to run the automated checks again. After those are passing, your library will automatically be added to Library Manager.

If you have any questions or concerns, please let me know.

Regards, Per

**Comment by Dhanabhon** [comment]
> Thanks for your interest in contributing to the Arduino Library Manager index @Dhanabhon Please resolve the error(s) mentioned in the previous comment.
> 
> After resolving the issue, trigger this check again by doing one of the following:
> 
> * **Commit the required change to the branch you submitted this pull request from.**
> * **Comment here, mentioning `@ArduinoBot` in the comment.**
> 
> ❗ **NOTE**: It is not necessary to open a new pull request. ❗
> 
> More information: https://github.com/arduino/library-registry/blob/main/README.md#if-the-problem-is-with-the-pull-request

@ArduinoBot

**Comment by Dhanabhon** [comment]
> Hello @Dhanabhon. I see you have fixed the error reported by the bot. However, Library Manager works exclusively from Git tags, so the bot won't be able to see the fix you made until you create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.
> 
> If you look at the repository contents at the latest tag, you can see that the version the bot is checking still has the problem:
> 
> https://github.com/Dhanabhon/TomIBT2/tree/v1.0.0
> 
> ❗ Remember to update the `version` field in the library's [`library.properties` file](https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format) as needed before making a release/tag.
> 
> Once you have done that, simply mention **@ArduinoBot** in a comment here to trigger it to run the automated checks again. After those are passing, your library will automatically be added to Library Manager.
> 
> If you have any questions or concerns, please let me know.
> 
> Regards, Per

Thank you for your recommendation. The problem is solved by your recommendation.

**Pull request merged**
