### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by nthnn**
Changed my library URL, because it collides with https://github.com/Panjkrc/TCS3200_library

I've updated my library's name. My bad.

### CODE REVIEW

**Comment by nthnn** [comment]
@ArduinoBot

**Comment by nthnn** [comment]
@ArduinoBot

**Review by per1234 — COMMENTED** [review]
Hello @nthnn. I re-opened this pull request because we actually need to do two distinct maintenance operations here:

- Change URL from `https://github.com/nthnn/TCS3200.git` to `https://github.com/nthnn/TCS3200-Color-Sensor.git` (this PR)
- Change name from `TCS3200` to `TCS3200-Sensor` (your request issue https://github.com/arduino/library-registry/issues/3172)

I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will merge this pull request when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by nthnn** [comment]
@ArduinoBot

**Review by per1234 — COMMENTED** [review]
No longer needed because the repository name was changed back to TCS3200:

https://github.com/nthnn/TCS3200

**Pull request closed without merging**
