### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by xamrex**
Remove library.
It is not working for a while.
API for Instagram has changed.

More info on **ISSUES** librabry page:
https://github.com/witnessmenow/arduino-instagram-stats/issues

### CODE REVIEW

**Review by per1234 — COMMENTED** [review]
Hi @xamrex. Thanks for your interest in the quality of the Library Manager offerings.

We only remove libraries at the request of the library's maintainer. So I will not be able to accommodate your request without approval from @witnessmenow.

I will go ahead and close this pull request, but I welcome you to contact @witnessmenow and work with them either to resolve the issues with the library, or else to obtain approval for removal.

**Comment by witnessmenow** [comment]
I'm ok with this being removed @per1234. Thanks

**Review by per1234 — COMMENTED** [review]
Hello again @xamrex. Now that we have obtained approval from the library maintainer, I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will merge this pull request when it is done. You will get a notification from GitHub at that time.

**Review by MatteoPologruto — APPROVED** [review]
Done:
```
2024/06/13 15:18:34 Loaded 7061 libraries from DB
Removing InstagramStats
Success!
```

**Pull request merged**
