### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by Arathierl**
https://github.com/Arathierl/RobotControl.git add my library in library manager of arduino

### CODE REVIEW

**Review by per1234 — COMMENTED** [review]
| @Arathierl |
| :-: |
| :exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation: |
| :exclamation::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::exclamation: |
| :exclamation::warning:  **PLEASE READ THIS IMPORTANT INFORMATION**  :warning::exclamation: |
| :exclamation::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::exclamation: |
| :exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation: |
| @Arathierl |

**WARNING: I AM LOSING PATIENCE WITH YOU. IF YOU DON'T IMMEDIATELY START PAYING ATTENTION TO MY COMMENTS YOU WILL BE PERMANENTLY BANNED FROM ALL OF ARDUINO'S REPOSITORIES. THIS IS YOUR LAST WARNING**

Hello @Arathierl. I see you have fixed the error reported by the bot. However, Library Manager works exclusively from Git tags, so the bot won't be able to see the fix you made until you create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.

If you look at the repository contents at the latest tag, you can see that the version the bot is checking still has the problem:

https://github.com/Arathierl/RobotControl/tree/v1.0.0

(note that the repository did not contain a `library.properties` file at that point in the revision history)

❗ Remember to update the `version` field in the library's [`library.properties` file](https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format) as needed before making a release/tag.

Once you have done that, simply mention **@ArduinoBot** in a comment here to trigger it to run the automated checks again. After those are passing, your library will automatically be added to Library Manager.

If you have any questions or concerns, please let me know.

Regards, Per

**Comment by Arathierl** [comment]
add my library @ArduinoBot

**Review by per1234 — COMMENTED** [review]
Although creating Arduino projects is intended to be accessible to everyone, sharing libraries with the Arduino community via Library Manager is something that should only be done by experienced users who can produce a high quality library and effectively maintain it.

Your behavior in this repository indicates that you don't meet our standards for distributing libraries via the Arduino Library Manager system so I am closing this pull request. We will reject all further submissions from you so please don't attempt to submit it again.

Best wishes for your progress in Arduino development work.

**Comment by per1234** [comment]
Hello @vpBharath and @ErlTechnologies (the accounts that were created by @Arathierl to circumvent the decision I stated above). Due to you having established a pattern of irresponsible behavior in your activity in this repository, your Arduino Library Manager Registry privileges have been revoked:

- https://github.com/arduino/library-registry/pull/4841#pullrequestreview-2204070146
- https://github.com/arduino/library-registry/pull/4873#pullrequestreview-2204405304
- https://github.com/arduino/library-registry/pull/4873#pullrequestreview-2206235445
- https://github.com/arduino/library-registry/pull/4890
- https://github.com/arduino/library-registry/pull/4891
- https://github.com/arduino/library-registry/pull/4892
- https://github.com/arduino/library-registry/pull/4893#event-13706584557
- https://github.com/arduino/library-registry/pull/4894
- https://github.com/arduino/library-registry/pull/4908
- https://github.com/arduino/library-registry/pull/4910
- https://github.com/arduino/library-registry/pull/4911
- https://github.com/arduino/library-registry/issues/4912
- https://github.com/arduino/library-registry/pull/4913
- https://github.com/arduino/library-registry/pull/4914
- https://github.com/arduino/library-registry/pull/4942
- https://github.com/arduino/library-registry/pull/4944

We will not accept any further requests from you or for your libraries.

If you would like to request the restoration of your privileges, you can follow this procedure:

---

⚠ These instructions must be followed precisely and comprehensively. Any deviation from the instructions will result in the rejection of your request.

---

1. Open a new [issue](https://docs.github.com/issues/tracking-your-work-with-issues/about-issues) in this repository's issue tracker.
   The "**Create new issue**" dialog will open.
1. Select "**Blank issue**" from the dialog.
   The new issue composer page will open.
1. Give the issue a title with this exact format:
   ```text
   Registry privileges restoration request for <entity>
   ```
1. Replace the `<entity>` placeholder in the title with the name of the user or organization whose registry privileges you are requesting be restored.
1. Add the following template text to the description field of the issue:
   ```text
   ## Privileges revocation reference

   <revocation notification URL>
   ```
1. Replace the `<revocation notification URL>` placeholder in the description with the URL of this comment that provides notification of the revocation of registry privileges.
   **ⓘ** You can get the URL of the comment by clicking on the date stamp on the comment header.
1. Add the following template text to the description field of the issue:
   ```text
   ## Reason for privileges revocation

   <description>
   ```
1. Replace the `<description>` placeholder in the description with a detailed and clear description of the irresponsible behavior that resulting in the registry privileges being revoked. Include reference URLs for each of the irresponsible actions.
1. Add the following template text to the description field of the issue:
   ```text
   ## Behavioral modification pledge

   <description>
   ```
1. Replace the `<description>` placeholder in the description with a detailed and clear description of the changes you will make to your future activity if registry privileges are restored.
1. Carefully review the title and description to ensure you have followed these instructions exactly, that your request includes all relevant details, that your request is clearly written, and that your request does not contain any typographical errors.
1. Submit the issue.
1. Wait patiently for the repository maintainer to review your request.

**Pull request closed without merging**
