### PR TITLE
Added DCS-Skunkworks/dcs-bios-arduino-library

### PR DESCRIPTION
**Pull request by maciekish**

### CODE REVIEW

**Comment by maciekish** [comment]
@ArduinoBot

**Comment by per1234** [comment]
Hello @maciekish. The automated system here only operates on open pull requests. Since your submission was already accepted and the pull request merged, the bot won't pay any more attention to this pull request.

But this human is happy to provide assistance. Was there something you needed from the bot? Are you commenting in regards to the name change request you submitted earlier at https://github.com/arduino/library-registry/issues/5026?

**Comment by maciekish** [comment]
> Hello @maciekish. The automated system here only operates on open pull requests. Since your submission was already accepted and the pull request merged, the bot won't pay any more attention to this pull request.
> 
> 
> 
> But this human is happy to provide assistance. Was there something you needed from the bot? Are you commenting in regards to the name change request you submitted earlier at https://github.com/arduino/library-registry/issues/5026?

Hi, yes, i was hoping that maybe it would trigger an update.

**Comment by per1234** [comment]
>  i was hoping that maybe it would trigger an update.

It won't.

You don't need to do anything to trigger an update. [The indexer automatically checks your repository every hour.](https://github.com/arduino/library-registry/blob/main/FAQ.md#how-can-i-publish-a-new-release-once-my-library-is-in-the-list)

**Pull request merged**
