### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by dvarrel**
remove .git from my librairries. Hope pb with ESPAsynWebsrv resolved

### CODE REVIEW

**Comment by per1234** [comment]
Hi @dvarrel the Library Manager system accepts library repository URLs with or without the `.git` suffix.

You are welcome to remove the suffix from your library URLs if you like, but you stated the purpose of this PR is:

> Hope pb with ESPAsynWebsrv resolved

Doing this will never fix any problem, so there is no point in making this change for that purpose.

I am happy to help you to find a solution for the problem, but I can only do that if I understand what the problem is. Please provide a detailed description of the problem:

- What did you do?
- What were the results you expected from doing that?
- What were the results you observed that did not match your expectations?
  - Make sure to include the full and exact text of any error or warning message you might have encountered.

**Comment by dvarrel** [comment]
When i try to install , I see "Processing ESPAsyncWebsrv 1.2.5" and that's all, the installation fails.
Is there any log to see ?

**Comment by dvarrel** [comment]
i don't see AsyncTCP in the library manager, and ESPAsyncWebsrv depends on it.
that's a possible issue

**Comment by per1234** [comment]
> Is there any log to see ?

There are logs, but unfortunately they don't show this problem. However, you can see the bot tried to warn you about a problem when you submitted the library:

https://github.com/arduino/library-registry/pull/2235#issuecomment-1350620098

```text
WARNING: library.properties depends field item(s) AsyncTCP, ESPAsyncTCP not found in the Library Manager index.
         See: https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format
         (Rule LP048)         
```

> i don't see AsyncTCP in the library manager, and ESPAsyncWebsrv depends on it.
that's a possible issue

That is exactly it. The library installation fails because the library references a dependency that can not be installed:

https://github.com/dvarrel/ESPAsyncWebSrv/blob/1.2.5/library.properties#L10

```text
depends=AsyncTCP, ESPAsyncTCP
```

Unfortunately Arduino IDE 2.x does not communicate about the problem to the user, but instead silently fails the installation:

https://github.com/arduino/arduino-ide/issues/621

So there are two possible solutions to the problem:

## Remove the unavailable library from the `depends` field

The user is responsible for manually installing the **AsyncTCP** library dependency. I recommend providing detailed instructions for how to install that dependency in the library's readme.

You will need to make a new release of the **ESPAsyncWebSrv** library after fixing its metadata:

https://github.com/arduino/library-registry/blob/main/FAQ.md#how-can-i-publish-a-new-release-once-my-library-is-in-the-list

## Submit the missing dependency to Arduino Library Manager

Unfortunately the library author has not been responsive to requests to add these popular libraries to Arduino Library Manager:

https://github.com/me-no-dev/AsyncTCP/issues/147

Although anyone is welcome to submit any library, we are unable to submit that one because its repository doesn't have a tag.

You can fork the library and then submit the fork to Arduino Library Manager. I see you actually have already forked it and submitted that fork: https://github.com/arduino/library-registry/pull/2233
But you registered it under the name **ESP32AsyncTCP** instead of **AsyncTCP**. So maybe you referenced the wrong name in the `depends` field of the **ESPAsyncWebSrv** library???

**Comment by dvarrel** [comment]
library is in line 5459 in repositories.txt https://github.com/dvarrel/AsyncTCP.git
perhaps the name has change.
May i have to reove it and then submit ?

**Comment by per1234** [comment]
Please submit a name change request by following these instructions:

https://github.com/arduino/library-registry/blob/main/FAQ.md#how-can-i-change-a-librarys-name

I see the latest tag in the library repository already has the desired name:

https://github.com/dvarrel/AsyncTCP/blob/1.1.3/library.properties#L1

so you only need to submit the request and we'll take care of the rest.

**Pull request closed without merging**
