### PR TITLE
add glpi_esp8266

### PR DESCRIPTION
**Pull request by verdanatech-dev**

### CODE REVIEW

**Comment by verdanatech-dev** [comment]
@github-actions

**Comment by verdanatech-dev** [comment]
@ArduinoBot

**Comment by per1234** [comment]
Hello @verdanatech-dev. I see you have fixed the error reported by the bot. However, Library Manager works exclusively from Git tags, so the bot won't be able to see the fix you made until you create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository. You can see that at the last tag, the problem still existed:
https://github.com/verdanatech/glpi_esp8266/tree/refs/tags/0.0.1

Remember to update the `version` field in the library's [`library.properties` file](https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format) as needed before making a release/tag.

Once you have done that, simply mention **@ArduinoBot** in a comment here to trigger it to run the automated checks again. After those are passing, your library will automatically be added to Library Manager.

**Comment by verdanatech-dev** [comment]
@ArduinoBot

**Comment by verdanatech-dev** [comment]
@ArduinoBot

**Comment by per1234** [comment]
Hello @verdanatech-dev.

The automated system here only operates on open pull requests submissions. Since your submission was already accepted and the pull request merged, the bot won't pay any more attention to this pull request. But this human is happy to provide assistance. Was there something you needed from the bot?

**Pull request merged**
