### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by RLL-Blue-Dragon**
Rename

### CODE REVIEW

**Comment by per1234** [comment]
Hi @RLL-Blue-Dragon. We can still proceed with the URL change if you like.

The error reported by the bot is a separate issue from the new URL. It is caused by the change to the value of the `name` field in the `library.properties` file made here:

https://github.com/RLL-Blue-Dragon/OSS-EC_NXP_MPXA4250A_00000057/commit/2c92019f48638892998ddb2f305fc608af8ffe84

That error will prevent any releases of the library under that name from being added to Arduino Library Manager, but the previous releases will still be available.

If you would like to change the name, please follow the instructions here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#how-can-i-change-a-librarys-name

**Comment by per1234** [comment]
From your comment at https://github.com/arduino/library-registry/issues/1893#issuecomment-1253104861 I can see you still want to update the URL (which is the right thing to do so we aren't reliant on the redirect from the old repo URL). So I'll reopen this.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will merge this pull request when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by per1234** [comment]
Note to backend maintainer: the validation failure is expected, caused by the name change done at the same time as the URL change. That will be resolved by https://github.com/arduino/library-registry/pull/1886.

**Comment by umbynos** [comment]
Done:
```
2022/09/27 12:45:40 Loaded 5179 libraries from DB
Removing NXP_MPXA4250_BSL00000057
Success!
```

**Comment by RLL-Blue-Dragon** [comment]
Thank you!

**Pull request merged**
