### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by Youniesta**
Removing my library from Library Manager

### CODE REVIEW

**Review by per1234 — APPROVED** [review]

**Comment by per1234** [comment]
Hello @Youniesta. The requested change is now in progress.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests and closes the PRs when that is done. If you are subscribed to this PR, you'll get a notification at that time.

**Comment by per1234** [comment]
Library Manager works exclusively from Git [tags](https://git-scm.com/docs/git-tag). The tag is a marker at a specific time in the development history of the library. This is important because it allows the users of your library to track which versions their sketches or dependent libraries are compatible with, and to make controlled updates to new versions of the library, with the option to roll back to a previous version if necessary.

Your repository only contains a single tag, so this is why that is the only version available from Library Manager:

https://github.com/MakerLabCRI/Max86141/tags

When you are ready to publish a new version of your library, just do this:

1. Update the `version` value in `library.properties` to the version that will be used for the new release.
1. Create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.

The indexer system will pick up that new release and it will be available from Library Manager within a day.

Since it is now clear that you did not actually intend for the library to be permanently removed from Library Manager, I will close this PR.

Please let me know if you have any questions or concerns.
Regards, Per

**Comment by Youniesta** [comment]
Thank you for these informations, it is more clear now.
But when I look my library on Library Manager, I see 2 versions 1.0.0 and 1.0.1 while I just have version 1.0.0 on Github.
I don't understand why that.

**Comment by per1234** [comment]
For efficiency, all releases are cached by Arduino. A side effect of this is that the release will still be available from Library Manager even after you have deleted a tag from your repository. That is usually not a problem because deleting tags is not a common practice.

My recommendation is to simply create a new release with the next appropriate version in the series (e.g., `1.0.2` if there were no changes to the library API). Even though the 1.0.1 release will still be in Library Manager, it will only be installed if the user selects that specific version from the menu, since by default the latest version is selected.

In cases where a release absolutely does need to be taken down, there is a procedure available for requesting its removal from the Library Manager cache:

https://github.com/arduino/library-registry/blob/main/FAQ.md#how-can-i-remove-a-release-of-my-library-from-library-manager

**Comment by Youniesta** [comment]
Thank you ! I think I will take the first option which is to create a new release.

**Pull request closed without merging**
