### PR TITLE
Delete my library from library registery

### PR DESCRIPTION
**Pull request by SMotlaq**
I want to delete my library.

### CODE REVIEW

**Review by per1234 — COMMENTED** [review]
Hello @SMotlaq. Please provide a detailed explanation of why you want the library to be removed.

Please note that we only allow removals on a permanent basis.

Sometimes library maintainers will request a removal with the plans to submit the library once again immediately after as a hacky attempt to fix some problem they are having. The fact that you submitted this library only days ago (https://github.com/arduino/library-registry/pull/4396), and then attempted to submit it again redundantly only hours ago (https://github.com/arduino/library-registry/pull/4467) makes me suspect that you are up to some such shenanigans.

There are standard procedures for solving any possible problem with a library or Library Manager. It will be much more efficient for you and for the Library Manager registry maintainers both if you follow those procedures, and you will also avoid the chance of causing problems for the users of your library. I'm here to help you solve any problem you might have, but I can only do that if you make the effort to communicate with me.

**Comment by SMotlaq** [comment]
Hello @per1234,

Earlier, I requested a rename of my library because its name was too long and contained the word "library." @MatteoPologruto kindly solved this problem, but I received a message stating that the library was removed successfully (#4398). However, the library is still listed in the registry while removed from Arduino IDE library manager, and I'm facing some issues with it.

Initially, I thought the library was removed from the registry, so I decided to add it again (#4467). But, I discovered that it was still present in the registry. Now, I'd like to remove the library from the registry and re-add it to resolve these issues.

I would greatly appreciate it if you could help me resolve this issue. I'm open to any suggestions or recommendations you may have on how to proceed. Thank you for your time and support.

**Comment by per1234** [comment]
> I received a message stating that the library was removed successfully

I understand the confusion. The way we handle a renaming in the database that populates Library Manager is to remove the data that is stored under the library's previously registered name ("PI3EQX12908 PCIe redriver library" in this case), after which the system will automatically populate the database for the new library name ("PI3EQX12908A2" in this case). So from the perspective of maintaining the database, accommodating a library rename request is the same procedure as for a library removal request. This is why the logs shared by the database maintainer said "`Removing PI3EQX12908 PCIe redriver library`". But those are only boring technical details to anyone other than the database maintainer. For the rest of us this is simply a name change and that is exactly what occurred:

image

> Now, I'd like to remove the library from the registry and re-add it to resolve these issues.

As I explained, we don't allow the temporary removal of libraries as a way to resolve issues. Instead we must use a standard procedure to resolve the issues.

> I would greatly appreciate it if you could help me resolve this issue. 

I'm happy to do that, but first I need to know what the issue is. Please provide a detailed description of the issue in a comment here.

**Comment by SMotlaq** [comment]
My apologies for the confusion earlier. I realized that I was searching for the new library name in the board manager instead of the library manager, which led me to believe that it was removed from the Arduino IDE!
Thank you for your help in resolving this issue. There's no problem anymore, and I appreciate your support.

**Comment by per1234** [comment]
You are welcome. I'm glad everything is working. Thanks for taking the time to provide an update!

**Pull request closed without merging**
