### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by PaulNTU**

### CODE REVIEW

**Comment by PaulNTU** [comment]
@ArduinoBot

**Comment by PaulNTU** [comment]
@ArduinoBot

**Comment by per1234** [comment]
Hello @PaulNTU. The automated system here only operates on open pull requests. Since your submission was already accepted and the pull request merged, the bot won't pay any more attention to this pull request.

But this human is happy to provide assistance. Was there something you needed from the bot?

**Comment by PaulNTU** [comment]
Hi, I think I have sussed it now. I was trying to work out how to update the existing package in the library manager. I think I forgot to check in the version number change in the properties file. I've updated that and will see if it works 🙂

Thanks for getting back to me 🤓

Paul

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request merged**
