### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by segertonGH**

### CODE REVIEW

**Review by per1234 — COMMENTED** [review]
Hello @segertonGH. In addition to the correct change of adding your library's repository URL to the list, your pull request also removes all occurrences of the text "ping" from the rest of the list.

This is the reason for the errors reported by the bot.

Please restore the harmful changes that were made to the content. Doing that will trigger another automated check by the bot. Once the pull request passes the checks it will be merged automatically and your library added to Arduino Library Manager.

Please let me know if you have any questions or problems while making the necessary changes.

Regards, Per

**Comment by segertonGH** [comment]
Hi Per, thanks, and ops, I was searching "ping" in the editor :-( I've corrected the warnings and errors picked up by the bot in the CreativeRobotix library and will resubmit the pull request.  Many thanks.  Simon.

**Comment by per1234** [comment]
@segertonGH you are welcome to continue to use this PR if you like. Any change you commit to the `main` branch in your fork will be automatically applied to this PR. The automated submission management system is designed to allow the contributors to iterate on their pull requests to achieve a compliant submission.

**Comment by segertonGH** [comment]
@ArduinoBot

**Pull request merged**
