### PR TITLE
update

### PR DESCRIPTION
**Pull request by bpescarolli**

### CODE REVIEW

**Comment by bpescarolli** [comment]
@ArduinoBot

**Comment by bpescarolli** [comment]
i need update that lib for new release for fix file library.properties ...

**Comment by bpescarolli** [comment]
@ArduinoBot

**Comment by per1234** [comment]
Hello @bpescarolli. I am confirming your request to update the registered name of the library.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests and closes those issues and pull requests when it is done. If you subscribe to the pull request which does the renaming, you will get a notification from GitHub at that time:

https://github.com/arduino/library-registry/pull/1419

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

Since the change proposed via this pull request would not achieve your goal of updating the library name, I will close it.

I'll continue to monitor this thread, so feel free to let me know if you have any questions or concerns.

**Pull request closed without merging**
