### PR TITLE
Added my MicroFlow library

### PR DESCRIPTION
**Pull request by Bobingstern**

### CODE REVIEW

**Comment by Bobingstern** [comment]
library.properties exists. It is in the main branch just like specified. I'm not sure what went wrong. @ArduinoBot

**Comment by Bobingstern** [comment]
I'm very confused. My repo has a library.properties file. I used the example provided in the library specifications and modified it for my library. @ArduinoBot

**Comment by Bobingstern** [comment]
@ArduinoBot 
library.properties exists

**Comment by Bobingstern** [comment]
Can someone tell me whats wrong
@ArduinoBot
Screenshot 2022-03-10 9 27 22 AM
?

**Comment by Bobingstern** [comment]
@ArduinoBot

**Comment by per1234** [comment]
Hi @Bobingstern. I see you have fixed the error reported by the bot. However, Library Manager works exclusively from Git tags, so the bot won't be able to see the fix you made until you create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.

If you look at the repository contents at the latest tag, you can see that the version the bot is checking still does not have the required `library.properties` file:

https://github.com/Bobingstern/MicroFlow/tree/v1.1.0

Remember to update the `version` field in the library's [`library.properties` file](https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format) as needed before making a release/tag.

Once you have done that, simply mention **@ArduinoBot** in a comment here to trigger it to run the automated checks again. After those are passing, your library will automatically be added to Library Manager.

If you have any questions or concerns, please let me know.

Regards, Per

**Comment by Bobingstern** [comment]
Ah I see now. Thanks you so much @per1234 
@ArduinoBot

**Pull request merged**
