### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by cclngit**

### CODE REVIEW

**Comment by cclngit** [comment]
@ArduinoBot

**Comment by cclngit** [comment]
@ArduinoBot

**Comment by per1234** [comment]
Hello @cclngit. The automated system here only operates on open pull requests. Since your submission was already accepted and the pull request merged, the bot won't pay any more attention to this pull request.

But this human is happy to provide assistance. Was there something you needed from the bot?

**Comment by cclngit** [comment]
@per1234 Hi, sorry for the misuse of the bot. I had badly created my example folders, so I saw the warning that my library had no example. So I updated the library and thought I had to re-call the bot for the update.

**Comment by per1234** [comment]
Thanks for the explanation. After the initial addition of the library, the indexer job periodically checks each of the libraries in the index and picks up any new release/tag that meets the requirements listed here:

https://github.com/arduino/library-registry/blob/main/FAQ.md#what-are-the-requirements-for-publishing-new-releases-of-libraries-already-in-the-library-manager-list

This means that you only need to do the following to release a new version of your library:

1. Bump the value of the `version` field in the library's [`library.properties` file](https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format).
1. Create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.

There is no need to take any additional action here in the Arduino Library Registry to add new releases of your library to Library Manager. They will be added automagically!

It does take a little time for the indexer job to run, and then some additional time after that for the update to propagate through the CDN and the local cache. But it will get there. We give a conservative estimate of availability within one day's time.

You can monitor the indexing of the library releases by checking the library's dedicated indexer logs web page:
https://github.com/arduino/library-registry/blob/main/FAQ.md#user-content-can-i-check-on-library-releases-being-added-to-library-manager

**Pull request merged**
