### PR TITLE
NRF_HAL library URL fix

### PR DESCRIPTION
**Pull request by pstolarz**
Some time ago I changed NRF_HAL repository name to match library name. This PR contains fixed URL.

### CODE REVIEW

**Review by per1234 — APPROVED** [review]
Thanks so much @pstolarz! Congratulations on making the first community submitted PR to this repository.

Don't worry about the CLA. We didn't remember to turn it off for this repository but it is now, so it won't be required for any future pull requests here.

**Comment by pstolarz** [comment]
Thanks @per1234.
Could you tell me what this repository is intended for? Are you going to change a method of adding new contributors repositories into Library Manager by replacing legacy method (submitting PRs to [Arduino](https://github.com/arduino/Arduino))?

**Comment by per1234** [comment]
> Are you going to change a method of adding new contributors repositories into Library Manager by replacing legacy method

That's exactly it.

There will be an official announcement about it soon. Until then, you can see details in the readme:
https://github.com/arduino/library-registry#readme

**Comment by pstolarz** [comment]
Thanks for the clarification. That's very good idea - the process will became more automatic w/o additional human intervention as currently.

**Pull request merged**
