### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by pxsty0**

### CODE REVIEW

**Comment by pxsty0** [comment]
@ArduinoBot

**Review by per1234 — COMMENTED** [review]
Hello @pxsty0. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will merge this pull request when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by pxsty0** [comment]
Thanks

**Review by MatteoPologruto — APPROVED** [review]
Done:
```
2024/11/12 15:46:01 Loaded 7456 libraries from DB
Changing URL of library PxServ from https://github.com/pxsty0/pxserv.lib.git to https://github.com/pxsty0/pxserv.arduino.git
warning: Library Git clone folder /home/ubuntu/workspace/gitclones/github.com/pxsty0/pxserv.lib not present
Success!
```

**Pull request merged**
