### PR TITLE
Added a updated dependency

### PR DESCRIPTION
**Pull request by internetoftobi**

### CODE REVIEW

**Comment by internetoftobi** [comment]
@ArduinoBot

**Review by per1234 — COMMENTED** [review]
I guess this was a hacky attempt at getting our system to run the submission checks on the library again after it had already been registered.

@internetoftobi as [I explained in your other pull request](https://github.com/arduino/library-registry/pull/5172#issuecomment-2377612564), we only run checks on submissions. This repository is not a check running service. Please do not spam our repository with pointless pull requests in an attempt to abuse the system as this wastes the time of the human maintainers and also will not achieve your goal.

I provided advice about how you can perform validation on your library in my comment on your other pull request:

https://github.com/arduino/library-registry/pull/5172#issuecomment-2377612564

If you have any questions about setting that up, or encounter any problems while doing it, you are welcome to request assistance over on Arduino Forum:

https://forum.arduino.cc/c/development/libraries/39

**Comment by internetoftobi** [comment]
@ArduinoBot

**Comment by per1234** [comment]
| @internetoftobi |
| :-: |
| :exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation: |
| :exclamation::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::exclamation: |
| :exclamation::warning:  **PLEASE READ THIS IMPORTANT INFORMATION**  :warning::exclamation: |
| :exclamation::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::exclamation: |
| :exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation: |
| @internetoftobi  |

CLEARLY YOU DIDN'T BOTHER TO READ WHAT I WROTE ABOVE!!!!!!!!!!!!!!!!!!!!!!!!
Please do that now, and stop spamming this repository with pointless comments. If you continue this disrespectful behavior, you will be banned from all of Arduino's repositories and your library will be removed from Library Manager.

**Pull request closed without merging**
