### PR TITLE
Add https://github.com/0neblock/Arduino_SNMP

### PR DESCRIPTION
**Pull request by 0neblock**

### CODE REVIEW

**Comment by 0neblock** [comment]
@per1234 This PR seems to be broken. The original repo has been fixed but the linter seems to be running against a cached version of the repo? https://github.com/0neblock/Arduino_SNMP

**Comment by 0neblock** [comment]
@ArduinoBot

**Comment by per1234** [comment]
Hello @0neblock. I see you have fixed the error reported by the bot. However, Library Manager works exclusively from Git tags, so the bot won't be able to see the fix you made until you create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.

Remember to update the `version` field in the library's [`library.properties` file](https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format) as needed before making a release/tag.

Once you have done that, simply mention @[]()ArduinoBot in a comment here to trigger it to run the automated checks again. After those are passing, your library will automatically be added to Library Manager.

**Comment by 0neblock** [comment]
@ArduinoBot

**Pull request merged**
