### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by locple**
Add LiquidCrystal_I2C_UTF8 to the library manager

### CODE REVIEW

**Comment by locple** [comment]
@ArduinoBot

**Comment by locple** [comment]
@ArduinoBot

**Comment by locple** [comment]
@ArduinoBot

**Comment by per1234** [comment]
Hello @locple. The automated system here only operates on open pull requests. Since your submission was already accepted and the pull request merged, the bot won't pay any more attention to this pull request.

But this human is happy to provide assistance. Was there something you needed from the bot?

**Comment by locple** [comment]
Hi,

I updated library.properties in order to remove some warnings. I don't know the pull request had closed before.

Thank you for your explaining.

Loc P. Le
________________________________
Từ: per1234 ***@***.***>
Đã gửi: 18 Tháng Ba 2024 2:51 SA
Đến: arduino/library-registry ***@***.***>
Cc: locple ***@***.***>; Mention ***@***.***>
Chủ đề: Re: [arduino/library-registry] Update repositories.txt (PR #4228)


Hello @locple<https://github.com/locple>. The automated system here only operates on open pull requests. Since your submission was already accepted and the pull request merged, the bot won't pay any more attention to this pull request.

But this human is happy to provide assistance. Was there something you needed from the bot?

**Pull request merged**
