### PR TITLE
Add TcBUTTON

### PR DESCRIPTION
**Pull request by Jakkapan-a**

### CODE REVIEW

**Comment by Jakkapan-a** [comment]
Add TcBuuton to [library-registry](https://github.com/arduino/library-registry)]

**Comment by Jakkapan-a** [comment]
> A problem was found with your submission https://github.com/Jakkapan-a/TcBUTTON
> 
> ❌ **ERROR:** The repository has no tags. You need to create a [release](https://docs.github.com/en/github/administering-a-repository/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) that matches the `version` value in the library's library.properties file.

 Updated the version tag already

**Comment by per1234** [comment]
@ArduinoBot please check it again.

**Comment by per1234** [comment]
Hello @Jakkapan-a. After the initial addition of the library, the indexer job periodically checks each of the libraries in the index and picks up any new release/tag that meets the requirements listed here:

https://github.com/arduino/library-registry/blob/main/FAQ.md#what-are-the-requirements-for-publishing-new-releases-of-libraries-already-in-the-library-manager-list

This means there is no need to take any additional action to add new releases of your library to Library Manager. They will be added automagically!

The automated system here only operates on open pull requests. Since your submission was already accepted and the pull request merged, the bot completely ignores this pull request thread.

It does take a little time for the indexer job to run, and then some additional time after that for the update to propagate through the CDN and the local cache. But it will get there. We give a conservative estimate of availability within one day's time.

You can monitor the indexing of the library releases by checking the library's dedicated indexer logs web page:
http://downloads.arduino.cc/libraries/logs/github.com/Jakkapan-a/TcBUTTON/

**Pull request merged**
