### PR TITLE
Cambios necesarios

### PR DESCRIPTION
**Pull request by AlfredoMunguia**
Se cambiaron los ejemplos y archivos de librerias

### CODE REVIEW

**Comment by AlfredoMunguia** [comment]
@ArduinoBot

**Comment by AlfredoMunguia** [comment]
ArduinoBot

**Comment by AlfredoMunguia** [comment]
se eliminaron las demas URL que se crearon de mas

**Comment by AlfredoMunguia** [comment]
@ArduinoBot

**Review by per1234 — COMMENTED** [review]
| @AlfredoMunguia |
| :-: |
| :exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation: |
| :exclamation::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::exclamation: |
| :exclamation::warning:  **PLEASE READ THIS IMPORTANT INFORMATION**  :warning::exclamation: |
| :exclamation::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::warning::exclamation: |
| :exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation::exclamation: |
| @AlfredoMunguia |

Hello @AlfredoMunguia. Please, please please...

:exclamation::exclamation::exclamation: _**DO NOT SUBMIT PULL REQUESTS EVERY TIME YOU MAKE A CHANGE IN YOUR LIBRARY**_ :exclamation::exclamation::exclamation: 

It is completely pointless and only wastes both of our time. I already explained this to you in your previous pull request (https://github.com/arduino/library-registry/pull/3516#pullrequestreview-1698456511), after which time you submitted two more.

:warning: **I'm starting to lose my patience with you. If you continue with this behavior we will ban you from Arduino's repositories and remove your library from Library Manager.**

---

After the initial addition of the library, the indexer job periodically checks each of the libraries in the index and picks up any new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository that meets the requirements listed here:

https://github.com/arduino/library-registry/blob/main/FAQ.md#what-are-the-requirements-for-publishing-new-releases-of-libraries-already-in-the-library-manager-list

This means there is no need to take any additional action to add new releases of your library to Library Manager. They will be added automagically!

It does take a little time for the indexer job to run, and then some additional time after that for the update to propagate through the CDN and the local cache. But it will get there. We give a conservative estimate of availability within one day's time.

You can monitor the indexing of the library releases by checking the library's dedicated indexer logs web page:
https://github.com/arduino/library-registry/blob/main/FAQ.md#user-content-can-i-check-on-library-releases-being-added-to-library-manager

**Comment by AlfredoMunguia** [comment]
Ok entiendo gracias, por su paciencia

**Pull request closed without merging**
