### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by divinofire**

### CODE REVIEW

**Comment by divinofire** [comment]
@ArduinoBot

**Comment by divinofire** [comment]
@ArduinoBot

**Comment by per1234** [comment]
Hello @divinofire. The automated system here only operates on open pull requests. Since your submission was already accepted and the pull request merged, the bot won't pay any more attention to this pull request.

But this human is happy to provide assistance. Was there something you needed from the bot?

**Comment by divinofire** [comment]
Yeah, I wish to ask that if I make an update to my library on github will arduino automatically make those changes available to the library manager?

**Comment by per1234** [comment]
After the initial addition of the library, the indexer job periodically checks each of the libraries in the index and picks up any new release/tag that meets the requirements listed here:

https://github.com/arduino/library-registry/blob/main/FAQ.md#what-are-the-requirements-for-publishing-new-releases-of-libraries-already-in-the-library-manager-list

This means that new releases of your library are added automatically to Library Manager without the need for you to take any additional action beyond making the release in your repository as usual.

It does take a little time for the indexer job to run, and then some additional time after that for the update to propagate through the CDN and the local cache. But it will get there. We give a conservative estimate of availability within one day's time.

You can monitor the indexing of the library releases by checking the library's dedicated indexer logs web page:

http://downloads.arduino.cc/libraries/logs/github.com/divinofire/DatabaseOnSD/

**Comment by divinofire** [comment]
Thank you for the clarification

**Pull request merged**
