### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by Arya11111**

### CODE REVIEW

**Comment by Arya11111** [comment]
ok

**Comment by per1234** [comment]
@ArduinoBot please check it again.

**Comment by per1234** [comment]
@Arya11111 Please check the latest error message from the bot;

```
Linting library in DFRobot_RaspberryPi_A02YYUW
ERROR: Path does not contain a valid Arduino library. See:                                                              
       https://arduino.github.io/arduino-cli/latest/library-specification (Rule LS001)                                  
```
There is no Arduino code in this repository. There is a `library.properties` file, but otherwise it is all Python and the documentation also indicates it is intended to be a Python project. Please check the repository carefully to make sure you have submitted the correct URL.

**Comment by per1234** [comment]
Closing due to lack of response.

**Pull request closed without merging**
