### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by SooDragon**

### CODE REVIEW

**Comment by SooDragon** [comment]
@ArduinoBot

**Comment by SooDragon** [comment]
@ArduinoBot

**Review by per1234 — CHANGES_REQUESTED** [review]
Hello @SooDragon. It looks like you are attempting to do three things will this pull request:

A. Add https://github.com/Geekble-Maker/Geekble_MotorOrgel
B. Change URL of https://github.com/geekblemaker/Geekble_note2freq to https://github.com/Geekble-Maker/Geekble_Note2Freq
C. Change URL of https://github.com/geekbleofficial/Geekble_LieDetector to https://github.com/geekblemaker/Geekble_LieDetector

Please use a separate pull request for each distinct type of operation. The automated system is not capable of processing pull requests that contain both a submission and a URL change. So please submit a dedicated pull request if you want to submit https://github.com/Geekble-Maker/Geekble_MotorOrgel.

You should create a dedicated branch in your fork for each pull request. You should not use the `main` branch of your fork for pull requests. You can learn how to work with pull requests from this tutorial:

https://docs.github.com/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests

---

You already have a pull request https://github.com/arduino/library-registry/pull/5512 for updating the URL of https://github.com/geekbleofficial/Geekble_LieDetector. So please remove that change from this pull request.

**Review by per1234 — COMMENTED** [review]
Closing as duplicate of https://github.com/arduino/library-registry/pull/5544

**Pull request closed without merging**
