### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by AlexRosito67**
Delete repository:
https://github.com/AlexRosito67/QUAD7SHIFT

Reason:
Conflict with the repository name.

### CODE REVIEW

**Review by per1234 — COMMENTED** [review]
Hi @AlexRosito67. Please provide a detailed explanation of what you are hoping to accomplish.

I ask because the reason you provided for the removal doesn't make sense:

> Conflict with the repository name.

It might be there is a more efficient way to accomplish your goal. If I understand what your goal is, I can suggest the optimal procedure and assist you with that.

**Comment by AlexRosito67** [comment]
The problem is that my library was called FSSD (Four digits Seven Segment Display) but there were other libraries called FSSD (no relation with seven segment displays) that can confuse the potential user about the purpose of my library. I, then, decided to change it’s name to QUAD7SHIFT (Four seven segment displays with shift registers). But even though I could change the name it seems that in your side you were still getting the library.properties with the information of the FSSD library that was lacking of the correct url. And also in your side there was a message that said that even the library name changed the library’s real name is FSSD. So I decided to clean everything. I deleted the old repository and recreated it. Now I need to clean the previous meta data from the FSSD library in your side. The only way I think might work is deleting everything about my previous pull requests and when everything is clean I’ll request another pull with the inclusion of the new metadata of the QUAD7SHIFT library.. I hope I haven’t confused you too much.

**Review by per1234 — COMMENTED** [review]
As I suspected, you are taking an inappropriate approach to achieving your goal.

Your goal is to change the library name to resolve the error shown in the logs:

https://downloads.arduino.cc/libraries/logs/github.com/AlexRosito67/QUAD7SHIFT/

```text
2023/08/02 04:29:43 Scraping https://github.com/AlexRosito67/QUAD7SHIFT.git
2023/08/02 04:29:43 Checking out tag: v1.0.0
2023/08/02 04:29:43 Release QUAD7SHIFT:1.0.0 has wrong library name, should be FSSD
```

So you need to follow the documented procedure for requesting a library name change:

https://github.com/arduino/library-registry/blob/main/FAQ.md#how-can-i-change-a-librarys-name

I will close this pull request as invalid because we do not allow this approach.

In the future, if you notice a problem with the indexing of your library's releases, or if you want to request some change to the registration data, please take some time to carefully read the repository's documentation, which might answer your question and provide directions for resolving it:

<https://github.com/arduino/library-registry#readme>

You should also be careful to clearly describe what you are hoping to accomplish. It is true that the library submission process is fully automated, but all other operations in this repository are handled by humans, so you must make the effort to communicate in a way a human can understand.

**Comment by AlexRosito67** [comment]
Fair enough! But now my question is. Is the problem still present as stated in the logs?  Or because my repository is still in the list, will the “system”, eventually, be updated with the new information?

**Comment by per1234** [comment]
> Is the problem still present as stated in the logs?

Yes.

> because my repository is still in the list, will the “system”, eventually, be updated with the new information?

No. Since the name is the sole unique identifier for a library, which used when specifying a dependency on the library, libraries in the Library Manager list are locked to the name that was defined in the `name` field of the `library.properties` file in the tagged version of the library at the time the library was submitted. You can see the library was registered under the name `FSSD` here:

https://github.com/arduino/library-registry/commit/abc067bf6f1734f8679e1cd851b0d5bdb38925c1

https://github.com/arduino/library-registry/blob/ea345bb8b139f800b0b1e3496999d5ffd67b38af/registry.txt#L6187

The only way to change that registration data is by explicitly requesting the registry maintainers to update the name via [the procedure](https://github.com/arduino/library-registry/blob/main/FAQ.md#how-can-i-change-a-librarys-name) I linked to in my previous comment.

**Comment by AlexRosito67** [comment]
Thank you so much for your answer, because I'm new in this adventure of publishing a library, (I hope to contribute more) I find it very useful and also clear and concise. 
Thanks again per1234.

**Pull request closed without merging**
