### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by Justin-Pl**

### CODE REVIEW

**Comment by Justin-Pl** [comment]
@ArduinoBot

**Comment by Justin-Pl** [comment]
@ArduinoBot check mal

**Comment by per1234** [comment]
Hello @Justin-Pl. The automated system here only operates on open pull requests. Since your submission was already accepted and the pull request merged, the bot won't pay any more attention to this pull request.

But this human is happy to provide assistance. Was there something you needed from the bot?

**Comment by Justin-Pl** [comment]
Hello @per1234, Im a little confused with the lint log: no example sketch found. My repo has a /examples dir with a sketch but lint dont see this dir. 
https://downloads.arduino.cc/libraries/logs/github.com/Justin-Pl/PCA9685_LED_DRIVER/
https://github.com/Justin-Pl/PCA9685_LED_DRIVER

**Comment by per1234** [comment]
>My repo has a /examples dir with a sketch

This is incorrect. Your repo has an `examples` dir with a `.ino` file in it.

Because many sketches consist of only a single `.ino` file, it is easy to get the impression that the `.ino` file is the sketch, but this is not so. It is the folder that is the sketch. The `.ino` file must be inside a folder that matches the filename in order for it to be a valid sketch that will show up in the **File > Examples > PCA9685_LED_DRIVER** menu in Arduino IDE:

```text
examples/
└── simpleTest/
    └── simpleTest.ino
```

**Comment by Justin-Pl** [comment]
Thanks for the help

**Pull request merged**
