### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by galarb**

### CODE REVIEW

**Comment by per1234** [comment]
Hello @galarb.  Thanks for your interest in contributing to the Arduino Library Manager index.

I see the bot reported a problem with your submission that will block its acceptance:

```text
❌ ERROR: Library is missing a library.properties metadata file.
```

I'll provide a bit more information. Every library added to the Arduino Library Manager index is required to have [a `library.properties` metadata file](https://arduino.github.io/arduino-cli/latest/library-specification/#library-metadata). I can see you attempted to add that file to your library:

https://github.com/galarb/clicli/blob/v1.0.1/library.properties.txt

The problem is you used the wrong filename. Note that your filename is `library.properties.txt`. The `.txt` at the end is not allowed.

I'll provide instructions for how you can fix the problem:

## Correct filename

It is sometimes difficult to see the extension when looking at the file on your computer because the operating system has an annoying default behavior of hiding known file extensions from you. So it looks like the file `library.properties.txt` is named `library.properties`. For this reason, it might be easiest to fix via the GitHub web interface:

1. Open this page in your web browser:
   https://github.com/galarb/clicli/blob/master/library.properties.txt
1. Click the pencil icon on the toolbar ("Edit this file").
1. Near the top of the page that opens, you will see the path of the file: "**clicli / library.properties.txt**"
   image
1. Click on the field containing the filename **library.properties.txt**.
1. Delete the `.txt` from the filename.
1. Scroll down to the bottom of the page.
1. Click the <kbd>Commit changes</kbd> button.

You will now have the correct filename.

## Make tag

Now you have fixed the error reported by the bot. However, Library Manager works exclusively from Git tags, so the bot won't be able to see the fix you made until you create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.

Remember to update the `version` field in the library's [`library.properties` file](https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format) as needed before making a release/tag.

## Trigger the checks again

Once you have done that, simply mention **@ArduinoBot** in a comment here to trigger it to run the automated checks again.

After those are passing, your library will automatically be added to Library Manager.

---

If you have any questions or concerns, please let me know.

Regards, Per

---

If you decide you no longer wish to submit the library, you can close this pull request.

**Comment by galarb** [comment]
@ArduinoBot

**Comment by galarb** [comment]
@ArduinoBot

**Comment by galarb** [comment]
@ArduinoBot

**Comment by galarb** [comment]
@ArduinoBot

**Comment by galarb** [comment]
@galarb

**Comment by galarb** [comment]
@ArduinoBot

**Comment by galarb** [comment]
@ArduinoBot

**Comment by galarb** [comment]
@ArduinoBot

**Comment by galarb** [comment]
@ArduinoBot

**Comment by galarb** [comment]
@ArduinoBot

**Comment by galarb** [comment]
@ArduinoBot

**Comment by galarb** [comment]
@ArduinoBot

**Comment by galarb** [comment]
@ArduinoBot

**Comment by galarb** [comment]
@ArduinoBot

**Comment by galarb** [comment]
@ArduinoBot

**Comment by galarb** [comment]
@ArduinoBot

**Comment by galarb** [comment]
@ArduinoBot

**Comment by galarb** [comment]
@ArduinoBot

**Comment by galarb** [comment]
@ArduinoBot

**Comment by galarb** [comment]
@ArduinoBot

**Comment by galarb** [comment]
@ArduinoBot

**Comment by per1234** [comment]
Hello @galarb. The reason the bot is unable to recognize the `name` field from your `library.properties` metadata file is because you have used the "UTF-8 BOM" character encoding in the file. This odd encoding adds a "BOM" character to the start of the file. So instead of this:

```text
name=clicli
```

Your file actually is this:

```text
<BOM>name=clicli
```

Hello @galarb.  Thanks for your interest in contributing to the Arduino Library Manager index.

I see the bot reported a problem with your submission that will block its acceptance:

```text
❌ ERROR: Library is missing a library.properties metadata file.
```

I'll provide instructions for how you can fix the problem:

## Remove BOM character

Depending on which text editor you are using on your computer, it might be more complicated to change the file encoding. The GitHub web interface makes it quite easy, so I'll provide instructions using it.

1. Open this page in your web browser:
   https://github.com/galarb/clicli/blob/master/library.properties.txt
1. Click the pencil icon on the toolbar ("Edit this file").
1. Look in the field containing the file contents. you will see a little red dot before `name=clicli`. This dot symbolizes the BOM character:
   image
1. Click on the field containing the containing the file contents.
1. Place the cursor after the red dot character.
1. Press the <kbd>Backspace</kbd> key to delete the red dot character from the file.
1. Scroll down to the bottom of the page.
1. Click the <kbd>Commit changes</kbd> button.

You will now have the correct filename.

## Make tag

Now you have fixed the error reported by the bot. However, Library Manager works exclusively from Git tags, so the bot won't be able to see the fix you made until you create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.

Remember to update the `version` field in the library's [`library.properties` file](https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format) as needed before making a release/tag.

## Trigger the checks again

Once you have done that, simply mention **@ArduinoBot** in a comment here to trigger it to run the automated checks again.

After those are passing, your library will automatically be added to Library Manager.

## Fix your editor software and existing files

You will likely have confusing problems like this over and over again as long as the text editor software on your computer is still configured to use UTF-8 BOM encoding. There is never any reason to use this encoding. Any good text editor will have an option to set the default encoding. Set it to "UTF-8".

If your text editor does not offer this option, get a good one. I recommend [**VS Code**](https://code.visualstudio.com/), but there are many options.

Even after you have configured the default character encoding in your editor, all the files you created with the bad setting will continue to have UTF-8 BOM encoding. You should open all these files and convert their encoding to UTF-8. Any good text editor will allow you do this easily.

---

If you have any questions or concerns, please let me know.

Regards, Per

---

If you decide you no longer wish to submit the library, you can close this pull request.

**Comment by galarb** [comment]
@ArduinoBot

**Comment by galarb** [comment]
@ArduinoBot

**Comment by galarb** [comment]
@ArduinoBot

**Comment by per1234** [comment]
Closing as duplicate of https://github.com/arduino/library-registry/pull/1928

**Comment by galarb** [comment]
@ArduinoBot

----------------------------------------
Best Regards,
Gal Arbel

Mobile: +972 502158529

On 29 Sep 2022, at 18:22, per1234 ***@***.***> wrote:

@ArduinoBot

**Comment by per1234** [comment]
Hello @galarb. As I already explained to you, the automated system here only operates on open pull requests. Since your submission was already accepted and the pull request merged, the bot won't pay any more attention to this pull request.

Was there something you needed from the bot?

**Pull request closed without merging**
