### PR TITLE
Add Matrix Library

### PR DESCRIPTION
**Pull request by zakarialaoui10**

### CODE REVIEW

**Comment by zakarialaoui10** [comment]
I have fixed it 
@ArduinoBot

**Comment by zakarialaoui10** [comment]
@ArduinoBot

**Comment by zakarialaoui10** [comment]
@ArduinoBot

**Comment by per1234** [comment]
Hello @zakarialaoui10. The automated system here only operates on open pull requests. Since your submission was already accepted and the pull request merged, the bot won't pay any more attention to this pull request.

But this human is happy to provide assistance. Was there something you needed from the bot?

**Comment by zakarialaoui10** [comment]
@per1234 Thank you , just i had a problem in release and I fixed it

**Pull request merged**
