### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by josiascarnot**

### CODE REVIEW

**Review by per1234 — COMMENTED** [review]
@josiascarnot please carefully read the messages from the bot. If you are not fluent in English, simply use Google Translate to translate the messages to your native language.

If there is something you don't understand, then add a comment here with a detailed description of what is not clear to you or what problem you are having.

⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ 
**DO NOT OPEN ADDITIONAL PULL REQUESTS!!!!!!!!!!!**
⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ 

The submission system is designed to allow you to use a single pull request to achieve a successful submission even when the first round of checks fail. You are only wasting time and making me angry by creating new pull requests.

**Comment by josiascarnot** [comment]
Désolé je veux soumettre une bibliothèque sur le référentiel de Arduino. Que dois-je faire

**Comment by josiascarnot** [comment]
@ArduinoBot

**Comment by josiascarnot** [comment]
@ArduinoBot

**Pull request merged**
