### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by deangi**
Add driver class libraries for sensors - tilt sensor, ultrasonic distance sensor, radar sensor, IR proximity sensor, PIR sensor

### CODE REVIEW

**Comment by deangi** [comment]
Adding driver classes for PIR sensor, IR Prox sensor, 0516 radar sensor, tilt sensor, ultrasonic distance sensor

**Comment by deangi** [comment]
Hey @ArduinoBot - I added tag 1.1

**Review by per1234 — COMMENTED** [review]
Hello @deangi. Thanks for your interest in contributing to the Arduino Library Manager index.

I see the bot reported a problem with your submission that will block its acceptance:

> ❌ ERROR: [Arduino Lint](https://github.com/arduino/arduino-lint) found errors with https://github.com/deangi/UltrasonicSensor:
>
>```text
>ERROR: Library name UltrasonicSensor is in use by a library in the Library Manager index. Each library must have a      
>       unique name value.
```

You will need to do the following things:

1. Change the value of the `name` field in the library's `library.properties` metadata file to a unique name that is not already in use by one of the other libraries in the Arduino Library manager:
   https://github.com/deangi/UltrasonicSensor/blob/main/library.properties#L1
1. Bump the value of the `version` field in the library's `library.properties` metadata file.
1. Create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.
1. Add a comment here in the pull request thread that mentions **@<!---->Arduino<!---->Bot**.

After that, the automated checks will run again. Once those are passing, your library will automatically be added to Library Manager.

If you have any questions or concerns, please let me know.

Regards, Per

**Comment by deangi** [comment]
@ArduinoBot. please lint again

**Pull request merged**
