### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by danielminson**

### CODE REVIEW

**Comment by danielminson** [comment]
I want to remove MyIoT library https://github.com/MyIoT-space/myiotlibrary

**Review by per1234 — COMMENTED** [review]
Hello @danielminson. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will merge this pull request when it is done. You will get a notification from GitHub at that time.

**Comment by njh** [comment]
@danielminson do you have any information about why you want to delete the library?

**Comment by danielminson** [comment]
I don’t want it to be public anymore.

**Review by MatteoPologruto — APPROVED** [review]

**Comment by MatteoPologruto** [comment]
Done:
```
2023/03/29 16:52:54 Loaded 5661 libraries from DB
Removing MyIoT library
warning: Library Git clone folder /home/ubuntu/workspace/gitclones/github.com/MyIoT-space/myiotlibrary not present
Success!
```

**Pull request merged**
