### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by Dhruvacube**
A new 7 seg library

### CODE REVIEW

**Comment by Dhruvacube** [comment]
@ArduinoBot

**Comment by Dhruvacube** [comment]
@ArduinoBot

**Comment by Dhruvacube** [comment]
ahhhh linking of tags

**Comment by Dhruvacube** [comment]
@ArduinoBot

**Comment by Dhruvacube** [comment]
hmmmmm i will come and check tommrow

**Review by per1234 — COMMENTED** [review]
Hello @Dhruvacube. I see you have fixed the error reported by the bot:

https://github.com/arduino/library-registry/pull/3152#issuecomment-1660735877

```text
ERROR: Prohibited character(s) in file name(s): Custom Character.ino                                   
       See: https://arduino.github.io/arduino-cli/latest/sketch-specification/#sketch-folders-and-files
       (Rule SS002)                                                                                    
```

However, Library Manager works exclusively from Git tags, so the bot won't be able to see the fix you made until you create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.

If you look at the repository contents at the latest tag, you can see that the version the bot is checking still has the problem:

https://github.com/Dhruvacube/7-Segment/tree/v0.0.1/examples/Custom%20Character

❗ Remember to update the `version` field in the library's [`library.properties` file](https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format) as needed before making a release/tag.

Once you have done that, simply mention **@ArduinoBot** in a comment here to trigger it to run the automated checks again. After those are passing, your library will automatically be added to Library Manager.

If you have any questions or concerns, please let me know.

Regards, Per

**Comment by Dhruvacube** [comment]
> Hello @Dhruvacube. I see you have fixed the error reported by the bot:
> 
> [#3152 (comment)](https://github.com/arduino/library-registry/pull/3152#issuecomment-1660735877)
> 
> ```
> ERROR: Prohibited character(s) in file name(s): Custom Character.ino                                   
>        See: https://arduino.github.io/arduino-cli/latest/sketch-specification/#sketch-folders-and-files
>        (Rule SS002)                                                                                    
> ```
> 
> However, Library Manager works exclusively from Git tags, so the bot won't be able to see the fix you made until you create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.
> 
> If you look at the repository contents at the latest tag, you can see that the version the bot is checking still has the problem:
> 
> https://github.com/Dhruvacube/7-Segment/tree/v0.0.1/examples/Custom%20Character
> 
> ❗ Remember to update the `version` field in the library's [`library.properties` file](https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format) as needed before making a release/tag.
> 
> Once you have done that, simply mention **@ArduinoBot** in a comment here to trigger it to run the automated checks again. After those are passing, your library will automatically be added to Library Manager.
> 
> If you have any questions or concerns, please let me know.
> 
> Regards, Per

oh ok got, then lemme quickly make nice readme file publish the new changes into a new version

**Comment by Dhruvacube** [comment]
> Hello! I'm checking your submission again.

eehhhh not now , bruh

**Comment by Dhruvacube** [comment]
@ArduinoBot

**Comment by Dhruvacube** [comment]
Ahhhh now praragraph field is required

**Comment by Dhruvacube** [comment]
@ArduinoBot

**Pull request merged**
