### PR TITLE
Add ESP32 Canon BLE Remote Library

### PR DESCRIPTION
**Pull request by maxmacstn**

### CODE REVIEW

**Comment by maxmacstn** [comment]
@ArduinoBot I've added a tag, please check it again.

Thank you.

**Comment by maxmacstn** [comment]
Added the url, let's see whether this time will pass or not :) @ArduinoBot

**Comment by maxmacstn** [comment]
Somehow new release has not been updated. let's try again @ArduinoBot.

**Comment by maxmacstn** [comment]
Thank you, more improvements will coming soon 🎉

**Comment by maxmacstn** [comment]
@ArduinoBot I've updated my library, please kindly check it out.

**Comment by per1234** [comment]
Hi @maxmacstn. The bot here in this repository only handles the submission process. It doesn't have any involvement with adding new releases to the Arduino Library Manager index. That part is handled by [a separate automated system](https://github.com/arduino/libraries-repository-engine) that runs hourly. It checks all the repositories on the list for new releases, checks if those releases meet the requirements for addition to the index, and then adds them.

So once your library has been added to the list, as you accomplished already via this pull request, everything happens automagically after that without any need for you to do anything special.

You can monitor the results of the indexing process via the dedicated web page for your libraries indexing logs here:
http://downloads.arduino.cc/libraries/logs/github.com/maxmacstn/ESP32-Canon-BLE-Remote/
From them, I can see that the latest 1.0.2 release has already been added to the index and is available to the world for installation via Library Manager.

**Pull request merged**
