### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by AsproCompany**
AsproSolarShield By Amir Salama

### CODE REVIEW

**Comment by AsproCompany** [comment]
AsproSolarShield By Amir Salama

**Comment by AsproCompany** [comment]
@ArduinoBot 
AsproSolarShield By Amir Salama

**Comment by AsproCompany** [comment]
@ArduinoBot
first liberary 1.0.0

**Comment by AsproCompany** [comment]
@ArduinoBot
check url

**Comment by AsproCompany** [comment]
@ArduinoBot
 Library Manager

**Comment by per1234** [comment]
Hello @AsproCompany. The automated system here only operates on open pull requests. Since your submission was already accepted and the pull request merged, the bot won't pay any more attention to this pull request.

But this human is happy to provide assistance. Was there something you needed from the bot?

**Pull request merged**
