### PR TITLE
Added PDLS_EXT3_Basic_BWRY

### PR DESCRIPTION
**Pull request by rei-vilo**
https://github.com/rei-vilo/PDLS_EXT3_Basic_BWRY

### CODE REVIEW

**Comment by per1234** [comment]
@ArduinoBot please check it again

**Comment by per1234** [comment]
@ArduinoBot please check it again

**Review by per1234 — COMMENTED** [review]
Hello @rei-vilo. Thanks for your interest in contributing to the Arduino Library Manager index.

I see that the bot found that the library does not meet the requirements for addition in the Arduino Library Manager:

```text
ERROR: Path does not contain a valid Arduino library.                         
       See: https://arduino.github.io/arduino-cli/latest/library-specification
       (Rule LS001)   
```

I verified that the repository does not contain a valid Arduino library at this time due to the lack of any code so I will close this pull request.

Please submit a new pull request here in the Library Manager Registry repository once you have added the library code to your repository and made a Git tag or GitHub release that contains that update.

**Comment by rei-vilo** [comment]
The library is now populated. I have created a new pull-request. Thak you!

**Pull request closed without merging**
