### PR TITLE
Adding a library to Library Manager

### PR DESCRIPTION
**Pull request by Mathieu52**
Adding GPSP

### CODE REVIEW

**Comment by per1234** [comment]
Hello @Mathieu52. I see you have fixed the error reported by the bot. However, Library Manager works exclusively from Git tags, so the bot won't be able to see the fix you made until you create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.

If you look at the repository contents at the latest tag, you can see that the version the bot is checking still has the problem:

https://github.com/Mathieu52/GPSP/blob/1.10/library.properties#L1

```text
name=ArduinoGPSP
```

Remember to update the `version` field in the library's [`library.properties` file](https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format) as needed before making a release/tag.

Once you have done that, simply mention **@ArduinoBot** in a comment here to trigger it to run the automated checks again. After those are passing, your library will automatically be added to Library Manager.

If you have any questions or concerns, please let me know.

Regards, Per

**Comment by Mathieu52** [comment]
@ArduinoBot Fixed

**Comment by per1234** [comment]
@Mathieu52 same problem. Please read my previous comment to understand how to fix it:

https://github.com/arduino/library-registry/pull/2155#issuecomment-1330804451

**Comment by Mathieu52** [comment]
@ArduinoBot Fixed

**Pull request merged**
