### PR TITLE
v1.0.1 ProyectilMx digitalIO

### PR DESCRIPTION
**Pull request by misa3L994**

### CODE REVIEW

**Review by per1234 — COMMENTED** [review]
Hello @misa3L994 . I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will merge this pull request when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by misa3L994** [comment]
@ArduinoBot

**Comment by per1234** [comment]
@misa3L994 please leave the pull request open. As I explained already, the URL change you requested here must be accompanied by a manual operation by the database maintainer. They will do that when they find the time, but if you close the pull request then we won't be able to do it.

So please just be patient and leave the pull request alone!

If you have any questions or concerns, feel free to comment here and I'll provide assistance. Please note that, although this repository does have an automated system for handling library submissions, everything else here is done by humans, not by omniscient robots as some people seem to believe. I am a human, so you must communicate with me as a human.

**Comment by misa3L994** [comment]
Sorry about that

**Review by MatteoPologruto — APPROVED** [review]
Done:
```
2024/11/26 14:58:55 Loaded 7503 libraries from DB
Changing URL of library Proyectil digitalIO from https://github.com/misaproyectil/digitalIO.git to https://github.com/misa3L994/digitalIO.git
Success!
```

**Pull request merged**
