### PR TITLE
Removing deprecated library

### PR DESCRIPTION
**Pull request by maker-zone**
The same functionality of sharing signatures between multiple libraries to make them interchangeable can be achieved without using an interface, so this library was deprecated to avoid wasting space on an arduino.

### CODE REVIEW

**Review by per1234 — COMMENTED** [review]
Hi @maker-zone . I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will close this issue when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by maker-zone** [comment]
I removed one library
UltiBlox DisplayValueCommon
...and just now added another
UltiBlox-SerialCommands
It looks like the bot is thinking I just renamed it.
What's the best way to resolve this? Should I just wait until the previous removal is completed?

**Review by per1234 — COMMENTED** [review]
@maker-zone please submit a separate pull request for each distinct request.

You can have multiple open pull requests by creating a separate [branch](https://docs.github.com/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-branches) in your [fork](https://docs.github.com/get-started/quickstart/fork-a-repo) for the specific changes you want to propose, then submitting a pull request from that branch.

In order to facilitate this workflow, you should never use the `main` branch of your fork to stage changes for a pull request. Instead, the `main` branch should be kept in sync with the parent repository's branch, so it can be used as the base for your pull request branches.

Please remove the change you made to this pull request so that it only contains the change of removing `https://github.com/UltiBlox/DisplayValueCommon`.

**Comment by maker-zone** [comment]
Ah I think I understand my mistake now.
I've removed that addition from this. I hadn't intended to include it in the same PR but didn't realise that it would get included automatically.
From now on I'll use branches other than main for each change.

**Review by MatteoPologruto — APPROVED** [review]
Done:
```
2024/11/26 15:16:39 Loaded 7503 libraries from DB
Removing UltiBlox DisplayValueCommon
Success!
```

**Pull request merged**
