### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by galarb**

### CODE REVIEW

**Comment by per1234** [comment]
Hello @galarb. I see your pull request removes several other libraries in addition to adding `https://github.com/galarb/gyroturn.git`. You can see the changes you are proposing here:

https://github.com/arduino/library-registry/pull/1923/files

If you really are proposing the removal of those libraries then you must provide a clear explanation of why. If the removals are unintentional then please fix your pull request as we cannot accept it in the current state.

**Comment by galarb** [comment]
Hi,
Correct I am trying to create another library as you wrote below. 
But still on clicli...
I keep getting an error message asif “
❌ ERROR: library.properties is missing a name field.

“
I cannot seem to find where the problem is…. I tried so many time changing small things in the library.properties file, to no avail.

Your Help is very much appreciated!

----------------------------------------
Best Regards,
Gal Arbel

Mobile: +972 502158529

On 1 Oct 2022, at 15:14, per1234 ***@***.***> wrote:


Hello @galarb <https://github.com/galarb>. I see your pull request removes several other libraries in addition to adding https://github.com/galarb/gyroturn.git. You can see the changes you are proposing here:

https://github.com/arduino/library-registry/pull/1923/files <https://github.com/arduino/library-registry/pull/1923/files>
If you really are proposing the removal of those libraries then you must provide a clear explanation of why. If the removals are unintentional then please fix your pull request as we cannot accept it in the current state.

**Comment by galarb** [comment]
@ArduinoBot

**Comment by per1234** [comment]
Closing as duplicate of https://github.com/arduino/library-registry/pull/1926

**Pull request closed without merging**
