### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by tabahi**
Added:
https://github.com/tabahi/TabahiConsole
https://github.com/tabahi/ESP-Wifi-Config

### CODE REVIEW

**Comment by tabahi** [comment]
I have added two libraries created by me.

**Review by per1234 — COMMENTED** [review]
Hello . Thanks for your interest in contributing to the Arduino Library Manager index.

I see the bot reported a problem with your submission that will block its acceptance:

> A problem was found with your submission https://github.com/tabahi/ESP-Wifi-Config
>
>❌ ERROR: The repository has no tags. You need to create a [release](https://docs.github.com/en/github/administering-a-repository/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) that matches the version value in the library's library.properties file.

>A problem was found with your submission https://github.com/tabahi/TabahiConsole
>
>❌ ERROR: The repository has no tags. You need to create a [release](https://docs.github.com/en/github/administering-a-repository/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) that matches the version value in the library's library.properties file.

Please fix the problem so we can proceed with your submission.

You will need to do the following things:

1. Create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repositories.
1. Add a comment here in the pull request thread that mentions **@ArduinoBot**.

After that, the automated checks will run again. Once those are passing, your library will automatically be added to Library Manager.

If you have any questions or concerns, please let me know.

Regards, Per

**Comment by per1234** [comment]
@ArduinoBot please check it again.

**Review by per1234 — COMMENTED** [review]
Closing as duplicate of https://github.com/arduino/library-registry/pull/4097 and https://github.com/arduino/library-registry/pull/4098

**Pull request closed without merging**
