### PR TITLE
Update URL of "ESPLogger"

### PR DESCRIPTION
**Pull request by per1234**
Resolves (partially) https://github.com/arduino/library-registry/issues/1557

### CODE REVIEW

**Comment by per1234** [comment]
The validation failure is expected, caused by the name change done at the same time as the URL change. That will be resolved by https://github.com/arduino/library-registry/pull/1560.

**Comment by umbynos** [comment]
@ArduinoBot

**Comment by umbynos** [comment]
The ArduinoLint check is expected to fail since it checks the current [library_index.json](http://downloads.arduino.cc/libraries/library_index.json) which needs an engine run to be updated

**Review by umbynos — APPROVED** [review]

**Comment by umbynos** [comment]
Solved in https://github.com/arduino/library-registry/pull/1560#issuecomment-1178711002

**Pull request merged**
