### PR TITLE
Add Polyline library

### PR DESCRIPTION
**Pull request by RobotGrrl**

### CODE REVIEW

**Comment by RobotGrrl** [comment]
@per1234 Not sure if I borked this with the revert - let me know if so (sorry!), and will try again - thanks!

**Comment by per1234** [comment]
Hi. Yeah, you added the library repository URL to repositories.txt, but then reverted that addition, so the PR is currently for no net change at all to repositories.txt:
https://github.com/arduino/library-registry/pull/156/files

This is why the bot doesn't consider it a submission.

If you add the URL to repositories.txt again in your branch and it will automatically update this PR:
https://github.com/RobotGrrl/library-registry/blob/main/repositories.txt

**Comment by RobotGrrl** [comment]
@ArduinoBot

**Comment by RobotGrrl** [comment]
@per1234 Thank you very much for your assistance! First time contributing a library :)

**Comment by per1234** [comment]
You're welcome. I'm glad to see your library added to Library Manager.
Regards, Per

**Pull request merged**
