### PR TITLE
OTAUpdateManager

### PR DESCRIPTION
**Pull request by raghulrajg**

### CODE REVIEW

**Comment by raghulrajg** [comment]
@ArduinoBot

**Comment by per1234** [comment]
Hello @raghulrajg. The automated system here only operates on open pull requests. Since your submission was already accepted and the pull request merged, the bot won't pay any more attention to this pull request.

But this human is happy to provide assistance. Was there something you needed from the bot?

**Comment by raghulrajg** [comment]
> Hello @raghulrajg. The automated system here only operates on open pull requests. Since your submission was already accepted and the pull request merged, the bot won't pay any more attention to this pull request.
> 
> But this human is happy to provide assistance. Was there something you needed from the bot?

I try find my library in Arduino library manager, i can't find out

**Comment by per1234** [comment]
The job that indexes the libraries runs hourly. After that, the update must propagate through the cache, which takes some time. We give a conservative estimate of availability within one day's time.

I see that the library is already available in my Library Manager:

image

Please check your Library Manager again.

**Comment by raghulrajg** [comment]
Thank you for response, yes I find my library but Ardu-badge not be found https://www.ardu-badge.com/OTAUpdateManager

> The job that indexes the libraries runs hourly. After that, the update must propagate through the cache, which takes some time. We give a conservative estimate of availability within one day's time.
> 
> I see that the library is already available in my Library Manager:
> 
> image
> 
> Please check your Library Manager again.

Thank you for your response, yes I find my library but Ardu-badge not be found https://www.ardu-badge.com/OTAUpdateManager

**Comment by per1234** [comment]
"ArduBadge" is a 3rd party service. Arduino does not have any involvement in the maintenance of that project so reports of problems with ArduBadge are off topic here.

Please report the problem via the issue tracker of the ArduBadge repository:

https://github.com/gilmaimon/ArduBadge/issues

I did a quick check and it looks like a long-standing problem. For example, the "EspNowCam" library was added to Library Manager 2024-01-29:

https://github.com/arduino/library-registry/commit/1058d61903363ed256371e9b55be847321cccc38

Yet it has not been picked up by ArduBadge:

https://www.ardu-badge.com/EspNowCam

Conversely, the "Logistics" library was added to Library Manager 2024-01-04:

https://github.com/arduino/library-registry/commit/3cde734c48fbd062a5118b7fac24b481dd014905

And it was picked up by ArduBadge:

https://www.ardu-badge.com/Logistic

I didn't investigate further, but this indicates the problem might have started sometime between 2024-01-04 and 2024-01-29. This matches with the timing of this report of previously submitted libraries which were picked up, but are now not receiving version updates: https://github.com/gilmaimon/ArduBadge/issues/28

**Comment by raghulrajg** [comment]
@ArduinoBot

**Comment by per1234** [comment]
Hello @raghulrajg. The automated system here only operates on open pull requests. Since your submission was already accepted and the pull request merged, the bot won't pay any more attention to this pull request.

But this human is happy to provide assistance. Was there something you needed from the bot?

**Pull request merged**
