### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by SergeSkor**

### CODE REVIEW

**Comment by SergeSkor** [comment]
@ArduinoBot

**Comment by SergeSkor** [comment]
@ArduinoBot

**Comment by per1234** [comment]
Hi @SergeSkor. Please disregard the last comment from the bot:
>❌ ERROR: Your submission meets all requirements. However, the pull request could not be merged.

This was made in error due to the automated system having been triggered redundantly by your mention of **@A[]()rduinoBot** while the original checks were already in progress. I have taken note of this confusing behavior and put it on my "to do" list to improve the system so it will behave correctly under these somewhat unusual conditions.

**Comment by SergeSkor** [comment]
> Hi @SergeSkor. Please disregard the last comment from the bot:
> 
> > ❌ ERROR: Your submission meets all requirements. However, the pull request could not be merged.
> 
> This was made in error due to the automated system having been triggered redundantly by your mention of **@ArduinoBot** while the original checks were already in progress. I have taken note of this confusing behavior and put it on my "to do" list to improve the system so it will behave correctly under these somewhat unusual conditions.

It may be may mistake, but not sure for 100% ... 
I might have mentioned bot twice in a row...

**Comment by per1234** [comment]
>I might have mentioned bot twice in a row within few seconds...

That was indeed the cause. This caused two independent copies of the checks to run simultaneously. They both found the submission valid and so attempted to merge the pull request. The first job was successful in merging the pull request. The second job's attempt to merge failed because the pull request was already merged by the first pull request and you can only merge a pull request once.

>It may be my mistake

Not really because the system should either prevent or effectively communicate the problem when the user does something unexpected. It did neither of those. I have already improved [the handling of merge failures](https://github.com/arduino/library-registry/blob/9a745998a12d841bdc7b1392ca9c4bcf89d414a1/.github/workflows/manage-prs.yml#L498-L542) a little bit since yesterday (though unfortunately it doesn't cover this exact cause) and have a tentative plan for an approach to preventing this particular problem entirely.

**Pull request merged**
