### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by pranavdhage**

### CODE REVIEW

**Comment by pranavdhage** [comment]
@ArduinoBot

**Comment by pranavdhage** [comment]
@ArduinoBot

**Comment by per1234** [comment]
Hello @pranavdhage. The automated system here only operates on library submissions. Since your submission was already accepted and the pull request merged, the bot won't pay any more attention to this pull request.

But this human is happy to help. What was it you wanted from the bot?

**Comment by pranavdhage** [comment]
@ArduinoBot

**Pull request merged**
