### PR TITLE
URL Change

### PR DESCRIPTION
**Pull request by AITINKR**
URL Change

### CODE REVIEW

**Comment by AITINKR** [comment]
@ArduinoBot

**Review by per1234 — COMMENTED** [review]
Hello @AITINKR. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will merge this pull request when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Review by per1234 — COMMENTED** [review]
@AITINKR I see you made another commit to the `main` branch of your repository that adds the URL `https://github.com/AITINKR/AITINKR_AIOT_DEVBOARD` to the list.

All commits you add to a branch in your fork repository are included in the pull request that was submitted from that branch. You submitted this pull request from the `main` branch in your fork, so you _**MUST NOT**_ push any additional commits to the `main` branch.

Please create a new branch in your fork, add the `https://github.com/AITINKR/AITINKR_AIOT_DEVBOARD` URL to the repositories.txt file in that branch, and then submit an additional pull request for the submission of `https://github.com/AITINKR/AITINKR_AIOT_DEVBOARD`.

If you have any questions or problems while doing that, just let me know and I'll provide assistance.

**Review by MatteoPologruto — APPROVED** [review]
Done:
```
2023/10/18 14:54:55 Loaded 6280 libraries from DB
Removing AITINKR_SHEILDS
Success!
```

**Pull request merged**
