### PR TITLE
Update Repository Name Supabase-ESP32 to Supabase-Arduino

### PR DESCRIPTION
**Pull request by zumatt**

### CODE REVIEW

**Review by per1234 — COMMENTED** [review]
Hello @zumatt. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will merge this pull request when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by zumatt** [comment]
Hello @per1234 thank you!

No problem for that I can imagine that this is not easy.

**Review by MatteoPologruto — APPROVED** [review]
Done:
```
2024/03/14 16:11:05 Loaded 6744 libraries from DB
Changing URL of library Supabase-ESP32 from https://github.com/zumatt/Supabase-ESP32.git to https://github.com/zumatt/Supabase-Arduino.git
Success!
```

**Comment by zumatt** [comment]
Dear @MatteoPologruto 

thank you for merging my Library.
Anyway, there's a problem with the library name.

If I check the link https://downloads.arduino.cc/libraries/logs/github.com/zumatt/Supabase-Arduino/ 
the last logs say:
```
2024/03/18 15:34:11 Checking out tag: 1.0.3
2024/03/18 15:34:11 Release Connect Arduino-Supabase:1.0.2 has wrong library name, should be Supabase-ESP32
```

You know how can I fix this?
I checked all the files inside the library and there's no more a connection to the old name.

Thank you,
Matteo.

**Comment by per1234** [comment]
Hello @zumatt. We only updated the repository URL in the registry. The library is locked to the name that is defined in the registry, which is `Supabase-ESP32`. If you would like to change the registered name, please submit a name change request by following the procedure documented here:

https://github.com/arduino/library-registry/blob/main/FAQ.md#how-can-i-change-a-librarys-name

Please let me know if you have any questions or concerns.

**Pull request merged**
