### PR TITLE
Add Deneyap Servo Library

### PR DESCRIPTION
**Pull request by DogushC**
Add Deneyap Servo Library

### CODE REVIEW

**Comment by DogushC** [comment]
> * `@ArduinoBot`

@ArduinoBot

**Comment by DogushC** [comment]
@ArduinoBot

**Comment by DogushC** [comment]
@ArduinoBot

**Comment by DogushC** [comment]
@ArduinoBot

**Comment by pxsty0** [comment]
@ArduinoBot

**Comment by per1234** [comment]
Hello @pxsty0. The automated system here only operates on open pull requests. Since your submission was already accepted and the pull request merged, the bot won't pay any more attention to this pull request.

But this human is happy to provide assistance. Was there something you needed from the bot?

**Pull request merged**
