### PR TITLE
Update URL for https://github.com/RobTillaart/MCP23S17

### PR DESCRIPTION
**Pull request by RobTillaart**
@per1234 
https://github.com/RobTillaart/MCP23S17 is registered by my mistake as https://github.com/RobTillaart/MCP23S17_RT and therefore it does not appear in the library manager.

### CODE REVIEW

**Comment by per1234** [comment]
Hi @RobTillaart. The requested change is now in progress.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests and closes those issues/PRs when that is done. If you are subscribed PR, you'll get a notification at that time: https://github.com/arduino/library-registry/pull/906

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by umbynos** [comment]
Nothing to do there

**Comment by RobTillaart** [comment]
@umbynos 

See https://downloads.arduino.cc/libraries/logs/github.com/RobTillaart/MCP23S17/

The URL of the library in my first commit was incorrect, that still needs to be fixed. 

The correct URL is **https://github.com/RobTillaart/MCP23S17**  without the _RT

**Comment by per1234** [comment]
Hello @RobTillaart.

>The URL of the library in my first commit was incorrect, that still needs to be fixed.

The URL was correct from the start. Here it is in your submission PR:
https://github.com/arduino/library-registry/pull/872/files
and here in the file:
https://github.com/arduino/library-registry/blob/727f50ea74c90e2cf1a83bcf19e7006d2c14054d/repositories.txt#L3193

The "wrong library name" mentioned in the logs:
```
2022/01/19 16:22:16 Scraping https://github.com/RobTillaart/MCP23S17.git
2022/01/19 16:22:16 Checking out tag: 0.1.0
2022/01/19 16:22:16 Release MCP23S17:0.1.0 has wrong library name, should be MCP23S17_RT
2022/01/19 16:22:16 Checking out tag: 0.1.1
2022/01/19 16:22:16 Release MCP23S17:0.1.1 has wrong library name, should be MCP23S17_RT
2022/01/19 16:22:16 Checking out tag: 0.1.2
2022/01/19 16:22:16 Release MCP23S17:0.1.2 has wrong library name, should be MCP23S17_RT
```
is referring to the `name` value in the `library.properties` metadata file, not the repository name in the URL.

At the time of the submission, the library is pinned to the current `name` value. Because this is the sole unique identifier for the library, any tag which uses a different name is rejected by the indexer job.

That name is recorded in a separate file here:
https://github.com/arduino/library-registry/blob/8cbdf75d2ea7fb86fc40b290ab36ab7a6aae6c1a/registry.txt#L4632
It was changed from "MCP23S17_RT" to "MCP23S17" according to your request by this PR: https://github.com/arduino/library-registry/pull/906/files

>I still can not access the lib through the library manager.

The indexer job runs hourly. After that, the updated library index must also propagate through the local cache. We give a conservative estimate of one day maximum delay before the library will become available through Library Manager.

Please let me know if you have any questions or concerns.

**Pull request closed without merging**
