### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by The-Young-Maker**

### CODE REVIEW

**Comment by The-Young-Maker** [comment]
@ArduinoBot

**Comment by The-Young-Maker** [comment]
@ArduinoBot

**Comment by per1234** [comment]
Hello @The-Young-Maker. The automated system here only operates on open pull requests. Since your submission was already accepted and the pull request merged, the bot won't pay any more attention to this pull request.

But this human is happy to provide assistance. Was there something you needed from the bot?

**Comment by The-Young-Maker** [comment]
It's because I was not sure about if the syatem will fetch the new version automatically or not.

**Comment by per1234** [comment]
It will. After the initial addition of the library, the indexer job periodically checks each of the libraries in the index and picks up any new release/tag that meets the requirements listed here:

https://github.com/arduino/library-registry/blob/main/FAQ.md#what-are-the-requirements-for-publishing-new-releases-of-libraries-already-in-the-library-manager-list

This means there is no need to take any additional action to add new releases of your library to Library Manager. They will be added automagically!

It does take a little time for the indexer job to run, and then some additional time after that for the update to propagate through the CDN and the local cache. But it will get there. We give a conservative estimate of availability within one day's time.

You can monitor the indexing of the library releases by checking the library's dedicated indexer logs web page:

http://downloads.arduino.cc/libraries/logs/github.com/The-Young-Maker/OpenMenuOS/

**Comment by The-Young-Maker** [comment]
Thanks for the information!

**Comment by The-Young-Maker** [comment]
It's been one day since I release my version 1.0.2 (I solved a LOT of problem) but still no logs from the indexer and I checked with Arduino-Lint and there is no problem with the library. Do you know why?

**Comment by per1234** [comment]
> my version 1.0.2

I guess you meant to write "1.0.2-beta". 

## Problem

The problem is shown here in [the "OpenMenuOS" library's dedicated indexer logs web page](http://downloads.arduino.cc/libraries/logs/github.com/The-Young-Maker/OpenMenuOS/):

```text
2024/02/27 07:33:14 Checking out tag: 1.0.2-beta
2024/02/27 07:33:14 Release OpenMenuOS:1.0.1-beta already loaded, skipping
```

Unfortunately, the logs don't communicate about this particular thing very well, but what this tells us is that the `version` value in [the `library.properties` metadata file](https://arduino.github.io/arduino-cli/latest/library-specification/#library-metadata) was not updated before creating the `1.0.2-beta` tag (note that the indexer checked out tag `<!-- TODO_TAG_NAME -->`, only to find the release version was `1.0.1-beta`).

You can see it here:

https://github.com/The-Young-Maker/OpenMenuOS/blob/1.0.2-beta/library.properties#L2

```text
version=1.0.1-beta
```

Even though [Git tags](https://git-scm.com/book/en/v2/Git-Basics-Tagging) are the unit of release for the Arduino Library Manager, all versioning is done according to the `version` field of the [`library.properties` file](https://arduino.github.io/arduino-cli/latest/library-specification/#library-metadata).

For this reason, the indexer will reject any tag that has the same value in its `version` field as a release already in the index.

## Solution

The solution is to make another release of the library which meets [the requirements](https://github.com/arduino/library-registry/blob/main/FAQ.md#what-are-the-requirements-for-publishing-new-releases-of-libraries-already-in-the-library-manager-list):

1. Update the `version` value in `library.properties` to the version that will be used for the new release.
1. Create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.

The indexer system will pick up that new release and it will be available from Library Manager within a day.

The non-compliant release will still be missing, but since the newer release will be available, that is no problem.

Please let me know if you have any questions or concerns.
Regards, Per

**Comment by The-Young-Maker** [comment]
The only thind I have is this :

 ```2024/02/26 00:32:55 Scraping https://github.com/The-Young-Maker/OpenMenuOS.git
2024/02/26 00:32:55 Checking out tag: 1.0.0-beta
2024/02/26 00:32:56 Arduino Lint has suggestions for possible improvements:
Click to expand Arduino Lint report

2024/02/26 00:32:58 Checking out tag: 1.0.1-beta
2024/02/26 00:32:58 Release OpenMenuOS:1.0.0-beta already loaded, skipping
2024/02/26 00:32:58 Arduino Lint has suggestions for possible improvements:
Click to expand Arduino Lint report```

**Comment by per1234** [comment]
Try doing a "[hard reload](https://support.google.com/chrome/answer/157179?hl=en&co=GENIE.Platform%3DDesktop#zippy=%2Ctab-window-shortcuts%2Cgoogle-chrome-feature-shortcuts%2Caddress-bar-shortcuts%2Cwebpage-shortcuts:~:text=Reload%20the%20current%20page%2C%20ignoring%20cached%20content)" of the page to see if that will get you the current content.

**Comment by The-Young-Maker** [comment]
Still not there. I even tried in private navigation and same problem.

**Comment by per1234** [comment]
Unfortunately I don't know what could cause this. I'm not very knowledgeable about web things.

This is what I see on the page (with or without a "hard reload"):

```text
2024/02/27 13:33:13 Scraping https://github.com/The-Young-Maker/OpenMenuOS.git
2024/02/27 13:33:13 Checking out tag: 1.0.0-beta
2024/02/27 13:33:13 Release OpenMenuOS:1.0.0-beta already loaded, skipping
2024/02/27 13:33:13 [Arduino Lint](https://arduino.github.io/arduino-lint/latest/) has suggestions for possible improvements:
Click to expand Arduino Lint report

2024/02/27 13:33:13 Checking out tag: 1.0.1-beta
2024/02/27 13:33:13 Release OpenMenuOS:1.0.0-beta already loaded, skipping
2024/02/27 13:33:13 [Arduino Lint](https://arduino.github.io/arduino-lint/latest/) has suggestions for possible improvements:
Click to expand Arduino Lint report

2024/02/27 13:33:13 Checking out tag: 1.0.2-beta
2024/02/27 13:33:13 Release OpenMenuOS:1.0.1-beta already loaded, skipping
2024/02/27 13:33:13 [Arduino Lint](https://arduino.github.io/arduino-lint/latest/) has suggestions for possible improvements:
Click to expand Arduino Lint report
```

We did receive another report of the same problem but they never reported back about whether the content was updated after a "hard reload" of the page:

https://forum.arduino.cc/t/library-update-not-publishing/1226480/3

Note [this comment](https://forum.arduino.cc/t/library-update-not-publishing/1226480/4):

> I looked on a different PC using a VPN, and it shows the updated page.
Not sure why it is cached on my normal PC

**Comment by The-Young-Maker** [comment]
Not sure what i did but I cleared the cache and I went on a VPN and then disconnected from it and it worked. However, I sent it to my teacher (on his computer) and he had the same problem as me. Definitely a problem with the server.

**Pull request merged**
