### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by nthnn**

### CODE REVIEW

**Review by per1234 — COMMENTED** [review]
Hello @nthnn. I see this pull request removes a library URL from the list. Please tell me what was the reason so that I can be sure to handle the request correctly.

**Comment by nthnn** [comment]
Hello @per1234 There are some mistakes on this library. Also, I've already made the repository hidden. Hence, I'd like to remove it from the list. Thank you!

**Review by per1234 — COMMENTED** [review]
Thanks for the clarification. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will merge this pull request when it is done. You will get a notification from GitHub at that time.

**Comment by njh** [comment]
@nthnn do you have any information about why you wanted your repo to be deleted from the Arduino Library manager?

**Comment by nthnn** [comment]
> Hello @per1234 There are some mistakes on this library. Also, I've already made the repository hidden. Hence, I'd like to remove it from the list. Thank you!

@njh

**Review by MatteoPologruto — APPROVED** [review]
Done:
```
2024/01/11 14:13:21 Loaded 6530 libraries from DB
Removing diwa
warning: Library Git clone folder /home/ubuntu/workspace/gitclones/github.com/nthnn/Diwa not present
Success!
```

**Pull request merged**
