### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by DinuraPasan**

### CODE REVIEW

**Comment by DinuraPasan** [comment]
@ArduinoBot

**Review by jursoleo — APPROVED** [review]

**Comment by per1234** [comment]
Hello @DinuraPasan.  Thanks for your interest in contributing to the Arduino Library Manager index.

I see the bot reported a problem with your submission that will block its acceptance:

```text
ERROR: Library name Arduino_Core_Libraries starts with "Arduino". These names are reserved for official libraries.
       See: https://arduino.github.io/arduino-cli/latest/library-specification/#libraryproperties-file-format     
       (Rule LP012)  
```

If you have any questions or problems while following the instructions to resolve the problem, please let me know and I'll help out.

If you decide you no longer wish to submit the library, you can close this pull request.

**Comment by jursoleo** [comment]
Hi Dinura ..

                The  ‘Arduino’   directory names .. I did not create any of that.  Githug tools apparently created all that .. I simply loaded  my files into the fork it created.  That fork is under the Arduino-libraries  ‘root’  or sub-dir  and I assume my upload dir has to be under that so that this library will appear in the Arduino Lib Manager.

 

I have to say … the GitHub  process is pretty incomprehensible, and I’m an old Engineer with grey hair so I’ve been around since there was a lot of command-line computer interaction.  But I have no understanding of what is going on – just trying to publish my library so users can retrieve it through Arduino IDE.

 

I have no idea what to do about the  references to  //Arduino … in the path below.  Any help you can provide will be appreciated.

 

--John

**Comment by jursoleo** [comment]
Deleted the entire repository.  Could make no sense of the tools and do not have time to waste with nonsense.

**Comment by per1234** [comment]
>the GitHub  process is pretty incomprehensible, and I’m an old Engineer with grey hair so I’ve been around since there was a lot of command-line computer interaction.  But I have no understanding of what is going on – just trying to publish my library so users can retrieve it through Arduino IDE.

I'm happy to provide assistance and to take action to improve the documentation based on your feedback. But we already have a thread dedicated to that in your own pull request: https://github.com/arduino/library-registry/pull/2461, so please confine any further discussion to that thread instead of using @DinuraPasan's pull request to discuss your difficulties submitting a library.

**Pull request closed without merging**
