### PR TITLE
ESP32QuantumAlgorithm

### PR DESCRIPTION
**Pull request by Manojshyaam**

### CODE REVIEW

**Review by per1234 — COMMENTED** [review]
Hello @Manojshyaam. Thanks for your interest in contributing to the Arduino Library Manager index.

I see the bot reported a problem with your submission that will block its acceptance:

> ❌ ERROR: The repository has no tags. You need to create a [release](https://docs.github.com/en/github/administering-a-repository/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) that matches the version value in the library's library.properties file.

I looked at your repository and see that there is an additional problem, which is that you added the library to the repository as a ZIP file. The repository must contain the library files in order to be allowed in the Arduino Library Manager. It is also just a terrible idea in general to store your code in a ZIP file because you lose all the benefits of a source code repository. GitHub even automatically generates a ZIP file from the source code files in a repository to make it easy for people to download, so your approach is completely unnecessary.

Please fix the problem so we can proceed with your submission. You should carefully study the full list of requirements for inclusion in the Arduino Library Manager to make sure your library is compliant:

https://github.com/arduino/library-registry/blob/main/FAQ.md#what-are-the-requirements-for-a-library-to-be-added-to-library-manager

You will need to do the following things:

1. Bring your library repository into full compliance with the requirements.
1. Create a new [release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) or [tag](https://git-scm.com/docs/git-tag) in the library repository.
1. Add a comment here in the pull request thread that mentions **@ArduinoBot**.

After that, the automated checks will run again. Once those are passing, your library will automatically be added to Library Manager.

If you have any questions or concerns, please let me know. I'm happy to help you to achieve a successful library submission.

Regards, Per

**Comment by Manojshyaam** [comment]
@ArduinoBot

**Comment by Manojshyaam** [comment]
@ArduinoBot

**Comment by Manojshyaam** [comment]
@ArduinoBot

**Review by per1234 — COMMENTED** [review]
@Manojshyaam I took a look at your code and I see this is not a library. As the name indicates, Arduino Library Manager is only for Arduino libraries so we will not be able to accept this.

**Pull request closed without merging**
