### PR TITLE
Update repositories.txt for new URL of CodeDebugScope Library

### PR DESCRIPTION
**Pull request by boseji**
Hello,

On behalf of the Author - Albert van Dalen <http://www.avdweb.nl>

Requesting a URL Update the Library `CodeDebugScope`

New Repository Location:

<https://github.com/avdwebLibraries/avdweb_CodeDebugScope>

Kindly help us out.

### CODE REVIEW

**Comment by boseji** [comment]
Please guide me if I made any mistake in this pull request.

This is first time I am requesting for an Update the repository name.

The reason being that the [Author](https://github.com/avandalen) has decide to shift all their libraries to a new [organization](https://github.com/avdwebLibraries).

This is to enable more engagement with their community and open-source development.

Kindly help us on this.

**Review by per1234 — COMMENTED** [review]
Hello @boseji. I am confirming your request.

Unlike submissions, this type of request is still handled manually. The Library Manager index maintainer occasionally comes through to clear all the outstanding requests. They will merge this pull request when it is done. You will get a notification from GitHub at that time.

After that, you can monitor the indexing of the library via its dedicated logs web page.
Information about that here:
https://github.com/arduino/library-registry/blob/main/FAQ.md#can-i-check-on-library-releases-being-added-to-library-manager

**Comment by boseji** [comment]
Thank you for the Help.

I have prepared the special Library URL as demonstrated in the Help document.

Old Repository logs available from:

<http://downloads.arduino.cc/libraries/logs/github.com/avandalen/avdweb_CodeDebugScope/>

New Repository logs that will be available when the new URL becomes active 

<http://downloads.arduino.cc/libraries/logs/github.com/avdwebLibraries/avdweb_CodeDebugScope/>

The new release has already got picked up thanks to github re-routing:

```log
2024/08/23 15:37:13 Checking out tag: 0.0.1
2024/08/23 15:37:13 Release CodeDebugScope:0.0.1 already loaded, skipping
```

### Just one more question : 

Do I update all the repository URL in one pull request or do it sequentially for each library ?

(as there are multiple libraries being moved)

Thanks again for the generous help and guidance.

**Comment by per1234** [comment]
> The new release has already got picked up thanks to github re-routing:

Yeah, when the library repository URL changes as the result of the library maintainer using GitHub's rename or transfer features, GitHub automatically creates a redirect and this allows the Library Manager indexer to continue to be able to monitor the repository even though it has the old URL.

However, it is still recommended for the library maintainer to submit a URL update as you have done here so that we aren't reliant on that redirect (for which which we don't have any guarantees of working forever).

> Do I update all the repository URL in one pull request or do it sequentially for each library ?

You can take whichever approach you prefer. I personally prefer to use a separate pull request for each library because this way if there was a problem with the operation for one library it wouldn't block the operation for the other libraries. But such a situation rarely occurs.

**Comment by boseji** [comment]
Thanks a lot for your guidance,

I will follow the step by step approach.
And will do One library at a time.

Ensure that the migration happens from the Logs as well.
Then move to the next one.

Looking forward to follow suit for my older libraries also.
I had quite a few before the malicious 2021 take-down notices.

Thanks to Arduino and the whole open-source we will prevail and prosper.

**Review by MatteoPologruto — APPROVED** [review]
Done:
```
2024/09/12 16:03:57 Loaded 7292 libraries from DB
Changing URL of library CodeDebugScope from https://github.com/avandalen/avdweb_CodeDebugScope.git to https://github.com/avdwebLibraries/avdweb_CodeDebugScope.git
Success!
```

**Pull request merged**
