### PR TITLE
clicli.txt

### PR DESCRIPTION
**Pull request by galarb**

### CODE REVIEW

**Comment by galarb** [comment]
@ArduinoBot

**Comment by per1234** [comment]
Hello @galarb. The automated system here only operates on open pull requests. Since your submission was already accepted and the pull request merged, the bot won't pay any more attention to this pull request.

But this human is happy to provide assistance. Was there something you needed from the bot?

**Comment by per1234** [comment]
We give a conservative estimate that the new release should be available for installation everywhere within one day's time.

You can monitor the process by checking the logs from the Library Manager indexer on the dedicated web page for your library here:

http://downloads.arduino.cc/libraries/logs/github.com/galarb/clicli/

However, even after the tag is shown as processed on that page, there will be some additional delay as the updated index works its way through the CDN and local caches to become available in the Library Manager of the user's IDE.

**Comment by galarb** [comment]
Thanks for your support,

Another question if I may,
Why are my examples not showing in the file\examples\clicli menu?
Thanks inn advance,

----------------------------------------
Best Regards,
Gal Arbel

Mobile: +972 502158529

On 9 Oct 2022, at 17:10, per1234 ***@***.***> wrote:


We give a conservative estimate that the new release should be available for installation everywhere within one day's time.

You can monitor the process by checking the logs from the Library Manager indexer on the dedicated web page for your library here:

http://downloads.arduino.cc/libraries/logs/github.com/galarb/clicli/ <http://downloads.arduino.cc/libraries/logs/github.com/galarb/clicli/>
However, even after the tag is shown as processed on that page, there will be some additional delay as the updated index works its way through the CDN and local caches to become available in the Library Manager of the user's IDE.

**Comment by per1234** [comment]
Because your example is not a valid sketch:

Spaces are not allowed in sketch names.

A sketch is a folder. The folder name must match the primary `.ino` filename.

Your current invalid attempt at creating an example sketch looks like this:

```text
examples/
└── simple usage.ino
```

A valid example sketch would look like this:

```text
examples/
└── SimpleUsage/
    └── SimpleUsage.ino
```

Please take the time to read the Arduino Sketch Specification to learn all about the Arduino sketch format:

https://arduino.github.io/arduino-cli/latest/sketch-specification/

**Pull request merged**
