### PR TITLE
Revert "Update repositories.txt"

### PR DESCRIPTION
**Pull request by nthnn**
Reverts arduino/library-registry#3154

### CODE REVIEW

**Review by per1234 — COMMENTED** [review]
@nthnn please provide a detailed explanation of what you are intending to accomplish with this PR. I get the feeling you are maybe trying to find some alternative approach to accomplishing the name change you requested previously (https://github.com/arduino/library-registry/issues/3172).

Please understand that, although submissions are handled by an automated system, all other requests such as this one are handled by humans. So you must make the effort to communicate in a human manner when making such requests.

**Comment by nthnn** [comment]
@per1234 My bad. You're right. I am trying to apply the updates on the library I'm trying to submit. And I can't seem to succeed.

Thank you!

**Comment by per1234** [comment]
>I am trying to apply the updates on the library I'm trying to submit. And I can't seem to succeed.

I'm sorry, but I still don't understand what you are trying to accomplish. Please provide a detailed answer for each of the following questions:

- What is the result you hope to achieve through this pull request?
- What is the reason you want to achieve that result?

I can surely help you to efficiently achieve your goal and to answer any questions you might have about the Library Manager system. But I can only do that if I understand what you need.

**Comment by nthnn** [comment]
I've added a submission of my library link on the registry. Upon submission, the Arduino Lint warned me to change my library's main source file name, but it didn't warned me that the library name was already in use. And so, I can't find my library on the Library Manager of Arduino IDE.

I tried to update my library's repository name here on GitHub and the library name itself (library.properties) and submitted a pull request that contains the updated GitHub repository link of the library, again, on the registry. But this happened, I skipped reading the instructions. My bad.

Now, I want to re-submit my library to the registry with its updated library name, so it won't collide with the already in-use library of the same name. Thank you!

**Review by per1234 — COMMENTED** [review]
>Now, I want to re-submit my library to the registry with its updated library name, so it won't collide with the already in-use library of the same name.

That is not allowed. We have a standardized procedure for requesting library name changes. You already made that request:

https://github.com/arduino/library-registry/issues/3172

I already confirmed the request and explained to you that you only need to  wait for the database maintainer to accommodate your request:

https://github.com/arduino/library-registry/issues/3172#issuecomment-1664944985

So please. Just stop submitting new pull requests, closing issues, etc. The process is already initiated. You only need to be patient. All this flailing around only wastes both our time and might even cause a delay in the name change.

**Pull request closed without merging**
