### PR TITLE
Revert "Update repositories.txt"

### PR DESCRIPTION
**Pull request by adrian2793**
Reverts arduino/library-registry#4409

### CODE REVIEW

**Comment by adrian2793** [comment]
@per1234 I want to delete it since I changed the name of the repository and I didn't wanted to make a name change request

**Comment by per1234** [comment]
Ugh. I see now that you submitted it again at https://github.com/arduino/library-registry/pull/4411

I also see that this is the second time you have requested a removal of this library: https://github.com/arduino/library-registry/pull/4245

Although the submission system is automated, the other requests are time consuming. You are making a lot of work for us. For the benefit of the community, Arduino has opened the Library Manager distribution service to everyone instead of restricting it to only official libraries. If every one of the thousands of library maintainers started removing and re-adding libraries unnecessarily we would have to stop offering this service to the community so the way you are behaving is irresponsible.

Since it was added twice, we will proceed with removing the URL as you requested here, but in the future, please only request library removals if it is absolutely essential to do so, such as if a library becomes completely obsolete. Removals must only be requested if you plan to permanently remove the library. This behavior of removing and then re-adding libraries is not allowed.

**Review by MatteoPologruto — APPROVED** [review]
Done:
```
2024/04/29 16:00:58 Loaded 6877 libraries from DB
Changing URL of library AISwitch from https://github.com/arduino279/ArduinoAI.git to https://github.com/arduino279/AI.git
Success!
```

**Review by adrian2793 — COMMENTED** [review]
Yea, good work, mate! This is a review for you : )

**Pull request merged**
