### PR TITLE
add AvrFHT library

### PR DESCRIPTION
**Pull request by ArthurKoba**

### CODE REVIEW

**Comment by ArthurKoba** [comment]
update

**Comment by ArthurKoba** [comment]
@ArduinoBot

**Comment by per1234** [comment]
Hello @ArthurKoba. The automated system here only operates on open pull requests. Since your submission was already accepted and the pull request merged, the bot won't pay any more attention to this pull request.

But this human is happy to provide assistance. Was there something you needed from the bot?

**Comment by ArthurKoba** [comment]
Hello @per1234. I really need help. I've added my library to the repository, but it's still not being discovered. I pinged the bot to check and update the repository, but nothing came of it. I had problems with the title being incorrectly formatted before, I fixed that and also created a new release with a new label. However, three days have already passed and the library does not appear in the list.

**Comment by per1234** [comment]
Hi @ArthurKoba. You can see the problem by looking at your library's dedicated Library Manager indexer logs page:

https://downloads.arduino.cc/libraries/logs/github.com/KobaProduction/AvrFHT/

```text
2024/08/13 09:37:11 Scraping https://github.com/KobaProduction/AvrFHT.git
2024/08/13 09:37:12 Checking out tag: v1.1.1
2024/08/13 09:37:12 Release AvrFHT:1.1.1 has wrong library name, should be AVR FHT Library
```

The name of your library (as defined by the `name` field of [its `library.properties` metadata file](https://github.com/KobaProduction/AvrFHT/blob/master/library.properties)) was set to "AVR FHT Library" at the time the library was registered here. After that time, you changed the library name to "AvrFHT" (https://github.com/KobaProduction/AvrFHT/commit/09d4c93ca21be3cd9fd871dff46e6a7e2ee4b739).

As documented [in the FAQ](https://github.com/arduino/library-registry/blob/main/FAQ.md#what-are-the-requirements-for-publishing-new-releases-of-libraries-already-in-the-library-manager-list), the Arduino Library Manager indexer system does not accept any releases that have a name defined in its [`library.properties` metadata file](https://arduino.github.io/arduino-cli/latest/library-specification/#library-metadata) which is different from the one the library had at the time of the registration.

The reason for this restriction is that this is the unique identifier for the library, meaning that any changes to the identifier might cause problems to users who rely on the established identifier in command line operations or for other library developers who have defined it as one of their dependencies.

If you do need to change the name, you can submit a request, following the instructions provided here:

https://github.com/arduino/library-registry/blob/main/FAQ.md#how-can-i-change-a-librarys-name

**Pull request merged**
